-- Catálogo oficial RCD: centros de secundaria de la provincia de Toledo.
-- Fuente: https://www.educacion.gob.es/centros/

insert into public.postal_locations (postal_code, municipality, province, autonomous_region)
values ('45200', 'Illescas', 'Toledo', 'Castilla-La Mancha')
on conflict (postal_code, municipality) do update set
  province = excluded.province,
  autonomous_region = excluded.autonomous_region;

insert into public.centers
  (official_code, name, generic_name, municipality, province, autonomous_region, ownership, source_url, is_active)
values
('45006049','SAN BLAS','Instituto de Educación Secundaria','Añover de Tajo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005653','JULIO VERNE','Instituto de Educación Secundaria','Bargas','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006050','LA JARA','Instituto de Educación Secundaria Obligatoria','Belvís de la Jara','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005781','VIRGEN DE LA ENCINA','Centro Privado de Educación Infantil Primaria y Secundaria','Calypo Fado','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45012128','BLAS DE PRADO','Instituto de Educación Secundaria','Camarena','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45011859','LIBERTAD','Instituto de Educación Secundaria','Carranque','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006062','ARENALES DEL TAJO','Instituto de Educación Secundaria','Cebolla','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45000734','CONSABURUM','Instituto de Educación Secundaria','Consuegra','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45000758','FUNDACION DIAZ-CORDOVES SEGOVIANO','Centro Privado de Educación Infantil Primaria y Secundaria','Corral de Almaguer','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45005801','LA BESANA','Instituto de Educación Secundaria','Corral de Almaguer','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45014204','JOSEFINA ALDECOA','Instituto de Educación Secundaria','El Señorío de Illescas','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45014745','IESO Nº 4','Instituto de Educación Secundaria Obligatoria','El Señorío de Illescas','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006074','LAZARILLO DE TORMES','Instituto de Educación Secundaria','Escalona','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45010387','ALONSO QUIJADA','Instituto de Educación Secundaria','Esquivias','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45000965','SAN JOSÉ','Centro Privado de Educación Infantil Primaria y Secundaria','Fuensalida','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45005665','ALDEBARÁN','Instituto de Educación Secundaria','Fuensalida','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005975','MONTES DE TOLEDO','Instituto de Educación Secundaria','Gálvez','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45001179','VIRGEN DE LA CARIDAD','Centro Privado de Educación Infantil Primaria y Secundaria','Illescas','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45005987','CONDESTABLE ÁLVARO DE LUNA','Instituto de Educación Secundaria','Illescas','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45004788','JUAN DE PADILLA','Instituto de Educación Secundaria','Illescas','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006116','ALDONZA LORENZO','Instituto de Educación Secundaria','La Puebla de Almoradiel','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45002317','FRANCISCANO DE LA INMACULADA','Centro Privado de Educación Infantil Primaria y Secundaria','La Puebla de Montalbán','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45004739','JUAN DE LUCENA','Instituto de Educación Secundaria','La Puebla de Montalbán','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45010508','LEONOR DE GUZMÁN','Instituto de Educación Secundaria Obligatoria','La Villa de Don Fadrique','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005495','LOS NAVALMORALES','Instituto de Educación Secundaria','Los Navalmorales','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005689','GUADALERZAS','Instituto de Educación Secundaria','Los Yébenes','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45001271','AMOR DE DIOS','Centro Privado de Educación Infantil Primaria y Secundaria','Madridejos','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45001283','CERVANTES','Centro Privado de Educación Infantil Primaria y Secundaria','Madridejos','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45001337','VALDEHIERRO','Instituto de Educación Secundaria','Madridejos','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45011860','ANTONIO JIMÉNEZ-LANDI','Instituto de Educación Secundaria','Méntrida','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006098','JUAN PATIÑO TORRES','Instituto de Educación Secundaria Obligatoria','Miguel Esteban','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45001611','MARÍA INMACULADA','Centro Privado de Educación Infantil Primaria y Secundaria','Mora','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45006220','PEÑAS NEGRAS','Instituto de Educación Secundaria','Mora','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006207','MANUEL DE GUZMÁN','Instituto de Educación Secundaria Obligatoria','Navahermosa','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45011872','PROFESOR EMILIO LLEDÓ','Instituto de Educación Secundaria','Numancia de la Sagra','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45002007','COLEGIO DIOCESANO SANTA CLARA','Centro Privado de Educación Infantil Primaria y Secundaria','Ocaña','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45004685','ALONSO DE ERCILLA','Instituto de Educación Secundaria','Ocaña','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45004791','MIGUEL HERNÁNDEZ','Instituto de Educación Secundaria','Ocaña','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45014563','AMALIA AVIA','Instituto de Educación Secundaria Obligatoria','Ocaña','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45014356','OLÍAS DEL REY','Instituto de Educación Secundaria','Olías del Rey','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45004727','ALONSO DE OROZCO','Instituto de Educación Secundaria','Oropesa','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45002433','NUESTRA SEÑORA DE LA CONSOLACIÓN','Centro Privado de Educación Infantil Primaria y Secundaria','Quintanar de la Orden','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45002445','NUESTRA SEÑORA DE LOS DOLORES','Centro Privado de Educación Infantil Primaria y Secundaria','Quintanar de la Orden','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45004867','ALONSO QUIJANO','Instituto de Educación Secundaria','Quintanar de la Orden','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45002470','INFANTE DON FADRIQUE','Instituto de Educación Secundaria','Quintanar de la Orden','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45012131','ARCIPRESTE DE CANALES','Instituto de Educación Secundaria','Recas','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006190','VELSINIA','Instituto de Educación Secundaria Obligatoria','Santa Cruz de la Zarza','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45014216','KAROL WOJTYLA','Centro Privado de Educación Infantil Primaria y Secundaria','Seseña','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45005677','MARGARITA SALAS','Instituto de Educación Secundaria','Seseña','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006244','LAS SALINAS','Instituto de Educación Secundaria','Seseña Nuevo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45014401','El Lago','Instituto de Educación Secundaria Obligatoria','Seseña Nuevo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005355','LA SISLA','Instituto de Educación Secundaria','Sonseca','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45003231','ADALID MENESES','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003036','CERVANTES','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45005082','CLEMENTE PALENCIA','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003073','COMPAÑÍA DE MARÍA','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003280','CRISTÓBAL COLÓN','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003127','EXA','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003103','FERNANDO DE ROJAS','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003085','JOAQUÍN ALONSO','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003221','JUAN RAMÓN JIMÉNEZ','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003051','LA SALLE - JOAQUINA SANTANDER','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45004995','LOPE DE VEGA','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003097','MARISTAS SANTA MARÍA DEL PRADO','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003206','RAFAEL MORALES','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45005331','RUIZ DE LUNA','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003012','SAGRADOS CORAZONES','Centro Privado de Educación Infantil Primaria y Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45004740','GABRIEL ALONSO DE HERRERA','Instituto de Educación Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45003267','JUAN ANTONIO CASTRO','Instituto de Educación Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45003255','PADRE JUAN DE MARIANA','Instituto de Educación Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005461','PUERTA DE CUARTOS','Instituto de Educación Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005471','RIBERA DEL TAJO','Instituto de Educación Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45003279','SAN ISIDRO','Instituto de Educación Secundaria','Talavera de la Reina','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45003531','COLEGIO MAYOL, SOCIEDAD COOPERATIVA DE CLM','Centro Privado de Educación Infantil Primaria y Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003528','DIVINA PASTORA','Centro Privado de Educación Infantil Primaria y Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45011926','INTERNATIONAL SCHOOL SAN PATRICIO TOLEDO','Centro Privado de Educación Infantil Primaria y Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003450','MARISTAS SANTA MARÍA','Centro Privado de Educación Infantil Primaria y Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003486','MEDALLA MILAGROSA','Centro Privado de Educación Infantil Primaria y Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003632','NUESTRA SEÑORA DE LOS INFANTES','Centro Privado de Educación Infantil Primaria y Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003462','SAN JUAN BAUTISTA','Centro Privado de Educación Infantil Primaria y Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003656','SANTIAGO EL MAYOR','Centro Privado de Educación Infantil Primaria y Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003498','VIRGEN DEL CARMEN','Centro Privado de Educación Infantil Primaria y Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45003735','SEMINARIO MENOR SANTO TOMÁS DE VILLANUEVA','Centro Privado de Educación Primaria y Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45004752','ALFONSO X EL SABIO','Instituto de Educación Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45003875','AZARQUIEL','Instituto de Educación Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005562','CARLOS III','Instituto de Educación Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45003863','EL GRECO','Instituto de Educación Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45004909','JUANELO TURRIANO','Instituto de Educación Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006301','MARÍA PACHECO','Instituto de Educación Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006311','PRINCESA GALIANA','Instituto de Educación Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005240','SEFARAD','Instituto de Educación Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45003796','UNIVERSIDAD LABORAL','Instituto de Educación Secundaria','Toledo','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005872','SANTÍSIMO CRISTO DE LA SANGRE','Centro Privado de Educación Infantil Primaria y Secundaria','Torrijos','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45004090','ALONSO DE COVARRUBIAS','Instituto de Educación Secundaria','Torrijos','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45005252','JUAN DE PADILLA','Instituto de Educación Secundaria','Torrijos','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45014393','Almudena Grandes','Instituto de Educación Secundaria','Ugena','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006141','CAÑADA REAL','Instituto de Educación Secundaria','Valmojado','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45004235','NUESTRA SEÑORA DE LA CONSOLACIÓN','Centro Privado de Educación Infantil Primaria y Secundaria','Villacañas','Toledo','Castilla-La Mancha','Centro privado','https://www.educacion.gob.es/centros/',true),
('45005321','ENRIQUE DE ARFE','Instituto de Educación Secundaria','Villacañas','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45004272','GARCILASO DE LA VEGA','Instituto de Educación Secundaria','Villacañas','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006153','LA FALCATA','Instituto de Educación Secundaria Obligatoria','Villafranca de los Caballeros','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006165','CASTILLO DEL ÁGUILA','Instituto de Educación Secundaria','Villaluenga de la Sagra','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45014368','La Galatea','Instituto de Educación Secundaria','Yeles','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006177','CARPETANIA','Instituto de Educación Secundaria','Yepes','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45006189','LA CAÑUELA','Instituto de Educación Secundaria','Yuncos','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true),
('45014253','El Melgar','Instituto de Educación Secundaria Obligatoria','Yuncos','Toledo','Castilla-La Mancha','Centro público','https://www.educacion.gob.es/centros/',true)
on conflict (official_code) do update set
  name = excluded.name,
  generic_name = excluded.generic_name,
  municipality = excluded.municipality,
  province = excluded.province,
  autonomous_region = excluded.autonomous_region,
  ownership = excluded.ownership,
  source_url = excluded.source_url,
  is_active = excluded.is_active;
