import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import crypto from'node:crypto';import{observations,cases,statements,proof,buildConeEigenspaceTetrahedronBatch}from'../scripts/resolve-andalucia-cone-eigenspace-tetrahedron.mjs';
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t*Math.max(1,Math.abs(b))),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],det=a=>dot(a[0],cross(a[1],a[2]));
test('0461 three official source/page/image hashes, with matrix header and next-exercise boundary repaired reversibly',()=>{const rows=p=>fs.readFileSync(p,'utf8').trim().split(/\r?\n/).map(JSON.parse),q=rows('artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'),map=new Map(rows('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl').map(x=>[x.exerciseId,x])),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');for(const o of observations){const e=map.get(q[o[0]].exerciseId);assert.equal(sha(e.provenance.localPath),o[1]);assert.equal(e.sourceRange.page,o[2]);assert.equal(sha(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`),o[4]);}assert.match(statements[1014],/matrix\{−2,−2,0;−2,1,0;0,0,−2\}/);assert.doesNotMatch(statements[1014],/3t/);});
test('1012 height-radius optimum independently verified by constraint, derivative, endpoints and feasible sweep',()=>{const p=proof({index:1012}),V=h=>Math.PI/3*(8100-h*h)*h;near(p.height*p.height+p.radius*p.radius,8100);near(V(p.height),p.volume);near(Math.PI*(2700-p.height*p.height),0);assert.equal(V(0),0);assert.equal(V(90),0);for(let h=0;h<=90;h+=.1)assert.ok(V(h)<=p.volume+1e-7);const pairs=[[p.height,p.radius],[p.radius,p.height],[45*Math.sqrt(2),45*Math.sqrt(2)],[45*Math.sqrt(3),45]];assert.deepEqual(pairs.map(([h,r])=>Math.abs(Math.PI*r*r*h/3-p.volume)<1e-6),[true,false,false,false]);for(const[h,r]of pairs)near(h*h+r*r,8100);});
test('1014 determinant roots use plus-lambda not eigenvalue signs',()=>{const A=proof({index:1014}).A;for(const l of[-5,-3,-2,0,1,2,3,4,6]){const a=A.map((r,i)=>r.map((x,j)=>x+(i===j?l:0)));near(det(a),(l-2)*(l-3)*(l+2));}const valid=roots=>roots.length===3&&[-2,2,3].every(x=>roots.includes(x));assert.deepEqual([[-2,2,3],[-3,-2,2],[-2,2],[2,3]].map(valid),[true,false,false,false]);});
test('1014 complete homogeneous eigenspace and x=1 solution independently substitute into A',()=>{const A=proof({index:1014}).A,families=[s=>[2*s,s,0],s=>[s,2*s,0],s=>[2*s,s,s]],valid=f=>[-3,-.5,0,1,5].every(s=>A.every((r,i)=>dot(r,f(s))===-3*f(s)[i]));assert.deepEqual(families.map(valid),[true,false,false]);const v=proof({index:1014}).atXOne;assert.equal(v[0],1);assert.deepEqual(A.map(r=>dot(r,v)),v.map(x=>-3*x||0));assert.ok(valid(families[0]));});
test('1015 tetrahedron determinant independently gives two volume roots; distractor root sets fail completeness',()=>{const value=t=>Math.abs(det([[-t,-1,2],[-1-t,-2,3],[2-t,1,-t]]))/6;for(const t of[-7,-5,-2,0,1,3,6,8])near(value(t),Math.abs(t*t-t)/6);assert.equal(value(-5),5);assert.equal(value(6),5);assert.deepEqual([[-5,6],[-6,5],[-2,3],[6]].map(a=>a.length===2&&a.every(t=>value(t)===5)),[true,false,false,false]);assert.ok(1-4*30<0);});
test('1015 distance foot verified with two independent formulas; four numeric options are distinct',()=>{const p=proof({index:1015}),v=p.point.map((x,i)=>x-p.foot[i]),w=p.point.map((x,i)=>x-p.linePoint[i]),c=cross(w,p.direction);assert.equal(dot(v,p.direction),0);assert.equal(dot(v,v),2);assert.deepEqual(p.foot,p.linePoint.map((x,i)=>x-p.direction[i]));near(dot(c,c)/dot(p.direction,p.direction),2);assert.deepEqual([Math.sqrt(2),Math.sqrt(5),Math.sqrt(6),2].map(x=>Math.abs(x*x-2)<1e-8),[true,false,false,false]);});
test('0461 three exercises five pedagogical parts remain unpublished, with deterministic inverse-order rebuild',()=>{const a=buildConeEigenspaceTetrahedronBatch('test').batch,b=buildConeEigenspaceTetrahedronBatch('test',[...cases].reverse()).batch;assert.equal(a.records.length,3);assert.equal(a.records.flatMap(r=>r.parts).length,5);assert.deepEqual(a.records,[...b.records].reverse());for(const r of a.records){assert.equal(r.qualityGates.publication,'NOT_ENABLED');assert.equal(r.qualityGates.rendering,'RECHECK_REQUIRED');for(const p of r.parts){assert.equal(p.solutionSteps.length,6);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.finalAnswer,p.answer);}}});
