import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,optimalFaceGraph,renderOptimalFaceGraph,buildProductionFacesBatch} from '../scripts/resolve-andalucia-linear-production-optimal-faces.mjs';
import {productionFacesObservations,productionFacesReplacements,restoredProductionPrompts} from '../scripts/andalucia-linear-production-optimal-faces-pdf-evidence.mjs';
import {derive} from '../scripts/resolve-andalucia-linear-quadrilaterals-official.mjs';import {feasible} from '../scripts/resolve-andalucia-linear-region-official.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),rows=()=>buildProductionFacesBatch('production-faces-test').batch.records;
for(const c of cases)test(`${c.index}: resource model verified by nonnegative dual certificate and independent feasible enumeration`,()=>{
 const sign=c.minimize?-1:1;for(let j=0;j<2;j++)near(c.constraints.reduce((s,r,i)=>s+c.dual[i]*r[j],0),sign*c.objective[j]);near(c.constraints.reduce((s,r,i)=>s+c.dual[i]*r[2],0),sign*c.extreme);assert.ok(c.dual.every(x=>x>=0));
 assert.ok(feasible(c.optimum,c.constraints));near(c.objective[0]*c.optimum[0]+c.objective[1]*c.optimum[1],c.extreme);const d=derive(c);near(c.minimize?d.min:d.max,c.extreme);
 let best=c.minimize?Infinity:-Infinity,count=0;for(let x=0;x<=c.domain.x[1];x++)for(let y=0;y<=c.domain.y[1];y++){if(!feasible([x,y],c.constraints))continue;const z=c.objective[0]*x+c.objective[1]*y;assert.ok(sign*z<=sign*c.extreme+1e-6);if(sign*z>sign*best+1e-6){best=z;count=1;}else if(Math.abs(z-best)<1e-6)count++;}near(best,c.extreme);assert.equal(count,c.integerFaceCount??1);
});
test('optimal faces retain ALL feasible integer optima and do not treat another optimum as a wrong numerical point',()=>{
 for(const c of cases.filter(c=>c.face)){const g=optimalFaceGraph(c);assert.equal(g.maximumFace.allPointsOptimal,true);assert.equal(g.maximumFace.integerPointCount,c.integerFaceCount);for(let i=0;i<=100;i++){const t=i/100,p=c.face[0].map((x,j)=>(1-t)*x+t*c.face[1][j]);assert.ok(feasible(p,c.constraints));near(c.objective[0]*p[0]+c.objective[1]*p[1],c.extreme);}const s=renderOptimalFaceGraph(g);assert.match(s,new RegExp(`Máximo en ${c.integerFaceCount} puntos enteros`));assert.doesNotMatch(s,/NaN|undefined/);assert.equal(s,renderOptimalFaceGraph(structuredClone(g)));}
 near(50*(26+40/60),4000/3);const r=rows();for(const i of[797,1255]){const p=r.find(x=>x.correctionEvidence.parameters.index===i).parts[0];assert.ok(p.distractors.slice(0,2).every(x=>x.startsWith('Únicamente')));assert.ok(!p.answer.startsWith('Únicamente'));}
});
test('27 distractors checked: nonoptimal or infeasible, with separate proof of false uniqueness statements',()=>{
 let n=0;for(const r of rows())for(const p of r.parts){assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.distractors.length,3);assert.equal(p.distractorEvidence.length,3);n+=3;const c=r.correctionEvidence.parameters;for(const xy of p.verification.numericalEvidence.wrongPoints??[]){const z=c.objective[0]*xy[0]+c.objective[1]*xy[1];assert.ok(!feasible(xy,c.constraints)||Math.abs(z-c.extreme)>1e-6);}}
 assert.equal(n,27);const c=cases.find(c=>c.index===1255);assert.ok(feasible([0,700],c.constraints));assert.ok(!feasible([350,0],c.constraints));assert.ok(!feasible([260,0],c.constraints));assert.ok(feasible([1,698],c.constraints));
});
test('8 official exercises, 9 deliveries; all a/b questions retained and whole-exercise scope explicit',()=>{
 const rs=rows();assert.equal(rs.length,8);assert.equal(rs.reduce((s,r)=>s+r.parts.length,0),9);for(const r of rs){const c=r.correctionEvidence.parameters;if(c.index===1255){assert.equal(r.sourceSubparts.length,2);assert.deepEqual(r.parts.map(p=>p.partId),['a','b']);assert.match(r.parts[1].answer,/700 de P₂/);}else{assert.equal(r.sourceSubparts.length,0);assert.equal(r.deliveryScope,'WHOLE_OFFICIAL_EXERCISE');}assert.ok(r.parts[0].visual);assert.ok(r.parts[0].solutionSteps.length>=10);for(const p of r.parts)assert.equal(p.answer,p.finalAnswer);}
});
test('8 PDF hashes and page hashes; numeric glyph restoration is reversible and does not invent missing parameters',()=>{
 let n=0;for(const r of rows()){const i=r.correctionEvidence.parameters.index,o=productionFacesObservations.find(x=>x[0]===i);assert.equal(sha(fs.readFileSync(r.officialSource.path)),o[1]);assert.equal(sha(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${i}.png`)),o[4]);let t=r.sourceLiteral;const undo=[];for(const[b,a]of productionFacesReplacements({...r,queueIndex:i})){const pos=t.indexOf(b);assert.ok(pos>=0,`${i}: ${b}`);t=t.slice(0,pos)+a+t.slice(pos+b.length);undo.push({pos,b,a});n++;}assert.doesNotMatch(t,/\u001c|BLOQUE B|𝑚3|𝑘𝑔/);assert.deepEqual(t.match(/\([^()]*puntos?\)/g),r.sourceLiteral.match(/\([^()]*puntos?\)/g));if(restoredProductionPrompts[i])assert.equal(t,restoredProductionPrompts[i]);for(const{pos,b,a}of undo.reverse())t=t.slice(0,pos)+b+t.slice(pos+a.length);assert.equal(t,r.sourceLiteral);}assert.equal(n,21);
 const t=restoredProductionPrompts;for(const s of['1000 kg','800 kg','300 kg','10 kg','30 €','20 €'])assert.ok(t[580].includes(s));for(const s of['100 minutos','50 minutos','26 horas y 40 minutos','12 lavadoras','16 frigoríficos','50 €'])assert.ok(t[797].includes(s));for(const s of['3500','1300','4200','10 horas','20 horas','800 euros','400 euros'])assert.ok(t[1255].includes(s));
});
test('batch is reproducible and order invariant; official sources, queue and current runtime unchanged',()=>{
 const paths=['data/andalucia-pau-runtime.js','math-renderer.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=paths.map(p=>sha(fs.readFileSync(p))),sort=r=>r.sort((a,b)=>a.exerciseId.localeCompare(b.exerciseId));assert.deepEqual(rows(),rows());assert.deepEqual(sort(rows()),sort(buildProductionFacesBatch('production-faces-test',[...cases].reverse()).batch.records));assert.deepEqual(paths.map(p=>sha(fs.readFileSync(p))),before);
});
