import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import crypto from'node:crypto';import{observations,statements,cases,proof,buildRankProductDiagonalBatch}from'../scripts/resolve-andalucia-rank-product-diagonal.mjs';
const near=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`),mul=(a,b)=>a.map(r=>b[0].map((_,j)=>r.reduce((s,x,k)=>s+x*b[k][j],0))),scale=(a,k)=>a.map(r=>r.map(x=>x*k)),sub=(a,b)=>a.map((r,i)=>r.map((x,j)=>x-b[i][j])),transpose=a=>a[0].map((_,i)=>a.map(r=>r[i])),eq=(a,b)=>a.every((r,i)=>r.every((x,j)=>Math.abs(x-b[i][j])<1e-8)),det=a=>a[0][0]*(a[1][1]*a[2][2]-a[1][2]*a[2][1])-a[0][1]*(a[1][0]*a[2][2]-a[1][2]*a[2][0])+a[0][2]*(a[1][0]*a[2][1]-a[1][1]*a[2][0]);
function rank(input){const a=input.map(r=>r.slice());let r=0;for(let j=0;j<a[0].length&&r<a.length;j++){let k=r;while(k<a.length&&Math.abs(a[k][j])<1e-8)k++;if(k===a.length)continue;[a[k],a[r]]=[a[r],a[k]];const d=a[r][j];a[r]=a[r].map(x=>x/d);for(let i=0;i<a.length;i++)if(i!==r){const t=a[i][j];a[i]=a[i].map((x,c)=>x-t*a[r][c]);}r++;}return r;}
const matrix=m=>[[2,3,m],[1,m,-1],[3,1,-3]],rhs=m=>[3,-1,-m];
test('0464 source and render hashes verified; fraction 3/7 and all matrix entries bound to official pages',()=>{const rows=p=>fs.readFileSync(p,'utf8').trim().split(/\r?\n/).map(JSON.parse),q=rows('artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'),map=new Map(rows('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl').map(x=>[x.exerciseId,x])),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');for(const o of observations){const e=map.get(q[o[0]].exerciseId);assert.equal(sha(e.provenance.localPath),o[1]);assert.equal(e.sourceRange.page,o[2]);assert.equal(sha(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`),o[4]);}assert.match(statements[1027],/λ−frac\{3\}\{7\}/);assert.doesNotMatch(statements[1032],/x=2\+λ/);});
test('1027 determinant polynomial independently computed and singular ranks checked by Gaussian elimination',()=>{for(const m of[-3,-2,0,1/3,1,2,5])near(det(matrix(m)),-(3*m-1)*(m+2));for(const[m,expected]of[[-2,[2,2]],[1/3,[2,3]],[0,[3,3]],[4,[3,3]]]){const a=matrix(m),b=rhs(m);assert.deepEqual([rank(a),rank(a.map((r,i)=>[...r,b[i]]))],expected);}assert.deepEqual(proof({index:1027}).singular,[-2,1/3]);});
test('1027 whole solution family satisfies all equations and wrong y values fail',()=>{for(const t of[-7,0,.25,1,19]){const result=mul(matrix(-2),[[t],[5/7],[t-3/7]]);result.forEach((r,i)=>near(r[0],rhs(-2)[i]));}assert.deepEqual([5/7,-5/7,3/7,5/3].map(y=>eq(mul(matrix(-2),[[0],[y],[-3/7]]),rhs(-2).map(x=>[x]))),[true,false,false,false]);});
test('1032 AB, subtraction, inverse and residual verified in original noncommutative order',()=>{const p=proof({index:1032});assert.deepEqual(mul(p.A,p.B),p.AB);assert.deepEqual(sub(p.AB,p.C),p.M);assert.equal(det(p.M),-1);assert.ok(eq(mul(p.M,p.inverseM),[[1,0,0],[0,1,0],[0,0,1]]));assert.deepEqual(mul(p.inverseM,scale(p.C,2)),p.X);assert.deepEqual(sub(mul(p.AB,p.X),scale(p.C,2)),mul(p.C,p.X));});
test('1032 distractor half-factor, transpose and sign are distinct and fail original equation',()=>{const p=proof({index:1032}),xs=[p.X,scale(p.X,.5),transpose(p.X),scale(p.X,-1)];assert.equal(new Set(xs.map(JSON.stringify)).size,4);assert.deepEqual(xs.map(X=>eq(sub(mul(p.AB,X),scale(p.C,2)),mul(p.C,X))),[true,false,false,false]);});
test('1033 derivative and independent upper bound confirm unique square; three plausible rectangles rejected',()=>{const p=proof({index:1033}),f=x=>x*Math.sqrt(100-x*x),der=x=>(100-2*x*x)/Math.sqrt(100-x*x);near(p.side*p.side,50);near(f(p.side),50);near(der(p.side),0);for(let j=1;j<100;j++){const x=j/10,y=Math.sqrt(100-x*x);assert.ok(x*y<=50+1e-9);near((f(x+1e-5)-f(x-1e-5))/2e-5,der(x),1e-4);}assert.deepEqual([[p.side,p.side],[6,8],[5,5],[5,5*Math.sqrt(3)]].map(([x,y])=>Math.abs(x*x+y*y-100)<1e-8&&Math.abs(x*y-50)<1e-8),[true,false,false,false]);});
test('0464 three records four complete parts, source preservation, order invariance and withheld delivery',()=>{const a=buildRankProductDiagonalBatch('test').batch,b=buildRankProductDiagonalBatch('test',[...cases].reverse()).batch;assert.equal(a.records.length,3);assert.equal(a.records.flatMap(r=>r.parts).length,4);assert.deepEqual(a.records,[...b.records].reverse());for(const r of a.records){assert.equal(r.qualityGates.publication,'NOT_ENABLED');assert.equal(r.qualityGates.rendering,'RECHECK_REQUIRED');for(const p of r.parts){assert.equal(p.solutionSteps.length,6);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.answer,p.finalAnswer);}}});
