import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {observations,cases,solve,proof,graphs,graphModel,renderLogParabolaAreas,buildLogParabolaAreasBatch} from '../scripts/resolve-andalucia-mates-log-parabola-areas.mjs';
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),d=(f,x)=>(f(x+1e-5)-f(x-1e-5))/2e-5;
function integral(f,a,b,n=40000){let s=0;for(let i=0;i<n;i++)s+=f(a+(i+.5)*(b-a)/n);return s*(b-a)/n;}
test('log-parabola official inspections retain exact page hashes',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);});
test('absolute-line and parabola intersections and all four paired options checked independently',()=>{const f=x=>4-3*Math.abs(x),g=x=>x*x,valid=ps=>ps.every(([x,y])=>f(x)===y&&g(x)===y);assert.deepEqual([[[-1,1],[1,1]],[[-4,16],[4,16]],[[-1,-1],[1,-1]],[[-4/3,0],[4/3,0]]].map(valid),[true,false,false,false]);for(const x of[-.9,-.5,0,.5,.9])assert.ok(f(x)>g(x));const a=integral(x=>f(x)-g(x),-1,1);near(a,13/3);assert.deepEqual([13/3,13/6,14/3,-13/3].map(v=>Math.abs(v-a)<1e-6),[true,false,false,false]);});
test('log area: each pairwise boundary intersection, vertical/horizontal quadrature and unique option',()=>{const f=x=>Math.log1p(x),valid=ps=>Math.abs(ps[0][0])<1e-9&&Math.abs(ps[0][1]-f(0))<1e-9&&ps[1][0]===0&&ps[1][1]===1&&Math.abs(f(ps[2][0])-1)<1e-9&&ps[2][1]===1;assert.deepEqual([[[0,0],[0,1],[Math.E-1,1]],[[0,0],[0,1],[Math.E,1]],[[0,0],[0,1],[Math.E-1,0]],[[0,1],[0,2],[Math.E-1,1]]].map(valid),[true,false,false,false]);const a=integral(x=>1-f(x),0,Math.E-1),b=integral(y=>Math.exp(y)-1,0,1);near(a,b);near(a,Math.E-2);assert.deepEqual([Math.E-2,Math.E-1,2-Math.E,1].map(v=>Math.abs(v-a)<1e-6),[true,false,false,false]);const H=x=>x-(x+1)*Math.log1p(x)+(x+1);for(const x of[0,.3,.7,1,Math.E-1])near(d(H,x),1-f(x));});
test('parametric parabola: general region, scaled graph and four distinct area-parameter options',()=>{for(const a of[.04,.5,1,2,4,9]){const lo=1-Math.sqrt(a),hi=1+Math.sqrt(a);near((lo-1)**2,a);near((hi-1)**2,a);near(integral(x=>a-(x-1)**2,lo,hi),4/3*a*Math.sqrt(a));for(const u of[-1,-.5,0,.5,1]){const x=1+Math.sqrt(a)*u;near((x-1)**2/a,u*u);}}const area=a=>integral(x=>a-(x-1)**2,1-Math.sqrt(a),1+Math.sqrt(a));assert.deepEqual([1,2**(2/3),(.5)**(2/3),(4/3)**(2/3)].map(a=>Math.abs(area(a)-4/3)<1e-6),[true,false,false,false]);const a=4,valid=([lo,hi,reverse])=>Math.abs((lo-1)**2-a)<1e-9&&Math.abs((hi-1)**2-a)<1e-9&&!reverse;assert.deepEqual([[1-Math.sqrt(a),1+Math.sqrt(a),false],[1-a,1+a,false],[-1-Math.sqrt(a),-1+Math.sqrt(a),false],[1-Math.sqrt(a),1+Math.sqrt(a),true]].map(valid),[true,false,false,false]);});
test('parabola tangent: independent numerical derivative rejects all three alternate lines',()=>{const f=x=>(9-x*x)/4,valid=([m,b])=>Math.abs(m+b-f(1))<1e-9&&Math.abs(m-d(f,1))<1e-7;assert.deepEqual([[-.5,2.5],[.5,1.5],[-2,4],[-.5,2]].map(valid),[true,false,false,false]);for(const x of[-2,0,1,2,3,5])near((5-x)/2-f(x),(x-1)**2/4);});
test('three-boundary region changes bottom at x=3; quadrature, triangle and distractors checked',()=>{const f=x=>(9-x*x)/4,r=x=>(5-x)/2;near(f(1),2);near(r(1),2);near(f(3),0);near(r(5),0);const a=integral(x=>r(x)-f(x),1,3),b=integral(r,3,5);near(a,2/3);near(b,1);near(b,(5-3)*r(3)/2);assert.deepEqual([5/3,2/3,1,10/3].map(v=>Math.abs(v-a-b)<1e-6),[true,false,false,false]);near(proof({index:368}).area,a+b);});
test('four derived graphs: every shaded boundary follows actual functions, normalized coordinates disclosed',()=>{for(const g of Object.values(graphs)){const m=graphModel(g.index),s=renderLogParabolaAreas(g);assert.equal(s,renderLogParabolaAreas(structuredClone(g)));assert.match(s,/<polygon/);assert.match(s,/<polyline/);assert.doesNotMatch(s,/NaN|undefined/);for(const r of m.regions)for(let i=0;i<=100;i++){const x=r.a+(r.b-r.a)*i/100;assert.ok(r.upper(x)>=r.lower(x)-1e-10);}const area=m.regions.reduce((sum,r)=>sum+integral(x=>r.upper(x)-r.lower(x),r.a,r.b),0);near(area,g.index===367?4/3:proof({index:g.index}).area);}assert.match(renderLogParabolaAreas(graphs[367]),/normalizadas/);assert.throws(()=>renderLogParabolaAreas({...graphs[344],index:333}));});
test('eight pedagogical parts, all options distinct, deterministic build and reverse order, not enabled',()=>{const ps=cases.flatMap(solve);assert.equal(ps.length,8);for(const p of ps){assert.equal(p.solutionSteps.length,6);assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);}const a=buildLogParabolaAreasBatch('test').batch,b=buildLogParabolaAreasBatch('test',[...cases].reverse()).batch;assert.deepEqual(a.records,[...b.records].reverse());a.records.forEach(x=>{assert.equal(x.qualityGates.publication,'NOT_ENABLED');assert.ok(x.parts.every(p=>p.visual?.plotVersion==='mates-log-parabola-areas-v1'));});});
