import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import crypto from'node:crypto';import{observations,cases,proof,line1036,buildDistanceTrisectionInflectionBatch}from'../scripts/resolve-andalucia-distance-trisection-inflection.mjs';
const near=(a,b,t=1e-7)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,j)=>s+x*b[j],0),sub=(a,b)=>a.map((x,j)=>x-b[j]),norm=a=>dot(a,a),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
test('0467 PDF hashes and source image glyph hashes verified',()=>{const rows=p=>fs.readFileSync(p,'utf8').trim().split(/\r?\n/).map(JSON.parse),q=rows('artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'),m=new Map(rows('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl').map(x=>[x.exerciseId,x])),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');for(const o of observations){const e=m.get(q[o[0]].exerciseId);assert.equal(sha(e.provenance.localPath),o[1]);assert.equal(e.sourceRange.page,o[2]);assert.equal(sha(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`),o[4]);}});
test('1036 equal distances and line membership, exactly one of four points',()=>{const P=[4,-2,2],valid=q=>norm(sub(q,line1036(q[2])))<1e-9&&Math.abs(norm(q)-norm(sub(q,P)))<1e-9;assert.deepEqual([[7,11,3],[4,7,2],[1,3,1],[-11,-13,-3]].map(valid),[true,false,false,false]);assert.equal(norm([7,11,3]),179);assert.equal(norm(sub([7,11,3],P)),179);});
test('1036 nearest point verified by orthogonality and global quadratic distance',()=>{const p=proof({index:1036}),v=[3,4,1];near(norm(p.nearest),15/13);near(dot(p.nearest,v),0);for(let j=-100;j<=100;j++){const t=j/13;near(norm(line1036(t)),26*(t-5/13)**2+15/13);}const valid=q=>norm(sub(q,line1036(q[2])))<1e-9&&Math.abs(dot(q,v))<1e-9;assert.deepEqual([p.nearest,[-41/13,-33/13,-5/13],[-5/4,0,.25],[1,3,1]].map(valid),[true,false,false,false]);});
test('1038 trisection independently checks three equal ordered segments and rejects distractors',()=>{const A=[1,2,3],B=[-1,0,4],expected=[-2/3,-2/3,1/3],pairs=[[[1/3,4/3,10/3],[-1/3,2/3,11/3]],[[-2/3,-2/3,1/3],[-4/3,-4/3,2/3]],[[5/3,8/3,8/3],[7/3,10/3,7/3]],[[.5,1.5,13/4],[-.5,.5,15/4]]];assert.deepEqual(pairs.map(([C,D])=>[sub(C,A),sub(D,C),sub(B,D)].every(v=>norm(sub(v,expected))<1e-9)),[true,false,false,false]);near(norm(expected),1);});
test('1038 plane passes A and has normal parallel to AB; wrong options fail',()=>{const A=[1,2,3],v=[-2,-2,1],opts=[[2,2,-1,-3],[2,2,-1,3],[1,2,3,-14],[2,-2,-1,5]];assert.deepEqual(opts.map(p=>Math.abs(dot(p.slice(0,3),A)+p[3])<1e-9&&norm(cross(p.slice(0,3),v))<1e-9),[true,false,false,false]);});
test('1043 point, slope and actual concavity change all necessary',()=>{const opts=[[3,-9,6],[-3,9,-6],[3,-3,0],[1,-3,2]];assert.deepEqual(opts.map(([a,b,c])=>a+b+c===0&&3*a+2*b+c===-3&&6*a+2*b===0&&a!==0),[true,false,false,false]);const f=x=>3*x**3-9*x*x+6*x,h=1e-5;near((f(1+h)-f(1-h))/(2*h),-3);assert.ok(18*(.9-1)<0&&18*(1.1-1)>0);});
test('0467 order invariant three exercises five six-step parts; original source retained and no enabling',()=>{const a=buildDistanceTrisectionInflectionBatch('test').batch,b=buildDistanceTrisectionInflectionBatch('test',[...cases].reverse()).batch;assert.equal(a.records.length,3);assert.equal(a.records.flatMap(r=>r.parts).length,5);assert.deepEqual(a.records,[...b.records].reverse());for(const r of a.records){assert.equal(r.qualityGates.publication,'NOT_ENABLED');assert.equal(r.qualityGates.rendering,'RECHECK_REQUIRED');for(const p of r.parts){assert.equal(p.solutionSteps.length,6);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.answer,p.finalAnswer);}}});
