import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {cases,buildFinalSourceBatch} from '../scripts/resolve-andalucia-probability-final-source-models.mjs';
const rows=buildFinalSourceBatch().batch.records,at=i=>rows.find(r=>r.correctionEvidence.parameters.index===i),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-12,`${a} != ${b}`);
const values=i=>at(i).parts.map(p=>{const e=p.verification.numericalEvidence;return e.numerator/e.denominator;});
function compare(i,refs){const got=values(i);assert.equal(got.length,refs.length);got.forEach((v,j)=>near(v,refs[j]));}
test('eight official tasks contain all twenty subparts and sixty distinct false options',()=>{assert.equal(rows.length,8);assert.equal(rows.flatMap(r=>r.parts).length,20);for(const r of rows)for(const p of r.parts){assert.equal(p.answer,p.finalAnswer);assert.equal(p.distractors.length,3);assert.ok(p.solutionSteps.length>=7);assert.doesNotMatch(p.prompt,/BLOQUE D|\(\d+(?:[.,]\d+)? puntos?\)/);const v=p.verification.numericalEvidence,all=[[v.numerator,v.denominator],...v.wrong];for(let i=0;i<4;i++){assert.ok(all[i][0]>=0&&all[i][0]<=all[i][1]);for(let j=i+1;j<4;j++)assert.notEqual(all[i][0]*all[j][1],all[j][0]*all[i][1]);}}});
test('bank loans: complement of inclusion-exclusion and restricted universe',()=>{compare(1562,[1-(.6+.5-.2),(.6-.2)/(1-.5)]);assert.deepEqual(values(1562),[.1,.8]);});
test('transport: exactly one is not union and inverse conditional is not requested',()=>{const union=1-.03,joint=.9+.4-union,onlyT=.4-joint;compare(1568,[union,onlyT,onlyT/(1-.9)]);assert.deepEqual(values(1568),[.97,.07,.7]);});
test('three coins independently enumerated with conditional outcomes on a six-point grid',()=>{const outcomes=[];for(const coin of['dollar','pound','euro'])for(let u=0;u<6;u++)outcomes.push({coin,head:coin==='dollar'?u<4:coin==='pound'?true:u<3});const heads=outcomes.filter(x=>x.head),tails=outcomes.filter(x=>!x.head);compare(1572,[heads.length/outcomes.length,tails.filter(x=>x.coin==='dollar').length/tails.length]);assert.deepEqual(values(1572),[13/18,2/5]);});
test('telework: missing conditional independently recovered from failure equation',()=>{const failureT=(.1251-.72*(1-.87)-.17*(1-.86))/.11;const improveT=1-failureT,nonSelfImprove=.72*.87+.11*improveT;compare(1579,[improveT,nonSelfImprove/(1-.1251)]);near(improveT,.93);near(nonSelfImprove,.7287);});
test('olive/sunflower inverse conditionals and neither use separate universes',()=>{compare(1581,[.2/.55,(.3-.2)/.3,1-.55-.3+.2]);assert.deepEqual(values(1581),[4/11,1/3,7/20]);});
test('juice: peach one-litre rate is complemented before total probability',()=>{const two=.6*.8+.3*.7+.1*.4,one=.6*.2+.3*.3+.1*.6;compare(1586,[two,.6*.8/two,.1*.6/one]);near(two+one,1);assert.deepEqual(values(1586),[.73,48/73,2/9]);});
test('replacement game independently enumerates all 144 labelled-ball pairs',()=>{const balls=[...Array(5).fill('B'),...Array(3).fill('R'),...Array(4).fill('N')],count={ana:0,manolo:0,tie:0};for(const a of balls)for(const b of balls){if(a===b)count.ana++;else if(Number(a==='B')+Number(b==='B')===1)count.manolo++;else count.tie++;}assert.deepEqual(count,{ana:50,manolo:70,tie:24});compare(1623,Object.values(count).map(n=>n/144));});
test('student selection independently enumerates the 700 official students',()=>{const students=Array.from({length:700},(_,i)=>({female:i>=210,pass:i<126||(i>=210&&i<553)})),passed=students.filter(x=>x.pass);compare(1632,[passed.length/700,passed.filter(x=>x.female).length/passed.length]);assert.deepEqual(values(1632),[.67,49/67]);});
test('source phrases, identities and official binary hashes remain immutable',()=>{for(const c of cases){const r=at(c.index);for(const text of c.literals)assert.ok(r.sourceLiteral.includes(text));assert.equal(crypto.createHash('sha256').update(fs.readFileSync(r.officialSource.path)).digest('hex'),r.officialSource.documentHash);assert.equal(r.subject,'Matemáticas Aplicadas a las CCSS II');assert.equal(r.publicationState,'PARALLEL_VALIDATED_NOT_PUBLISHED');}});
test('repeat and reverse preserve exact mathematical payload and official provenance',()=>{const sig=rs=>rs.map(r=>[r.exerciseId,r.sourceLiteral,r.officialSource,r.parts]).sort((a,b)=>a[0].localeCompare(b[0]));assert.deepEqual(sig(rows),sig(buildFinalSourceBatch().batch.records));assert.deepEqual(sig(rows),sig(buildFinalSourceBatch('batch-0277',[...cases].reverse()).batch.records));});
