import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {observations,cases,proof,buildRankSkewLinesBatch} from '../scripts/resolve-andalucia-mates-rank-skew-lines.mjs';
const near=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],det=A=>dot(A[0],cross(A[1],A[2]));
function rank(input){const a=input.map(r=>[...r]);let i=0;for(let j=0;j<a[0].length&&i<a.length;j++){let k=i;while(k<a.length&&Math.abs(a[k][j])<1e-9)k++;if(k===a.length)continue;[a[i],a[k]]=[a[k],a[i]];const pivot=a[i][j];a[i]=a[i].map(x=>x/pivot);for(k=0;k<a.length;k++)if(k!==i){const f=a[k][j];a[k]=a[k].map((x,q)=>x-f*a[i][q]);}i++;}return i;}
const system=(i,m)=>i===573?{A:[[1,m+1,2],[m,1,1],[1-m,2,1]],b:[-1,m,-m-1]}:{A:[[1,-m,-2],[1,1,1],[1,2,m]],b:[m,2*m,3*m]},sat=(i,m,v)=>{const{A,b}=system(i,m);return A.every((r,j)=>Math.abs(dot(r,v)-b[j])<1e-9);};
test('four rank/skew official page images retain their independently recorded hashes',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);});
test('573 classification verified by independent numerical ranks and determinant polynomial',()=>{for(const m of[-3,-1,0,.5,1,2,4]){const{A,b}=system(573,m);near(det(A),-(2*m-1)*(m-2));assert.deepEqual([rank(A),rank(A.map((r,j)=>[...r,b[j]]))],m===.5?[2,3]:m===2?[2,2]:[3,3]);}const{A,b}=system(573,.5);near(det(A.map((r,j)=>[r[0],r[1],b[j]])),proof({index:573}).augmentedMinorAtHalf);});
test('573 free solution and z=2 condition reject each plausible distractor',()=>{const f=t=>[(7-t)/5,(-4-3*t)/5,t];for(const t of[-3,0,2,8])assert.ok(sat(573,2,f(t)));assert.deepEqual(f(2),proof({index:573}).solutionAtTwo);assert.deepEqual([f,t=>[(7+t)/5,(-4-3*t)/5,t],t=>[(7-t)/5,(-4+3*t)/5,t]].map(g=>[-3,0,2,8].every(t=>sat(573,2,g(t)))),[true,false,false]);assert.ok(sat(573,2,[1,-2,2]));});
test('574 singular ranks and unique m=1 answer independently reject wrong signs',()=>{for(const m of[-3,-2,0,1,2,4]){const{A,b}=system(574,m);near(det(A),m*m-4);assert.deepEqual([rank(A),rank(A.map((r,j)=>[...r,b[j]]))],Math.abs(m)===2?[2,3]:[3,3]);}assert.deepEqual([[4/3,1,-1/3],[4/3,1,1/3],[2/3,1,1/3],[4/3,-1,-1/3]].map(v=>sat(574,1,v)),[true,false,false,false]);});
test('582 crossing and double cross product plane verified from the original line equations',()=>{const p=proof({index:582});assert.deepEqual(cross(p.d,p.e),p.cross);near(dot(p.Q.map((v,i)=>v-p.P[i]),p.cross),p.triple);assert.notEqual(p.triple,0);assert.deepEqual(cross(p.d,p.cross),p.plane.slice(0,3));const planes=[p.plane,[30,-23,51,118],[-5,9,7,-1],[30,23,51,-26]];assert.deepEqual(planes.map(a=>Math.abs(dot(a.slice(0,3),p.P)+a[3])<1e-9&&dot(a.slice(0,3),p.d)===0&&dot(a.slice(0,3),p.cross)===0),[true,false,false,false]);near(dot(p.cross,p.d),0);near(dot(p.cross,p.e),0);});
test('584 crossing distance verified using independent closest-point equations',()=>{const p=proof({index:584}),q=p.Q.map((v,i)=>v-p.P[i]);assert.deepEqual(cross(p.d,p.e),p.cross);near(dot(q,p.cross),9);near(Math.abs(dot(q,p.cross))/Math.hypot(...p.cross),p.distance);const dd=dot(p.d,p.d),ee=dot(p.e,p.e),de=dot(p.d,p.e),qd=dot(q,p.d),qe=dot(q,p.e),den=dd*ee-de*de,t=(de*qd-dd*qe)/den,u=(qd+de*t)/dd;const H=p.P.map((v,i)=>v+u*p.d[i]),K=p.Q.map((v,i)=>v+t*p.e[i]),gap=K.map((v,i)=>v-H[i]);near(dot(gap,p.d),0);near(dot(gap,p.e),0);near(Math.hypot(...gap),p.distance);assert.deepEqual([3*Math.sqrt(3)/5,9/5,3/25,Math.sqrt(11)].map(x=>Math.abs(x-p.distance)<1e-9),[true,false,false,false]);});
test('four exercises, eight parts, distinct choices and six steps reproduce in reversed order',()=>{const a=buildRankSkewLinesBatch('test').batch,b=buildRankSkewLinesBatch('test',[...cases].reverse()).batch;assert.deepEqual(a.records,[...b.records].reverse());assert.equal(a.records.length,4);assert.equal(a.records.flatMap(r=>r.parts).length,8);for(const r of a.records)for(const p of r.parts){assert.ok(p.partId);assert.equal(p.answer,p.finalAnswer);assert.equal(p.solutionSteps.length,6);assert.equal(new Set([p.answer,...p.distractors]).size,4);}});
