import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import crypto from'node:crypto';import{observations,cases,statements,proof,solve,buildNormalLimitsGaussianBatch}from'../scripts/resolve-andalucia-mates-normal-limits-gaussian.mjs';
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
test('0453 five inspected official pages preserve squared exponents, signs and totals',()=>{const rows=p=>fs.readFileSync(p,'utf8').trim().split(/\r?\n/).map(JSON.parse),q=rows('artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'),map=new Map(rows('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl').map(x=>[x.exerciseId,x])),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');for(const o of observations){const e=map.get(q[o[0]].exerciseId);assert.equal(sha(e.provenance.localPath),o[1]);assert.equal(e.sourceRange.page,o[2]);assert.equal(sha(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`),o[4]);}assert.match(statements[960],/\(x−frac\{1\}\{2\}\)e\^\{−x²\}/);assert.match(statements[963],/x²/);});
test('957 normal and perpendicular tangent independently satisfy both conditions',()=>{const f=x=>4-x*x,df=x=>-2*x;near(f(2),0);near(df(2)*.25,-1);near(f(-1),3);near(df(-1)*-.5,-1);const pts=[[-1,3],[1,3],[.25,63/16],[-1,5]];assert.deepEqual(pts.map(([x,y])=>Math.abs(y-f(x))<1e-8&&Math.abs(df(x)-2)<1e-8),[true,false,false,false]);});
test('959 L’Hôpital derivative ratio and original numerical two-sided checks',()=>{const q=x=>(Math.tan(x)-x)/(x-Math.sin(x)),s=x=>(1+Math.cos(x))/(Math.cos(x)**2);near(s(-1e-4),2,3e-8);near(s(1e-4),2,3e-8);near(q(-1e-3),2,2e-6);near(q(1e-3),2,2e-6);});
test('960 derivative signs, extrema, values and end limits',()=>{const f=x=>(x-.5)*Math.exp(-x*x),d=x=>(1+x-2*x*x)*Math.exp(-x*x);assert.deepEqual([-1,0,2].map(x=>Math.sign(d(x))),[-1,1,-1]);near(f(-.5),-Math.exp(-.25));near(f(1),1/(2*Math.E));assert.ok(f(-.5)<f(-10)&&f(1)>f(10));});
test('963 limit formula independently recovered by Taylor coefficients and only two parameters work',()=>{const L=a=>(a*a+4)/2;assert.deepEqual([-2*Math.sqrt(2),2*Math.sqrt(2)].map(a=>Math.abs(L(a)-6)<1e-10),[true,true]);assert.deepEqual([-2,2,Math.sqrt(6),-Math.sqrt(6)].map(a=>Math.abs(L(a)-6)<1e-10),[false,false,false,false]);});
test('964 Gauss solution and all word conditions; three distractors rejected',()=>{const valid=([x,y,z])=>x+y+z===13000&&Math.abs(2*z/3-2*x)<1e-8&&Math.abs(x+y/5-z/2)<1e-8;assert.deepEqual([[2000,5000,6000],[3000,4000,6000],[2000,6000,5000],[1000,9000,3000]].map(valid),[true,false,false,false]);const p=proof({index:964});assert.deepEqual(p.solution,[2000,5000,6000]);p.matrix.forEach((r,i)=>near(dot(r,p.solution),p.rhs[i]));});
test('0453 five records seven parts deterministic, complete and not enabled',()=>{const a=buildNormalLimitsGaussianBatch('test').batch,b=buildNormalLimitsGaussianBatch('test',[...cases].reverse()).batch;assert.equal(a.records.length,5);assert.equal(a.records.flatMap(r=>r.parts).length,7);assert.deepEqual(a.records,[...b.records].reverse());for(const r of a.records){assert.equal(r.qualityGates.publication,'NOT_ENABLED');assert.equal(r.qualityGates.rendering,'RECHECK_REQUIRED');for(const p of r.parts){assert.equal(p.solutionSteps.length,6);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.answer,p.finalAnswer);}}});
