import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,observations,statements,solve,proof,det3,transformedMatrices,simpson,rationalFunction,primitive,areaGraph,renderMatesAreaGraph,buildMatesBatch} from '../scripts/resolve-andalucia-mates-determinants-integrals.mjs';
const close=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
test('three Math II official pages preserve complete source and binary evidence',()=>{const rows=fs.readFileSync('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl','utf8').trim().split(/\r?\n/).map(JSON.parse);for(const [i,h,p,q,png]of observations){const r=rows.find(r=>r.documentHash===h);assert.equal(sha(fs.readFileSync(r.provenance.localPath)),h);assert.equal(sha(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${i}.png`)),png);assert.ok(p>0&&q);assert.ok(statements[i]);}assert.match(statements[425],/x≠1 y x≠4/);assert.match(statements[428],/F\(0\)=frac\{π\}\{3\}/);});
const transpose=a=>a[0].map((_,i)=>a.map(r=>r[i]));
const multiply=(a,b)=>a.map(r=>b[0].map((_,j)=>r.reduce((s,x,k)=>s+x*b[k][j],0)));
function inverse(a){const d=det3(a);return transpose(a.map((r,i)=>r.map((_,j)=>{const m=a.filter((_,k)=>k!==i).map(row=>row.filter((_,k)=>k!==j));return (-1)**(i+j)*(m[0][0]*m[1][1]-m[0][1]*m[1][0])/d;})));}
test('determinant identities independently hold on 160 diverse official-shaped matrices',()=>{let count=0;for(let k=1;count<160;k++){let A=[[k%7-3,(k*3)%11-5,(k*5)%13-6],[(k*7)%17-8,(k*11)%19-9,(k*13)%23-11],[1,2,3]];const d=det3(A);if(!d)continue;A[0]=A[0].map(x=>2*x/d);close(det3(A),2);const bs=transformedMatrices(A);close(det3(bs[0]),-12);close(det3(bs[1]),-4);const P=multiply(inverse(A),transpose(A)).map(r=>r.map(x=>x/3));close(det3(P),1/27,2e-7);count++;}assert.equal(count,160);});
test('determinant distractors are distinct false pairs or false scalar determinants',()=>{const p=proof(cases[0]);assert.equal(new Set([p.productDeterminant,...p.wrongProducts]).size,4);assert.ok(p.wrongProducts.every(x=>Math.abs(x-1/27)>1e-9));assert.equal(new Set(p.wrongDeterminants.map(JSON.stringify)).size,3);assert.ok(p.wrongDeterminants.every(([a,b])=>a!==-12||b!==-4));});
test('rational function partial fractions, primitive and area verified independently',()=>{for(let i=0;i<=100;i++){const x=2+i/100;assert.ok(rationalFunction(x)<0);close(-1/(x-1)+1/(x-4),rationalFunction(x));const h=1e-5;close((primitive(x+h)-primitive(x-h))/(2*h),rationalFunction(x));}close(primitive(3)-primitive(2),-2*Math.log(2));close(simpson(x=>-rationalFunction(x),2,3),2*Math.log(2));const p=proof(cases[1]);assert.equal(new Set([p.area,...p.wrongAreas]).size,4);});
test('area graph preserves formula, bounds, sign and shading, with no pole-crossing',()=>{assert.deepEqual(areaGraph.area,[2,3]);assert.deepEqual(areaGraph.pieces[0].denominator,[4,-5,1]);assert.ok(areaGraph.pieces[0].range[0]>1&&areaGraph.pieces[0].range[1]<4);const svg=renderMatesAreaGraph(areaGraph);assert.match(svg,/<polygon/);assert.match(svg,/<polyline/);assert.doesNotMatch(svg,/NaN|undefined/);assert.throws(()=>renderMatesAreaGraph({...areaGraph,area:[1,4]}));});
test('both fundamental theorem results independently checked with nonmonotone primitives too',()=>{const h=Math.PI/6;for(const k of[0,.2,1,2]){const F=x=>Math.PI/3+4*x+k*Math.sin(12*x),f=x=>4+12*k*Math.cos(12*x);close(F(0),Math.PI/3);close(F(h),Math.PI);close(simpson(x=>3*f(x)-Math.cos(x),0,h),2*Math.PI-.5);close(simpson(x=>Math.sin(F(x))*f(x),0,h),1.5);if(k===1)assert.ok(f(h/2)<0);}const p=proof(cases[2]);for(const key of['First','Second']){const exact=p[key.toLowerCase()];const wrong=p['wrong'+key];assert.equal(new Set([exact,...wrong]).size,4);assert.ok(wrong.every(x=>Math.abs(x-exact)>1e-9));}});
test('source-bound Math II builds reproducibly with five complete parts and 15 reasoned distractors',()=>{const a=buildMatesBatch('test'),b=buildMatesBatch('test',[...cases].reverse());assert.deepEqual([...a.batch.records].sort((x,y)=>x.exerciseId.localeCompare(y.exerciseId)),[...b.batch.records].sort((x,y)=>x.exerciseId.localeCompare(y.exerciseId)));assert.equal(a.batch.records.reduce((s,r)=>s+r.parts.length,0),5);for(const r of a.batch.records){assert.equal(r.subject,'Matemáticas II');assert.equal(r.matesEvidence.documentHash,r.officialSource.documentHash);for(const p of r.parts){assert.equal(p.answer,p.finalAnswer);assert.ok(p.solutionSteps.length>=5);assert.equal(p.distractorEvidence.length,3);assert.equal(new Set([p.answer,...p.distractors]).size,4);}}const whole=a.batch.records.find(r=>r.correctionEvidence.parameters.index===425);assert.equal(whole.deliveryScope,'WHOLE_OFFICIAL_EXERCISE');assert.equal(whole.sourceSubparts.length,0);assert.equal(whole.parts[0].prompt,whole.sourceLiteral);});
