import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,observations,statements,proof,solve,buildLinearConstraintsBatch} from '../scripts/resolve-andalucia-mates-linear-constraints.mjs';
const near=(a,b,t=1e-7)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),det=A=>A[0][0]*(A[1][1]*A[2][2]-A[1][2]*A[2][1])-A[0][1]*(A[1][0]*A[2][2]-A[1][2]*A[2][0])+A[0][2]*(A[1][0]*A[2][1]-A[1][1]*A[2][0]),mul=(A,B)=>A.map(row=>B[0].map((_,j)=>row.reduce((s,v,k)=>s+v*B[k][j],0))),sub=(A,B)=>A.map((r,i)=>r.map((x,j)=>x-B[i][j])),tr=A=>A[0].map((_,i)=>A.map(r=>r[i])),I=[[1,0,0],[0,1,0],[0,0,1]],zero=A=>A.every(r=>r.every(x=>Math.abs(x)<1e-9));
function rank(A){A=A.map(r=>r.slice());let k=0;for(let j=0;j<A[0].length&&k<A.length;j++){const p=A.findIndex((r,i)=>i>=k&&Math.abs(r[j])>1e-8);if(p<0)continue;[A[p],A[k]]=[A[k],A[p]];const v=A[k][j];A[k]=A[k].map(x=>x/v);for(let i=k+1;i<A.length;i++){const f=A[i][j];A[i]=A[i].map((x,t)=>x-f*A[k][t]);}k++;}return k;}
test('six exact official pages and their question labels are bound by hashes',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);assert.equal(observations[0][3],'B.5');assert.equal(observations[4][3],'B.2');});
test('car counts independently satisfy percentages, difference and uniqueness',()=>{const valid=([x,y,z])=>{const T=x+y+z;return Math.abs(.6*x+.5*y-.3*T)<1e-8&&Math.abs(.2*x+.6*y+.6*z-.5*T)<1e-8&&y-x===100;};assert.ok(valid(proof({index:190}).counts));for(const v of [[600,500,900],[500,600,300],[250,300,450]])assert.ok(!valid(v));assert.notEqual(det([[3,2,-3],[-3,1,1],[-1,1,0]]),0);});
test('parameter system determinant independently expanded and ranks checked at both roots',()=>{for(const m of [-5,-2,-1,0,1,2,4]){const A=[[1,2,1],[1,-1,m],[m,1,3]],B=A.map((r,i)=>[...r,i?m-2:0]);near(det(A),2*(m*m-4));if(m===-2){assert.equal(rank(A),2);assert.equal(rank(B),3);}else if(m===2){assert.equal(rank(A),2);assert.equal(rank(B),2);}else assert.equal(rank(A),3);}});
test('homogeneous family contains every solution and all three wrong families fail',()=>{const A=[[1,2,1],[1,-1,2],[2,1,3]];for(const t of [-5,-1,0,.4,2])for(const row of A)near(dot(row,[-5*t,t,3*t]),0);for(const v of [[5,1,3],[-5,1,-3],[-3,1,1]])assert.ok(A.some(row=>dot(row,v)!==0));assert.equal(rank(A),2);});
test('equidistant point satisfies the original line and both distances, all distractors rejected',()=>{const valid=P=>Math.abs((P[0]+3)/2-(P[1]+5)/3)<1e-9&&Math.abs((P[1]+5)/3-(P[2]+4)/3)<1e-9&&Math.abs(dot(P,P)-dot(P.map((v,i)=>v-[3,2,1][i]),P.map((v,i)=>v-[3,2,1][i])))<1e-9;assert.ok(valid([1,1,2]));for(const P of [[-1,-2,-1],[3,4,5],[1,1,-2]])assert.ok(!valid(P));});
test('matrix inverse checked on both sides and inverse distractors rejected',()=>{const {A,B,inverse:J}=proof({index:196});assert.equal(det(A),2);assert.equal(det(B),0);assert.ok(zero(sub(mul(A,J),I)));assert.ok(zero(sub(mul(J,A),I)));for(const X of [tr(J),A,J.map(r=>r.map(x=>2*x))])assert.ok(!zero(sub(mul(A,X),I)));});
test('power determinant checked independently via preserved null vector',()=>{const {A,B}=proof({index:196});assert.deepEqual(B.map(r=>dot(r,[1,1,0])),[0,0,0]);for(let n=1,P=B;n<=12;n++,P=mul(P,B))near(det(mul(mul(A,P),tr(A))),0);assert.equal(proof({index:196}).determinants[2],0);assert.equal(new Set([0,4,-4,2]).size,4);});
test('matrix equation verified entrywise with source matrices and wrong matrices excluded',()=>{const {A,B,X}=proof({index:196}),AB=mul(A,B),valid=Y=>zero(sub(sub(mul(A,Y),B),AB));assert.ok(valid(X));for(const Y of [tr(X),X.map(r=>r.map(x=>2*x)),B])assert.ok(!valid(Y));assert.deepEqual(AB,[[-1,1,0],[0,0,2],[0,0,-2]]);});
test('integral parameters checked by numerical quadrature and finite differences',()=>{const target=27-8*Math.log(4),integral=(a,b)=>{let s=0,n=100000;for(let i=0;i<n;i++){const x=1+3*(i+.5)/n;s+=a*x*x+b*Math.log(x);}return s*3/n;},f=x=>x*x-2*Math.log(x),h=1e-4;near(integral(1,-2),target);near((f(1+h)-f(1-h))/(2*h),0,1e-7);near((f(1+h)-2*f(1)+f(1-h))/(h*h),4,1e-6);for(const [a,b]of [[-1,2],[1,2],[2,-4]])assert.ok(Math.abs(2*a+b)>1e-8||Math.abs(integral(a,b)-target)>1e-5);});
test('perpendicular plane satisfies point and original line direction, rejects all alternatives',()=>{const p=proof({index:203});near(dot(p.normal,p.point)+p.planeConstant,0);for(const [n,k]of [[[ -2,1,2],-12],[[2,1,2],8],[[-2,1,2],0]])assert.ok(Math.abs(dot(n,p.point)+k)>0||n[0]/-2!==n[1]);});
test('line-plane sine verified by orthogonal projection and all distractors rejected',()=>{const p=proof({index:203}),u=p.rDirection,n=p.normal;near(dot([2,-3,1],u),0);near(dot([-3,2,2],u),0);const proj=n.map(x=>x*dot(u,n)/dot(n,n)),s=Math.sqrt(dot(proj,proj)/dot(u,u));near(s,p.sine);for(const x of [1/Math.sqrt(138),8/(3*Math.sqrt(138)),Math.sqrt(1241)/(3*Math.sqrt(138))])assert.ok(Math.abs(x-s)>1e-4);});
test('ten complete parts preserve answers and have four distinct options with evidence',()=>{let count=0;for(const c of cases)for(const p of solve(c,statements[c.index])){count++;assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.distractorEvidence.length,3);assert.ok(p.solutionSteps.length>=6);assert.equal(p.verification.verified,true);}assert.equal(count,10);});
test('batch deterministic under reverse ordering and does not publish by construction',()=>{const a=buildLinearConstraintsBatch('test').batch,b=buildLinearConstraintsBatch('test',[...cases].reverse()).batch;assert.deepEqual(a.records,[...b.records].reverse());assert.equal(a.records.length,6);for(const r of a.records){assert.equal(r.subject,'Matemáticas II');assert.equal(r.qualityGates.publication,'NOT_ENABLED');}});
