import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,buildDocContinuityBatch} from '../scripts/resolve-andalucia-doc-continuity-2012.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`),records=()=>buildDocContinuityBatch('doc-continuity-test').batch.records,sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
test('DOC17 initial value, strict growth and exact asymptotic residual',()=>{const f=t=>(11*t+20)/(t+2);near(f(0),10);for(const t of[0,.2,1,2,10,100,1e5]){near(11-f(t),2/(t+2));assert.ok(f(t)<11);near(f(t+.5)-f(t),1/((t+2)*(t+2.5)));assert.ok(f(t+.5)>f(t));}for(const v of[20,11,0])assert.notEqual(f(0),v);assert.notEqual(f(2),11);});
test('DOC23 continuity and differentiability determine two parameters independently',()=>{const valid=([a,b])=>Math.abs(4*a+6+2*b)<1e-9&&Math.abs(4*a+3-(4-b))<1e-9;assert.ok(valid([2,-7]));for(const w of[[2,7],[-2,1],[1,-5]])assert.ok(!valid(w));near(4*2+6,14);near(4*2+3,11);});
test('DOC23 tangent matches value, slope and exact second-order residual',()=>{const g=x=>(x+2)/(x-1);for(const x of[-2,-.4,0,.2,.8,2])near(g(x)-(-3*x-2),3*x*x/(x-1));near(g(0),-2);near((g(1e-5)-g(-1e-5))/2e-5,-3);for(const[m,b]of[[3,-2],[-2,-2],[-3,2]])assert.ok(m!==-3||b!==g(0));});
test('DOC27 global differentiability needs both continuity and derivative equations',()=>{const valid=([a,b])=>a+b===12&&a-2===4;assert.ok(valid([6,6]));for(const w of[[4,8],[6,-6],[6,4]])assert.ok(!valid(w));near(-1+6-7,4-6);});
test('three official exercises, six full parts and eighteen nonduplicate distractors',()=>{const rr=records();assert.equal(rr.length,3);assert.equal(rr.reduce((s,r)=>s+r.parts.length,0),6);for(const r of rr){assert.equal(sha(r.officialSource.path),r.officialSource.documentHash);assert.equal(r.examSlot,3);for(const p of r.parts){assert.equal(p.distractors.length,3);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.ok(p.solutionSteps.length>=6);assert.equal(p.verification.verified,true);}}});
test('deterministic regeneration, inverse-order invariance and untouched sources',()=>{const paths=['data/andalucia-pau-runtime.js','math-renderer.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=paths.map(sha),sort=a=>a.sort((x,y)=>x.exerciseId.localeCompare(y.exerciseId));assert.deepEqual(records(),records());assert.deepEqual(sort(records()),sort(buildDocContinuityBatch('doc-continuity-test',[...cases].reverse()).batch.records));assert.deepEqual(paths.map(sha),before);});
