import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {observations,cases,proof,statements,buildSourceCalculusRanksBatch} from '../scripts/resolve-andalucia-mates-source-calculus-ranks.mjs';
const near=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],det=A=>dot(A[0],cross(A[1],A[2]));
function rank(input){const a=input.map(r=>[...r]);let i=0;for(let j=0;j<a[0].length&&i<a.length;j++){let k=i;while(k<a.length&&Math.abs(a[k][j])<1e-8)k++;if(k===a.length)continue;[a[i],a[k]]=[a[k],a[i]];const pivot=a[i][j];a[i]=a[i].map(x=>x/pivot);for(k=0;k<a.length;k++)if(k!==i){const f=a[k][j];a[k]=a[k].map((x,q)=>x-f*a[i][q]);}i++;}return i;}
function simpson(f,a,b,n=10000){const h=(b-a)/n;let s=f(a)+f(b);for(let j=1;j<n;j++)s+=(j%2?4:2)*f(a+j*h);return s*h/3;}
const derivative=(f,x,h=1e-5)=>(f(x+h)-f(x-h))/(2*h);
test('eleven official sources and inspected page images retain exact hashes',()=>{const q=fs.readFileSync('artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl','utf8').trim().split(/\r?\n/).map(JSON.parse),canon=new Map(fs.readFileSync('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl','utf8').trim().split(/\r?\n/).map(JSON.parse).map(r=>[r.exerciseId,r]));for(const o of observations){const e=canon.get(q[o[0]].exerciseId);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(e.provenance.localPath)).digest('hex'),o[1]);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);}assert.match(statements[603],/e\^\(−x\)/);assert.ok(!statements[603].includes('9−x'));});
test('603 exponential quotient derivative, extremum and directional asymptotes',()=>{const f=x=>Math.exp(-x)/(1-x),df=x=>x*Math.exp(-x)/(1-x)**2;for(const x of[-3,-.5,0,.3,2,4])near(derivative(f,x),df(x),1e-6);near(f(0),1);assert.ok(f(1-1e-6)>1e5&&f(1+1e-6)<-1e5);assert.ok(Math.abs(f(40))<1e-15&&f(-40)>1e12&&f(-40)/(-40)<-1e10);assert.deepEqual([-1,.5,2].map(x=>Math.sign(df(x))),[-1,1,1]);const options=[{x:0,y:1,type:'min'},{x:0,y:1,type:'max'},{x:1,y:0,type:'min'},{x:0,y:-1,type:'min'}];assert.deepEqual(options.map(v=>Number.isFinite(f(v.x))&&Math.abs(f(v.x)-v.y)<1e-9&&v.type==='min'&&df(v.x-.01)<0&&df(v.x+.01)>0),[true,false,false,false]);});
test('606 three plane tasks independently verified by points and directions',()=>{const p=proof({index:606});near(dot(p.n,p.d),0);near(dot(p.n,p.P)+2,6);assert.ok(Math.hypot(...cross(p.n,p.d))>0);const cand=[p.perpendicular,[1,-4,-2,-7],p.parallel,[1,4,-2,7]];assert.deepEqual(cand.map(a=>dot(a.slice(0,3),p.d)===0&&dot(a.slice(0,3),p.n)===0&&dot(a.slice(0,3),p.P)+a[3]===0),[true,false,false,false]);const parametrizations=[(u,v)=>[5+u,-2*u+v,6+v],(u,v)=>[5+u,2*u+v,6+v],(u,v)=>[5+u,-2*u+v,-6+v],(u,v)=>[5+u,-2*u+v,6-v]];assert.deepEqual(parametrizations.map(f=>[[0,0],[2,1],[-3,4]].every(([u,v])=>dot(p.n,f(u,v))-4===0)),[true,false,false,false]);for(const t of[-2,0,3])assert.deepEqual(parametrizations[0](-2*t,-3*t),p.P.map((x,i)=>x+t*p.d[i]));});
test('607 piecewise integral checked by direct quadrature and differentiating both primitives',()=>{const f=x=>x*Math.sin(2*x),g=x=>Math.cos(Math.PI*x)-1,F=x=>-x*Math.cos(2*x)/2+Math.sin(2*x)/4,G=x=>Math.sin(Math.PI*x)/Math.PI-x;const a=simpson(f,-Math.PI/4,0),b=simpson(g,0,1);near(a,.25);near(b,-1);for(const x of[-.7,-.4,-.1])near(derivative(F,x),f(x));for(const x of[.1,.4,.8])near(derivative(G,x),g(x));assert.deepEqual([-.75,-1.25,.25,1.25].map(x=>Math.abs(x-a-b)<1e-8),[true,false,false,false]);});
const sys609=a=>({A:[[a,1,1],[1,2,-1],[1,1+a,-a]],b:[1+a,1-a,0]}),sys623=m=>({A:[[m,2,-1],[5,-4,2],[1,3*m,0]],b:[1,0,m+2/5]});
const sat=(s,v)=>s.A.every((r,j)=>Math.abs(dot(r,v)-s.b[j])<1e-8);
test('609 all singular ranks and solution/distractors checked against original system',()=>{for(const a of[-3,0,1,2,4]){const s=sys609(a);near(det(s.A),-(a-1)*(a-2));assert.deepEqual([rank(s.A),rank(s.A.map((r,i)=>[...r,s.b[i]]))],a===1?[2,2]:a===2?[2,3]:[3,3]);}assert.deepEqual([[-1,1,0],[1,1,0],[-1,0,1],[-1,1,1]].map(v=>sat(sys609(0),v)),[true,false,false,false]);assert.deepEqual([[1],[2],[1,2],[]].map(xs=>JSON.stringify(xs)===JSON.stringify([1])),[true,false,false,false]);});
test('611 characteristic determinant and kernel independently computed for all roots',()=>{const A=[[2,0,2],[-1,2,1],[0,1,4]],M=l=>A.map((r,i)=>r.map((v,j)=>v-(i===j?l:0)));for(const l of[-3,0,1,2,3,4,5]){near(det(M(l)),-(l-1)*(l-3)*(l-4));assert.equal(rank(M(l)),[1,3,4].includes(l)?2:3);}const vectors=[t=>[-2*t,-3*t,t],t=>[2*t,-3*t,t],t=>[-2*t,3*t,t]];assert.deepEqual(vectors.map(f=>[-2,1,3].every(t=>M(1).every(r=>dot(r,f(t))===0))),[true,false,false]);assert.ok(M(1).every(r=>dot(r,[2,3,-1])===0));assert.equal(proof({index:611}).specific[0],2);});
test('613 inflexion, tangent and normal checked with numerical derivatives',()=>{const f=x=>(x-1)*Math.exp(x),p=proof({index:613});near(f(-1),p.inflexion[1]);near(derivative(f,-1),p.tangent[0]);const d2=x=>(f(x+1e-3)-2*f(x)+f(x-1e-3))/1e-6;assert.ok(d2(-1.1)<0&&d2(-.9)>0);const options=[[p.tangent,p.normal],[[1/Math.E,3/Math.E],[-Math.E,-Math.E-2/Math.E]],[p.tangent,[1/Math.E,-1/Math.E]], [[-1/Math.E,-1/Math.E],[Math.E,Math.E]]];assert.deepEqual(options.map(([t,n])=>Math.abs(t[0]+1/Math.E)<1e-8&&Math.abs(-t[0]+t[1]-f(-1))<1e-8&&Math.abs(-n[0]+n[1]-f(-1))<1e-8&&Math.abs(t[0]*n[0]+1)<1e-8),[true,false,false,false]);assert.ok(Math.abs(f(-40))<1e-14&&f(40)/40>1e16);assert.ok(Number.isFinite(f(1)));});
test('614 rational parameters uniquely satisfy vertical asymptote, point and slope',()=>{assert.deepEqual([[10,2,1],[2,10,1],[6,-2,1],[10,2,-1]].map(([a,b,c])=>1-c===0&&b-a!==0&&Math.abs((a+b)/(c+1)-6)<1e-9&&Math.abs((a-b*c)/(c+1)**2-2)<1e-9),[true,false,false,false]);near(derivative(x=>(10*x+2)/(x+1),1),2);});
test('617 substitution integral independently checked in original x coordinate',()=>{const I=simpson(x=>Math.sin(Math.sqrt(x)),0,Math.PI**2,100000);near(I,2*Math.PI,1e-6);assert.deepEqual([2*Math.PI,2,Math.PI,-2*Math.PI].map(x=>Math.abs(x-I)<1e-6),[true,false,false,false]);for(const t of[.2,1,2.7])near(derivative(x=>-2*x*Math.cos(x)+2*Math.sin(x),t),2*t*Math.sin(t));});
test('618 cancellation limit checked on both sides and distinct plausible options',()=>{const f=x=>1/x-Math.cos(x)/Math.sin(x);for(const x of[-.01,-.001,.001,.01])assert.ok(Math.abs(f(x))<Math.abs(x)/2);near(f(.001)/.001,1/3,1e-6);near(f(-.001)/(-.001),1/3,1e-6);assert.deepEqual([0,1,1/3].map(x=>Math.abs(f(.0001)-x)<1e-4),[true,false,false]);assert.ok(Math.abs(f(.0001)-f(-.0001))<1e-4);});
test('619 one-sided derivatives, monotonicity and continuity independently verified',()=>{const f=x=>(1+Math.abs(x))/(1-Math.abs(x));near((f(-1e-6)-1)/(-1e-6),-2,3e-6);near((f(1e-6)-1)/1e-6,2,3e-6);assert.ok(Math.abs(f(1e-7)-f(0))<3e-7);for(const x of[-.8,-.3,.2,.6])near(derivative(f,x),x<0?-2/(1+x)**2:2/(1-x)**2,1e-6);assert.ok(f(-.8)>f(-.3)&&f(.2)<f(.6));assert.deepEqual([[-1,1],[1,-1],[1,1],[-1,-1]].map(v=>v[0]===Math.sign(derivative(f,-.3))&&v[1]===Math.sign(derivative(f,.3))),[true,false,false,false]);});
test('623 singular ranks, free family and impossibility of x=0 independently verified',()=>{for(const m of[-4,-2.5,-1,0,1,3]){const s=sys623(m);near(det(s.A),-3*m*(2*m+5));assert.deepEqual([rank(s.A),rank(s.A.map((r,i)=>[...r,s.b[i]]))],m===0?[2,2]:m===-2.5?[2,3]:[3,3]);}const fns=[t=>[.4,t,2*t-1],t=>[.4,t,2*t+1],t=>[-.4,t,2*t-1],t=>[0,t,2*t-1]];assert.deepEqual(fns.map(f=>[-2,0,3].every(t=>sat(sys623(0),f(t)))),[true,false,false,false]);assert.notEqual(sys623(0).b[2],0);});
test('eleven exercises, nineteen parts and 57 distractors reproduce under reversed input order',()=>{const a=buildSourceCalculusRanksBatch('test').batch,b=buildSourceCalculusRanksBatch('test',[...cases].reverse()).batch;assert.equal(a.records.length,11);assert.equal(a.records.flatMap(r=>r.parts).length,19);assert.deepEqual(a.records,[...b.records].reverse());for(const r of a.records)for(const p of r.parts){assert.ok(p.partId);assert.equal(p.answer,p.finalAnswer);assert.equal(p.solutionSteps.length,6);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.distractorEvidence.length,3);}});
