import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,buildDocMatricesBatch,projectNativeMatrices} from '../scripts/resolve-andalucia-doc-matrices-2012.mjs';
const rows=()=>buildDocMatricesBatch('doc-matrices-test').batch.records,sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const mul=(A,B)=>A.map(r=>B[0].map((_,j)=>r.reduce((s,x,k)=>s+x*B[k][j],0))),add=(A,B,k=1)=>A.map((r,i)=>r.map((x,j)=>x+k*B[i][j]));
test('DOC1 monthly quantities obey the three distinct source rules',()=>{const r=rows().find(r=>r.correctionEvidence.parameters.index===1),e=r.parts[0].verification.numericalEvidence;
 assert.deepEqual(e.E,[[9,5],[3,7],[4,6]]);assert.deepEqual(e.F,e.E.map((r,i)=>r.map(x=>i<2?2*x:x+1)));assert.deepEqual(e.M,e.F.map((r,i)=>r.map(x=>i?x:0)));
 assert.deepEqual(add(add(e.E,e.F),e.M),r.parts[1].verification.numericalEvidence.T);
 for(const w of r.parts[1].verification.numericalEvidence.wrong)assert.notDeepEqual(w,add(add(e.E,e.F),e.M));
 for(const w of r.parts[0].distractors)assert.notEqual(w,r.parts[0].answer);
});
test('DOC1 all client invoices checked by independent month totals and both price orders',()=>{const r=rows().find(r=>r.correctionEvidence.parameters.index===1),e=r.parts[0].verification.numericalEvidence,t=r.parts[1].verification.numericalEvidence.T,v=r.parts[2].verification.numericalEvidence;
 const prices=[[80],[100]],invoices=mul(t,prices).flat();assert.deepEqual(invoices,v.invoices);assert.equal(invoices.reduce((a,b)=>a+b,0),11480);
 assert.equal([e.E,e.F,e.M].map(A=>mul(A,prices).flat().reduce((a,b)=>a+b,0)).reduce((a,b)=>a+b,0),v.total);
 assert.deepEqual([...mul(t,[[100],[80]]).flat(),11200],v.wrong[0]);assert.deepEqual([...mul(add(e.E,e.F),prices).flat(),8500],v.wrong[1]);assert.deepEqual([...t.map(r=>r[0]+r[1]),126],v.wrong[2]);for(const w of v.wrong)assert.notDeepEqual(w,[...invoices,v.total]);
});
test('DOC5 original equation residual uniquely accepts correct X and rejects each distractor',()=>{const e=rows().find(r=>r.correctionEvidence.parameters.index===5).parts[0].verification.numericalEvidence,S=mul(e.A,e.A),R=add(e.A,mul(e.B,e.C),-1);
 assert.deepEqual(S,[[1,3],[0,4]]);assert.deepEqual(R,[[0,1],[-8,1]]);assert.deepEqual(mul(S,e.X),R);assert.equal(S[0][0]*S[1][1]-S[0][1]*S[1][0],4);
 for(const w of e.wrong)assert.notDeepEqual(mul(S,w),R);assert.deepEqual(mul([[1,-.5],[0,.5]],R),e.wrong[0]);assert.deepEqual(mul(R,[[1,-.75],[0,.25]]),e.wrong[1]);assert.deepEqual(mul([[1,-.75],[0,.25]],add(e.A,mul(e.B,e.C))),e.wrong[2]);
});
test('native matrix projection preserves exact entries, shape, round delimiters and original literal',()=>{const r=rows().find(r=>r.correctionEvidence.parameters.index===5),p=r.parts[0],x=projectNativeMatrices(r.sourceLiteral);assert.equal(x.changes.length,3);assert.equal(x.text,p.prompt);let restored=x.text,delta=0;const positions=x.changes.map(c=>{const at=c.offset+delta;delta+=c.after.length-c.before.length;return{...c,at};});for(const c of positions.reverse())restored=restored.slice(0,c.at)+c.before+restored.slice(c.at+c.after.length);assert.equal(restored,r.sourceLiteral);assert.equal(p.promptRepresentationEvidence.mathematicalChange,false);
 assert.throws(()=>projectNativeMatrices(String.raw`\left(\begin{matrix}1 & ? \\ 0 & 2\end{matrix}\right)`),/complete native/);
});
test('two official exercises have four complete parts and twelve plausible checked options',()=>{const rr=rows();assert.equal(rr.length,2);assert.equal(rr.reduce((s,r)=>s+r.parts.length,0),4);for(const r of rr){assert.equal(sha(r.officialSource.path),r.officialSource.documentHash);assert.equal(r.examSlot,1);for(const p of r.parts){assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.distractorEvidence.length,3);assert.ok(p.solutionSteps.length>=6);}}});
test('DOC matrix batch is deterministic, order independent and leaves sources and runtime intact',()=>{const paths=['data/andalucia-pau-runtime.js','math-renderer.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=paths.map(sha),sort=a=>a.sort((x,y)=>x.exerciseId.localeCompare(y.exerciseId));assert.deepEqual(rows(),rows());assert.deepEqual(sort(rows()),sort(buildDocMatricesBatch('doc-matrices-test',[...cases].reverse()).batch.records));assert.deepEqual(paths.map(sha),before);});
