import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {observations,cases,proof,solve,buildFtcPrimitivesOptimumBatch} from '../scripts/resolve-andalucia-mates-ftc-primitives-optimum.mjs';
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),d=(f,x,h=1e-5)=>(f(x+h)-f(x-h))/(2*h);
test('four intact official page evidence hashes',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);});
test('fundamental theorem tangent independently follows explicit primitive',()=>{const F=x=>x*x+2/3*x**1.5;near(d(F,1),3);near(F(1),5/3);near(3-4/3,F(1));for(const [m,b]of [[3,5/3],[2.5,-5/6],[3,-1/3]])assert.ok(Math.abs(m-d(F,1))>.1||Math.abs(m+b-F(1))>.1);});
test('cubic satisfies both points, inflection and vertical normal',()=>{const f=x=>-2*x**3+6*x+4;near(f(0),4);near(f(1),8);near(d(f,1),0);assert.ok(-12*(-.1)>0&&-12*.1<0);for(const [a,c,e]of [[2,-6,4],[-2,6,0],[-4,12,4]])assert.ok(e!==4||a+c+e!==8||3*a+c!==0);assert.deepEqual(proof(cases[1]),{a:-2,b:0,c:6,d:4});});
test('cosine square-root primitive checks derivative, endpoint and distractors',()=>{const H=(x,a=2,b=2,c=3)=>a*Math.sqrt(x)*Math.sin(Math.sqrt(x))+b*Math.cos(Math.sqrt(x))+c;near(H(0),5);for(const x of [.001,.1,1,3,9])near(d(H,x),Math.cos(Math.sqrt(x)));near((H(1e-5)-H(0))/1e-5,1,3e-6);for(const [a,b,c]of [[2,2,5],[2,-2,7],[1,1,4]])assert.ok(H(0,a,b,c)!==5||Math.abs(d(x=>H(x,a,b,c),1)-Math.cos(1))>.1);});
test('right triangle optimum verified by derivative and Pythagoras',()=>{const x=5/Math.sqrt(2),A=x=>x*Math.sqrt(25-x*x)/2;near(2*x*x,25);near(A(x),25/4);near(d(A,x),0);for(const z of [.1,1,2,3,4,4.9])assert.ok(A(z)<A(x));assert.equal(3*4/2,6);assert.notEqual(2*(2.5**2),25);assert.notEqual(2*25,25);});
test('four complete solutions maintain all three plausible false alternatives',()=>{for(const c of cases){const [p]=solve(c);assert.equal(p.solutionSteps.length,6);assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.distractorEvidence.length,3);}});
test('source-bound construction reversible order and no automatic enabling',()=>{const a=buildFtcPrimitivesOptimumBatch('test').batch,b=buildFtcPrimitivesOptimumBatch('test',[...cases].reverse()).batch;const sort=x=>x.records.toSorted((a,b)=>a.exerciseId.localeCompare(b.exerciseId));assert.deepEqual(sort(a),sort(b));for(const r of a.records){assert.equal(r.deliveryScope,'WHOLE_OFFICIAL_EXERCISE');assert.equal(r.qualityGates.publication,'NOT_ENABLED');}});
