import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {observations,cases,solve,proof,graphs,renderNormalAbsoluteAreas,buildNormalAbsoluteAreasBatch} from '../scripts/resolve-andalucia-mates-normal-absolute-areas.mjs';
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),d=(f,x)=>(f(x+1e-5)-f(x-1e-5))/2e-5;
function integral(f,a,b,n=20000){let s=0;for(let i=0;i<n;i++)s+=f(a+(i+.5)*(b-a)/n);return s*(b-a)/n;}
test('normal-absolute official pages preserve inspection hashes',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);});
test('normal independently meets point and perpendicular derivative, with exactly one correct option',()=>{const f=x=>-x*x+6*x-5,valid=([m,b])=>Math.abs(4*m+b-f(4))<1e-8&&Math.abs(m*d(f,4)+1)<1e-7;assert.deepEqual([[.5,1],[-2,11],[-.5,5],[.5,3]].map(valid),[true,false,false,false]);});
test('parabola-line roots, positive area, primitive and all distinct false areas independently checked',()=>{const g=x=>-x*x+6*x-5,r=x=>x/2+1,H=x=>-(x**3)/3+11*x*x/4-6*x,p=proof({index:328});for(const[x,y]of p.intersections){near(g(x),y);near(r(x),y);}for(const x of[1.5,2,2.5,3,4]){near(d(H,x),g(x)-r(x));assert.ok(g(x)>=r(x));}const area=integral(x=>g(x)-r(x),1.5,4);near(area,125/48);assert.deepEqual([125/48,125/24,125/96,-125/48].map(v=>Math.abs(v-area)<1e-6),[true,false,false,false]);});
test('absolute quadratic branches and graphical intersections do not use the wrong extension',()=>{const f=x=>6*x-x*x,g=x=>Math.abs(x*x-2*x);for(const[x,y]of proof({index:331}).intersections){near(f(x),y);near(g(x),y);}near(g(2),0);near(f(2),8);for(const x of[.1,1,1.9,2,2.1,3,3.9])assert.ok(f(x)>g(x));for(const x of[-2,-.1,4.1,5])assert.ok(f(x)<g(x));near(g(1),1);near(f(3),9);});
test('split quadrature yields 56/3; three plausible wrong branch/omission choices are false',()=>{const diff=x=>6*x-x*x-Math.abs(x*x-2*x),a=integral(diff,0,2),b=integral(diff,2,4);near(a,8);near(b,32/3);const total=integral(diff,0,4);near(total,a+b);assert.deepEqual([56/3,64/3,32,32/3].map(x=>Math.abs(x-total)<1e-6),[true,false,false,false]);});
test('containing plane passes origin and every line point; all alternate planes rejected',()=>{const p=proof({index:333}),valid=([n,k])=>k===0&&dot(n,p.point)===0&&dot(n,p.direction)===0;assert.deepEqual([[[-5,5,-4],0],[[-5,5,-4],3],[[1,2,-1],0],[[1,-3,-5],0]].map(valid),[true,false,false,false]);for(const t of[-5,-1,0,1,7]){const q=p.point.map((x,i)=>x+t*p.direction[i]);near(q[0]+2*q[1]-q[2],3);near(2*q[0]-q[1]+q[2],1);near(dot(p.containingNormal,q),0);}});
test('perpendicular parametric plane has correct anchor and two independent orthogonal directions',()=>{const n=[1,-3,-5],valid=([P,u,v])=>dot(n,P)===-2&&dot(n,u)===0&&dot(n,v)===0&&(u[1]*v[2]-u[2]*v[1])!==0;assert.deepEqual([[[1,1,0],[3,1,0],[5,0,1]],[[1,1,0],[1,-3,-5],[5,0,1]],[[0,0,0],[3,1,0],[5,0,1]],[[1,1,0],[3,1,0],[-5,0,1]]].map(valid),[true,false,false,false]);});
test('route equations have multiple integer solutions until new constraint; wrong trip options rejected',()=>{const valid=([a,b,c],extra=false)=>a+b+c===70&&b===a+c&&2*(a+c)===70&&(!extra||2*c===b-5);for(let t=1;t<35;t++)assert.ok(valid([35-t,35,t]));assert.deepEqual([[20,35,15],[15,35,20],[5,35,30],[10,35,25]].map(x=>valid(x,true)),[true,false,false,false]);assert.deepEqual(proof({index:341}).trips,[20,35,15]);});
test('two reproducible source-bound graphs contain proper curves, shading and labels',()=>{for(const g of Object.values(graphs)){const s=renderNormalAbsoluteAreas(g);assert.equal(s,renderNormalAbsoluteAreas(structuredClone(g)));assert.equal((s.match(/<polyline/g)||[]).length,2);assert.match(s,/<polygon/);assert.match(s,/Cortes:/);assert.doesNotMatch(s,/NaN|undefined/);}assert.throws(()=>renderNormalAbsoluteAreas({...graphs[328],index:333}));});
test('eight full pedagogical parts preserve answers and distinct options; reversal stable, not enabled',()=>{const ps=cases.flatMap(solve);assert.equal(ps.length,8);for(const p of ps){assert.equal(p.solutionSteps.length,6);assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);}const a=buildNormalAbsoluteAreasBatch('test').batch,b=buildNormalAbsoluteAreasBatch('test',[...cases].reverse()).batch;assert.deepEqual(a.records,[...b.records].reverse());a.records.forEach(x=>assert.equal(x.qualityGates.publication,'NOT_ENABLED'));});
