import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,buildOfficialApplicationsBatch,functions,graphSpecs,renderOfficialApplicationsGraph} from '../scripts/resolve-andalucia-calculus-official-applications.mjs';
import {officialApplicationsObservations,officialApplicationsReplacements} from '../scripts/andalucia-calculus-official-applications-pdf-evidence.mjs';
const rows=()=>buildOfficialApplicationsBatch('official-applications-test').batch.records,ev=(i,k)=>rows().find(r=>r.correctionEvidence.parameters.index===i).parts[k].verification.numericalEvidence;
const close=(a,b,t=1e-5)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),d=(f,x)=>(f(x+1e-5)-f(x-1e-5))/2e-5,sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function integral(f,a,b,n=40000){const h=(b-a)/n;let s=0;for(let k=0;k<n;k++)s+=h*f(a+(k+.5)*h);return s;}
test('76: two official tangents verified by difference quotient, points and all wrong-line mechanisms',()=>{const p=ev(76,0),{f,g}=functions[76];close(d(f,0),p.slopes[0]);close(d(g,0),p.slopes[1]);assert.equal(f(0),p.intercepts[0]);assert.equal(g(0),p.intercepts[1]);for(const [m,b,n,c]of p.wrong)assert.ok(m!==p.slopes[0]||b!==p.intercepts[0]||n!==p.slopes[1]||c!==p.intercepts[1]);for(const x of [-.2,.1,.7])close(d(f,x),((6*x+5)*(7-3*x)+3*(3*x*x+5*x-2))/(7-3*x)**2);});
test('76: two definite integrals independently quadrature-verified and primitive differentiated',()=>{const p=ev(76,1),{u,v}=functions[76];close(integral(u,-2,-1),35/72,1e-8);close(integral(v,-3,0),.6*(1-Math.exp(-1)),1e-8);close(d(x=>-5/(9*x**3),-1.5),u(-1.5));close(d(x=>.6*Math.exp(x/3),-1.2),v(-1.2));for(const w of p.wrong)assert.ok(w.some((x,i)=>Math.abs(x-p.values[i])>.1));assert.equal(new Set(p.wrong.map(JSON.stringify)).size,3);});
test('193: roots extrema monotonicity and second derivative independently checked',()=>{const f=functions[193],p=ev(193,0);for(const x of p.roots)assert.equal(f(x),0);p.critical.forEach((x,k)=>{close(d(f,x),0);close(f(x),p.values[k]);});for(const x of [-2,0,.7,1,1.3,2,4])close(d(f,x),3*x*x-6*x+2);assert.ok(d(f,0)>0&&d(f,1)<0&&d(f,2)>0);assert.ok(6*p.critical[0]-6<0&&6*p.critical[1]-6>0);assert.deepEqual(p.inflexion,[1,0]);for(const u of [.1,.5,2])close(f(1+u),-f(1-u));});
test('193: unsigned bounded area is one half, not the cancelling signed integral',()=>{const f=functions[193],p=ev(193,2);close(integral(f,0,1),.25,1e-8);close(integral(f,1,2),-.25,1e-8);close(integral(x=>Math.abs(f(x)),0,2),p.area,1e-8);close(integral(f,0,2),0,1e-8);close(d(x=>x**4/4-x**3+x*x,.7),f(.7));for(const w of p.wrongAreas)assert.notEqual(w,p.area);});
test('498: complete domain, joins, vertex and roots match the temperature function',()=>{const f=functions[498],a=ev(498,0),b=ev(498,1);assert.throws(()=>f(-1));assert.throws(()=>f(25));for(const t of a.joins){assert.equal(f(t),-9);close(f(t-1e-7),-9);close(f(t+1e-7),-9);}assert.equal(f(6),16);b.roots.forEach(x=>assert.equal(f(x),0));for(let k=0;k<=2400;k++){const y=f(k/100);assert.ok(y>=-9&&y<=16);}assert.equal(-6*6+12*6-20,b.vertex[1]);});
test('498: power-return interpretation distinguishes cooling from return to set point',()=>{const f=functions[498],p=ev(498,2);assert.equal(p.duration,5);assert.equal(p.interpretation,'POWER_RETURN_IDENTIFIED_WITH_START_OF_COOLING_IN_GIVEN_THERMAL_MODEL');for(const t of [1.1,2,4,5.9])assert.ok(d(f,t)>0);for(const t of [6.1,8,10.9])assert.ok(d(f,t)<0);assert.deepEqual(p.outage,[1,6]);assert.equal(f(11),-9);});
test('498: threshold inequalities, not power-outage duration, determine damaged products',()=>{const p=ev(498,3),f=functions[498];assert.equal(p.maximum,16);assert.equal(p.serumSpoiled,false);assert.equal(p.vaccineSpoiled,true);for(let k=0;k<=2400;k++){const t=k/100;assert.equal(f(t)>0,t>2&&t<10);assert.ok(f(t)<20);}assert.equal(p.positiveDuration,8);assert.ok(p.positiveDuration>p.vaccineThreshold);});
test('533: all closed-domain extrema including duplicated minimum are checked',()=>{const f=functions[533],a=ev(533,0),b=ev(533,1);assert.deepEqual(a.endpointValues,[-6,14]);assert.deepEqual(a.euros,[-6000,14000]);b.candidates.forEach((t,k)=>assert.equal(f(t),b.candidateValues[k]));for(const t of b.critical)close(d(f,t),0);for(let k=0;k<=1000;k++){const t=k/100,y=f(t);assert.ok(y>=-6-1e-9&&y<=210+1e-9);close(y+6,2*t*(t-9)**2,1e-9);}assert.deepEqual(b.minima,[[0,-6],[9,-6]]);assert.deepEqual(b.maximum,[3,210]);assert.ok(d(f,1)>0&&d(f,6)<0&&d(f,9.5)>0);});
test('official graphs encode actual formulas and correct signed area geometry',()=>{for(const s of Object.values(graphSpecs)){for(const p of s.points)close(functions[s.index](p.xy[0]),p.xy[1]);for(const p of s.pieces)for(let k=1;k<100;k++){const x=p.range[0]+(p.range[1]-p.range[0])*k/100;close(p.coefficients.reduce((n,c,i)=>n+c*x**i,0),functions[s.index](x));}const svg=renderOfficialApplicationsGraph(s);assert.equal(svg,renderOfficialApplicationsGraph(s));assert.doesNotMatch(svg,/undefined|NaN/);assert.equal((svg.match(/<polyline /g)||[]).length,s.pieces.length);assert.throws(()=>renderOfficialApplicationsGraph({...s,yRange:[0,1]}));}});
test('four official pages bind eleven full subparts with reversible source projection and distinct options',()=>{const r=rows();assert.equal(r.length,4);assert.equal(r.reduce((n,x)=>n+x.parts.length,0),11);for(const x of r){const i=x.correctionEvidence.parameters.index,o=officialApplicationsObservations.find(o=>o[0]===i);assert.equal(sha(fs.readFileSync(x.officialSource.path)),o[1]);assert.equal(sha(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${i}.png`)),o[4]);let text=x.sourceLiteral;const changes=[];for(const[before,after]of officialApplicationsReplacements({...x,queueIndex:i})){const offset=text.indexOf(before);assert.ok(offset>=0);text=text.replace(before,after);changes.push({before,after,offset});}assert.doesNotMatch(text.replace(/\([\d.,]+ puntos?\)/g,''),/undefined/);for(const c of changes.reverse())text=text.slice(0,c.offset)+c.before+text.slice(c.offset+c.after.length);assert.equal(text,x.sourceLiteral);for(const p of x.parts){assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.ok(p.solutionSteps.length>=5);}}});
test('official calculus application batch is reproducible and order invariant without changing originals',()=>{const paths=['data/andalucia-pau-runtime.js','math-renderer.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=paths.map(p=>sha(fs.readFileSync(p))),sort=r=>r.sort((a,b)=>a.exerciseId.localeCompare(b.exerciseId));assert.deepEqual(rows(),rows());assert.deepEqual(sort(rows()),sort(buildOfficialApplicationsBatch('official-applications-test',[...cases].reverse()).batch.records));assert.deepEqual(paths.map(p=>sha(fs.readFileSync(p))),before);});
