import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,buildAreaResourceBatch,greenhouseGraph,renderGreenhouseGraph} from '../scripts/resolve-andalucia-area-and-resource-production.mjs';import {areaResourceObservations,areaResourceReplacements} from '../scripts/andalucia-area-resource-pdf-evidence.mjs';import {feasible} from '../scripts/resolve-andalucia-linear-region-official.mjs';import {renderRationalGraph} from '../scripts/resolve-andalucia-linear-rational-and-faces.mjs';
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),rows=()=>buildAreaResourceBatch('area-resource-test').batch.records,close=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
for(const c of cases.filter(c=>c.constraints)){
 test(`${c.index} resources: exhaustive independent integer enumeration proves the unique maximum and rejects three distractors`,()=>{const found=[];let best=-Infinity;for(let x=0;x<=c.domain.x[1];x++)for(let y=0;y<=c.domain.y[1];y++){if(!c.constraints.every(([a,b,k])=>a*x+b*y<=k))continue;const z=c.objective[0]*x+c.objective[1]*y;if(z>best){best=z;found.length=0;found.push([x,y]);}else if(z===best)found.push([x,y]);}assert.equal(best,c.maximum);assert.deepEqual(found,[c.optimum]);const profits=c.wrong.map(([x,y])=>c.objective[0]*x+c.objective[1]*y);assert.equal(new Set(profits).size,3);profits.forEach(z=>assert.notEqual(z,best));c.wrong.forEach(p=>assert.ok(!feasible(p,c.constraints)||c.objective[0]*p[0]+c.objective[1]*p[1]<best));});
 test(`${c.index} nonnegative dual coefficients certify the continuous bound; all region vertices satisfy every inequality`,()=>{const[u,v]=c.dual,[a,b]=c.constraints;assert.ok(u>0&&v>0);close(u*a[0]+v*b[0],c.objective[0]);close(u*a[1]+v*b[1],c.objective[1]);close(u*a[2]+v*b[2],c.maximum);const r=rows().find(r=>r.correctionEvidence.parameters.index===c.index),p=r.parts[0];for(const point of p.verification.numericalEvidence.points)assert.ok(feasible(point,c.constraints));const svg=renderRationalGraph(p.visual);assert.doesNotMatch(svg,/undefined|NaN/);assert.match(svg,/<polygon/);assert.equal(svg,renderRationalGraph(p.visual));assert.ok(p.solutionSteps.length>=10);});
}
test('153 intersections, graph and positive area verified by numerical Simpson quadrature',()=>{const f=x=>(x-1)**2,g=x=>5-2*x;for(const[x,y]of[[-2,9],[2,1]]){close(f(x),y);close(g(x),y);}for(let k=1;k<400;k++)assert.ok(g(-2+k/100)>f(-2+k/100));let s=0;const n=1000,h=4/n;for(let k=0;k<=n;k++){const x=-2+k*h;s+=(k===0||k===n?1:k%2?4:2)*(g(x)-f(x));}close(s*h/3,32/3);const svg=renderGreenhouseGraph(greenhouseGraph);assert.match(svg,/<polygon/);assert.doesNotMatch(svg,/NaN|undefined/);assert.equal(svg,renderGreenhouseGraph(greenhouseGraph));assert.throws(()=>renderGreenhouseGraph({...greenhouseGraph,index:154}));});
test('153 discarded fraction refers to purchased area, not damaged area; all wrong costs fail material balance',()=>{const p=rows().find(r=>r.correctionEvidence.parameters.index===153).parts[1].verification.numericalEvidence;close(p.purchased*(1-1/3),p.area);close(p.purchased*p.price,p.cost);assert.equal(new Set(p.wrongCosts).size,3);for(let i=0;i<3;i++){close(p.wrongPurchased[i]*p.price,p.wrongCosts[i]);assert.ok(Math.abs(p.wrongPurchased[i]*2/3-p.area)>1);}close((p.area+p.area/3)*p.price,640/3);});
test('four official sources and five original response units; PDF-bound source edits reverse exactly',()=>{const rr=rows();assert.equal(rr.length,4);assert.equal(rr.reduce((s,r)=>s+r.parts.length,0),5);for(const r of rr){const i=r.correctionEvidence.parameters.index,o=areaResourceObservations.find(o=>o[0]===i);assert.equal(sha(fs.readFileSync(r.officialSource.path)),o[1]);assert.equal(sha(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${i}.png`)),o[4]);let t=r.sourceLiteral;const edits=[];for(const[b,a]of areaResourceReplacements({...r,queueIndex:i})){const at=t.indexOf(b);assert.ok(at>=0);edits.push({at,b,a});t=t.slice(0,at)+a+t.slice(at+b.length);}assert.doesNotMatch(t,/\u001c|¾|BLOQUE B|undefined/);for(const e of edits.reverse())t=t.slice(0,e.at)+e.b+t.slice(e.at+e.a.length);assert.equal(t,r.sourceLiteral);for(const p of r.parts){assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.answer,p.finalAnswer);assert.ok(p.solutionSteps.length>=6);}}});
test('area/resource output deterministic, invariant to order, and preserves runtime and immutable queue',()=>{const paths=['data/andalucia-pau-runtime.js','math-renderer.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=paths.map(p=>sha(fs.readFileSync(p))),sort=r=>r.sort((a,b)=>a.exerciseId.localeCompare(b.exerciseId));assert.deepEqual(rows(),rows());assert.deepEqual(sort(rows()),sort(buildAreaResourceBatch('area-resource-test',[...cases].reverse()).batch.records));assert.deepEqual(paths.map(p=>sha(fs.readFileSync(p))),before);});
