import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {observations,cases,proof,statements,buildBisectorCylinderWindowBatch} from '../scripts/resolve-andalucia-mates-bisector-cylinder-window.mjs';
const near=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],det=A=>dot(A[0],cross(A[1],A[2])),sub=(a,b)=>a.map((x,i)=>x-b[i]);
const der=(f,x,h=1e-5)=>(f(x+h)-f(x-h))/(2*h);
function rank(input){const a=input.map(r=>[...r]);let i=0;for(let j=0;j<a[0].length&&i<a.length;j++){let k=i;while(k<a.length&&Math.abs(a[k][j])<1e-8)k++;if(k===a.length)continue;[a[i],a[k]]=[a[k],a[i]];const p=a[i][j];a[i]=a[i].map(x=>x/p);for(k=0;k<a.length;k++)if(k!==i){const f=a[k][j];a[k]=a[k].map((x,q)=>x-f*a[i][q]);}i++;}return i;}
test('seven PDF and page-image hashes bind the source; correction criteria are not substituted for an exercise',()=>{const rows=p=>fs.readFileSync(p,'utf8').trim().split(/\r?\n/).map(JSON.parse),q=rows('artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'),canon=new Map(rows('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl').map(r=>[r.exerciseId,r])),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');for(const o of observations){const e=canon.get(q[o[0]].exerciseId);assert.equal(hash(e.provenance.localPath),o[1]);assert.equal(e.sourceRange.page,o[2]);assert.equal(hash(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`),o[4]);}assert.ok(!cases.some(c=>c.index===636));assert.match(statements[637],/frac\{x−1\}\{3\}=frac\{y\}\{2\}/);assert.match(statements[642],/frac\{2x²\}/);});
test('633 coplanarity and perpendicular plane uniquely select the correct options',()=>{const A=[1,1,1],B=[-1,2,0],C=[2,1,2],AB=sub(B,A),AC=sub(C,A),n=cross(AB,AC);assert.deepEqual(n,[1,1,-1]);assert.deepEqual([5,-5,3,1].map(t=>det([AB,AC,sub([t,-2,2],A)])===0),[true,false,false,false]);const planes=[[2,-1,1,-5],[2,-1,1,5],[2,1,1,-7],[2,-1,-1,-1]];assert.deepEqual(planes.map(p=>dot(p.slice(0,3),C)+p[3]===0&&cross(p.slice(0,3),AB).every(x=>x===0)),[true,false,false,false]);});
const sys=k=>({A:[[1,1,k],[2,k,0],[0,1,2]],b:[1,1,k]}),satisfies=(s,v)=>s.A.every((r,i)=>Math.abs(dot(r,v)-s.b[i])<1e-9);
test('635 ranks verified by elimination, not a singular-determinant shortcut',()=>{for(const k of[-4,-1,0,1,2,3]){const s=sys(k);near(det(s.A),4*(k-1));assert.deepEqual([rank(s.A),rank(s.A.map((r,i)=>[...r,s.b[i]]))],k===1?[2,2]:[3,3]);}const options=[k=>k===1?'SCI':'SCD',k=>k===1?'SI':'SCD',k=>k===-1?'SCI':'SCD',k=>[1,-1].includes(k)?'SCI':'SCD'];assert.deepEqual(options.map(f=>[-2,-1,0,1,2].every(k=>{const s=sys(k),a=rank(s.A),b=rank(s.A.map((r,i)=>[...r,s.b[i]]));return f(k)===(a<b?'SI':a===3?'SCD':'SCI');})),[true,false,false,false]);});
test('635 both parameter specializations and every numeric distractor checked by substitution',()=>{const fns=[t=>[t,1-2*t,t],t=>[t,1+2*t,t],t=>[t,1-2*t,-t]];assert.deepEqual(fns.map(f=>[-2,0,1,3].every(t=>satisfies(sys(1),f(t)))),[true,false,false]);assert.ok(satisfies(sys(1),[1,-1,1])&&satisfies(sys(1),[0,1,0]));assert.notDeepEqual(fns[0](1),fns[0](0));assert.deepEqual([[.5,0,-.5],[.5,0,.5],[-.5,0,.5],[0,1,-1]].map(v=>satisfies(sys(-1),v)),[true,false,false,false]);});
test('637 equal distances use full plane normals and correct continuous-line denominators',()=>{const p=proof({index:637}),n=cross([1,1,0],[-3,0,1]);assert.deepEqual(n,[1,-1,3]);near(dot(n,[-4,1,0])+5,0);const points=[p.point,[17/8,3/4,-5/8],[-5/4,-3/2,-7/4],[1,0,-1]],distance=(v,d)=>Math.abs(dot(n,v)+d)/Math.hypot(...n);assert.deepEqual(points.map(v=>{const t=v[2]+1;return v.every((x,i)=>Math.abs(x-p.rPoint[i]-t*p.rDirection[i])<1e-9)&&Math.abs(distance(v,2)-distance(v,5))<1e-9;}),[true,false,false,false]);near(distance(p.point,2),3/(2*Math.sqrt(11)));});
test('638 skew lines and plane uniquely checked by vector products and original equations',()=>{const p=proof({index:638});assert.deepEqual(cross(p.d,p.e),p.cross);near(dot(sub(p.Q,p.P),p.cross),26);assert.equal(rank([p.d,p.e,sub(p.Q,p.P)]),3);for(const t of[-2,0,3]){const v=p.Q.map((x,i)=>x+t*p.e[i]);near(v[0]-v[1]-3,0);near(3*v[1]-v[2]+6,0);}const planes=[p.plane,[6,-9,1,-2],[6,9,1,20],[6,-9,-1,4]];assert.deepEqual(planes.map(a=>dot(a.slice(0,3),p.P)+a[3]===0&&dot(a.slice(0,3),p.d)===0&&dot(a.slice(0,3),p.e)===0),[true,false,false,false]);});
test('642 rational function asymptotes and derivative independently evaluated',()=>{const f=x=>2*x*x/((x+1)*(x-2)),df=x=>-2*x*(x+4)/((x+1)*(x-2))**2;for(const x of[-7,-3,-.5,.5,3,8])near(der(f,x),df(x),1e-6);near(f(1e7),2,1e-6);near(f(-1e7),2,1e-6);assert.ok(f(-1-1e-7)>1e6&&f(-1+1e-7)<-1e6&&f(2-1e-7)<-1e6&&f(2+1e-7)>1e6);near(f(-4),16/9);near(f(0),0);assert.deepEqual([-5,-2,-.5,1,3].map(x=>Math.sign(df(x))),[-1,1,1,-1,-1]);const descriptions=[{v:[-1,2],h:2,o:null},{v:[-1,2],h:1,o:null},{v:[2],h:2,o:null},{v:[-1,2],h:null,o:2}];assert.deepEqual(descriptions.map(x=>x.v.length===2&&x.v.includes(-1)&&x.v.includes(2)&&Math.abs(f(1e7)-x.h)<1e-6&&x.o===null),[true,false,false,false]);assert.deepEqual([-2,2,0].map(x=>Number.isFinite(f(x))&&Math.abs(f(x)-2)<1e-9),[true,false,false]);});
test('642 monotonicity descriptions retain domain gaps; invalid ranges cannot be equivalent',()=>{const ranges=[{up:[[-4,-1],[-1,0]],down:[[-Infinity,-4],[0,2],[2,Infinity]]},{up:[[-Infinity,-4],[0,2],[2,Infinity]],down:[[-4,-1],[-1,0]]},{up:[[-4,0]],down:[[-Infinity,-4],[0,Infinity]]},{up:[[0,2],[2,Infinity]],down:[[-Infinity,-1],[-1,0]]}];const df=x=>-2*x*(x+4)/((x+1)*(x-2))**2;const good=(r,sign)=>r.every(([a,b])=>![-1,2].some(x=>a<x&&x<b)&&[.2,.5,.8].every(t=>{const x=Number.isFinite(a)&&Number.isFinite(b)?a+(b-a)*t:!Number.isFinite(a)?b-1/(1-t):a+1/(1-t);return Math.sign(df(x))===sign;}));assert.deepEqual(ranges.map(r=>good(r.up,1)&&good(r.down,-1)),[true,false,false,false]);});
test('646 closed-cylinder constraint, global optimum and distinct distractors verified independently',()=>{const p=proof({index:646}),surface=(r,h)=>2*Math.PI*r*(r+h),V=r=>27*r-Math.PI*r**3,rmax=Math.sqrt(27/Math.PI);near(surface(p.radius,p.height),54);near(der(V,p.radius),0,1e-7);near(Math.PI*p.radius**2*p.height,p.volume);for(let i=1;i<100;i++)assert.ok(V(rmax*i/100)<=p.volume+1e-8);const v=[[p.radius,p.height],[3/Math.sqrt(2*Math.PI),6/Math.sqrt(2*Math.PI)],[3*Math.sqrt(2/Math.PI),3*Math.sqrt(2/Math.PI)],[3/Math.sqrt(Math.PI),3/Math.sqrt(Math.PI)]];assert.deepEqual(v.map(([r,h])=>Math.abs(surface(r,h)-54)<1e-8&&Math.abs(h-2*r)<1e-8),[true,false,false,false]);assert.equal(new Set(v.map(x=>x.join(','))).size,4);});
test('655 window includes lower side, both jambs and semicircle arc; global area maximum verified',()=>{const p=proof({index:655}),h=r=>4-(2+Math.PI)*r/2,area=r=>2*r*h(r)+Math.PI*r*r/2;near(2*p.rectangleHeight+(2+Math.PI)*p.radius,8);near(p.rectangleHeight,h(p.radius));near(der(area,p.radius),0,1e-7);near(p.width,2*p.radius);near(p.totalHeight,p.rectangleHeight+p.radius);const rmax=8/(2+Math.PI);for(let i=1;i<100;i++)assert.ok(area(rmax*i/100)<=area(p.radius)+1e-8);const den=[4+Math.PI,2+Math.PI,4+2*Math.PI,8+Math.PI];assert.deepEqual(den.map(d=>Math.abs((4+Math.PI)*8/d-8)<1e-8),[true,false,false,false]);assert.equal(new Set(den).size,4);});
test('seven source-bound exercises and thirteen tasks with three wrong options each reproduce in reverse order',()=>{const a=buildBisectorCylinderWindowBatch('test').batch,b=buildBisectorCylinderWindowBatch('test',[...cases].reverse()).batch;assert.equal(a.records.length,7);assert.equal(a.records.flatMap(x=>x.parts).length,13);assert.deepEqual(a.records,[...b.records].reverse());for(const r of a.records){assert.equal(r.qualityGates.rendering,'RECHECK_REQUIRED');assert.equal(r.qualityGates.publication,'NOT_ENABLED');for(const p of r.parts){assert.ok(p.partId);assert.equal(p.answer,p.finalAnswer);assert.equal(p.solutionSteps.length,6);assert.equal(p.distractors.length,3);assert.equal(p.distractorEvidence.length,3);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.ok(!/[\[(]\s*\d+(?:[.,’']\d+)?\s*puntos?\s*[\])]/i.test(p.prompt));}}});
