import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,buildRemainingMatrixBatch} from '../scripts/resolve-andalucia-matrix-official-remaining.mjs';
const mul=(A,B)=>A.map(r=>B[0].map((_,j)=>r.reduce((s,x,k)=>s+x*B[k][j],0))),add=(A,B,k=1)=>A.map((r,i)=>r.map((x,j)=>x+k*B[i][j])),sc=(A,k)=>A.map(r=>r.map(x=>x*k));
const eq=(A,B)=>A.length===B.length&&A.every((r,i)=>r.length===B[i].length&&r.every((x,j)=>Math.abs(x-B[i][j])<1e-8)),I=n=>Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>+(i===j)));
const determinant=A=>A.length===1?A[0][0]:A[0].reduce((s,x,j)=>s+(-1)**j*x*determinant(A.slice(1).map(r=>r.filter((_,k)=>k!==j))),0);
const rows=()=>buildRemainingMatrixBatch('remaining-matrix-test').batch.records,c=i=>cases.find(x=>x.index===i),at=(r,i,p)=>r.find(x=>x.correctionEvidence.parameters.index===i).parts[p].verification.numericalEvidence;
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function reject(e,check){assert.ok(check(e.value));for(const w of e.wrong)assert.equal(check(w),false);const all=[e.value,...e.wrong];for(let a=0;a<4;a++)for(let b=0;b<a;b++)assert.equal(eq(all[a],all[b]),false);}
test('official 480: both parameter determinants and all two-sided matrix options independently checked',()=>{const r=rows(),z=c(480),e=at(r,480,1);for(const a of [-3,0,.5,1,2,4]){const dA=determinant([[a,1,0],[0,a,2],[0,1,1]]),dB=determinant([[2,-1],[a,-1]]);assert.equal(dA,a*(a-2)+0);assert.equal(dB,a-2);assert.equal(dA!==0&&dB!==0,![0,2].includes(a));}reject(e,X=>eq(mul(mul(z.A,X),z.B),z.C));assert.deepEqual(e.value,[[-3,5],[4,-5],[-2,3]]);});
test('official 604: four vertices fix k uniquely and matrix residual rejects all distractors',()=>{const r=rows(),p=at(r,604,0),e=at(r,604,1),z=c(604),values=p.vertices.map(([x,y])=>2*x+3*y);assert.deepEqual(values,p.baseValues);assert.equal(Math.max(...values)+p.k,19);assert.equal(Math.min(...values)+p.k,6);assert.equal(values.indexOf(Math.max(...values)),2);assert.equal(values.indexOf(Math.min(...values)),0);reject(e,X=>eq(add(mul(z.B,z.A),sc(X,2)),z.C));});
test('official 628: fourth power equation verified directly without using rearranged formula',()=>{const r=rows(),e=at(r,628,0),A=c(628).A,A2=mul(A,A),A4=mul(A2,A2);assert.equal(determinant(A),-9);reject(e,X=>eq(add(mul(A2,X),A4),A));assert.ok(eq(sc(e.value,9),[[-8,2,-40],[40,-10,2],[38,40,-8]]));});
test('official 766: each ingredient, recipe, supplier, transport and profit checked in integer cents',()=>{const e=at(rows(),766,0),pricesCents=[[50,40,60],[40,50,70]],production=[11,9],transport=[2,3];let raw=0,prod=0,trans=0,profit=0,total=0;for(let i=0;i<2;i++)for(let j=0;j<2;j++){const ingredients=e.Q[i].reduce((s,g,k)=>s+g*pricesCents[j][k]/1000,0);assert.ok(Math.abs(ingredients/100-e.raw[i][j])<1e-12);const unit=ingredients+production[i]+transport[j]+5,n=e.orders[i][j];assert.ok(Math.abs(unit/100-e.unit[i][j])<1e-12);raw+=ingredients*n;prod+=production[i]*n;trans+=transport[j]*n;profit+=5*n;total+=unit*n;}assert.deepEqual([raw,prod,trans,profit,total],[1101000,220000,55000,110000,1486000]);assert.ok(Math.abs(e.total-total/100)<1e-8);assert.deepEqual(e.wrong,[(total-profit)/100,(total-trans)/100,(total-prod)/100]);assert.equal(new Set([total/100,...e.wrong]).size,4);});
test('official 768: official activities, brackets and all wrong payment rules checked separately',()=>{const r=rows(),e=at(r,768,0),gross=e.Q.map(row=>row[0]*75+row[1]*300+row[2]*250),net=gross.map(v=>v-(v<10000?v*.15:v*.18));assert.deepEqual(gross,[7250,12500,17500]);assert.deepEqual(net,[6162.5,10250,14350]);assert.ok(eq(e.net.map(x=>[x]),net.map(x=>[x])));for(const w of e.wrong)assert.ok(w.some((v,i)=>Math.abs(v-net[i])>1e-8));assert.equal(new Set([net,...e.wrong].map(JSON.stringify)).size,4);for(const a of [-2,0,.8,1,4])assert.ok(Math.abs(determinant([[-2,2,1],[3,a-1,2],[4,0,3]])-(8-10*a))<1e-10);assert.equal(at(r,768,1).excluded,.8);});
test('official 822: real products confirm dimensions; inverse and singularity independently proved',()=>{const r=rows(),e=at(r,822,1),z=c(822),CT=[z.C.map(x=>x[0])],scalar=mul(mul(CT,z.A),z.C),square=mul(mul(mul(z.A,z.C),CT),z.B);assert.deepEqual([scalar.length,scalar[0].length],[1,1]);assert.deepEqual([square.length,square[0].length],[3,3]);assert.equal(determinant(z.A),17);assert.equal(determinant(z.B),0);assert.deepEqual(z.B[0].map((v,j)=>2*v+z.B[1][j]),z.B[2]);assert.ok(eq(mul(z.A,e.inverseA),I(3)));assert.ok(eq(mul(e.inverseA,z.A),I(3)));for(const w of e.wrongInverseA)assert.equal(eq(mul(z.A,w),I(3)),false);});
test('official 822: both matrix equations reject every competing ordered pair',()=>{const e=at(rows(),822,2),valid=([X,Y])=>eq(add(sc(X,2),sc(Y,3)),e.A)&&eq(add(sc(X,-3),sc(Y,4)),e.B);assert.ok(valid([e.X,e.Y]));for(const w of e.wrong)assert.equal(valid(w),false);assert.deepEqual(e.X,[[1,-2,3],[2,0,-1],[0,0,1]]);assert.deepEqual(e.Y,[[1,-1,0],[1,0,2],[0,1,-1]]);});
test('official 962: three price equations have unique positive solution and reject distractors',()=>{const e=at(rows(),962,0),valid=p=>eq(mul(e.S,p.map(x=>[x])),e.v);assert.ok(valid(e.prices));assert.notEqual(determinant(e.S),0);assert.ok(e.prices.every(x=>x>0));for(const w of e.wrong)assert.equal(valid(w),false);assert.equal(new Set([e.prices,...e.wrong].map(JSON.stringify)).size,4);});
test('official 962: rank two drops to one, certified by row dependencies and nonzero minors',()=>{const e=at(rows(),962,1);assert.deepEqual(e.A[0].map((v,j)=>2*v+e.A[1][j]),e.A[2]);assert.equal(determinant(e.A),0);assert.equal(determinant(e.A.slice(0,2).map(r=>r.slice(0,2))),2);assert.deepEqual(mul(e.A,e.A),e.A2);assert.deepEqual(e.A2[0].map(x=>-5*x+0),e.A2[1]);assert.deepEqual(e.A2[0].map(x=>-3*x+0),e.A2[2]);assert.ok(e.A2[0].some(x=>x!==0));assert.deepEqual(e.ranks,[2,1]);});
test('seven whole official exercises, thirteen parts and thirty-nine distinct distractors retain hashes and full steps',()=>{const r=rows();assert.equal(r.length,7);assert.equal(r.reduce((n,x)=>n+x.parts.length,0),13);for(const x of r){assert.equal(sha(x.officialSource.path),x.officialSource.documentHash);assert.equal(x.examSlot,1);for(const p of x.parts){assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.distractorEvidence.length,3);assert.ok(p.solutionSteps.length>=6);}}});
test('remaining matrices repeat exactly, tolerate reversed input order and do not mutate sources or runtime',()=>{const paths=['data/andalucia-pau-runtime.js','math-renderer.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=paths.map(sha),sort=r=>r.sort((a,b)=>a.exerciseId.localeCompare(b.exerciseId));assert.deepEqual(rows(),rows());assert.deepEqual(sort(rows()),sort(buildRemainingMatrixBatch('remaining-matrix-test',[...cases].reverse()).batch.records));assert.deepEqual(paths.map(sha),before);});
