import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,observations,statements,coefficients,independent,proof,solve,buildRanksBatch} from '../scripts/resolve-andalucia-mates-ranks-determinants.mjs';
import {rank} from '../scripts/resolve-andalucia-mates-parameter-systems.mjs';import {det3} from '../scripts/resolve-andalucia-mates-determinants-integrals.mjs';import {multiply} from '../scripts/resolve-andalucia-mates-inverse-normal-geometry.mjs';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
test('rank/determinant official page and source hashes retained',()=>{const all=fs.readFileSync('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl','utf8').trim().split(/\r?\n/).map(JSON.parse);for(const [i,h,p,q,img]of observations){assert.equal(sha(fs.readFileSync(all.find(x=>x.documentHash===h).provenance.localPath)),h);assert.equal(sha(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${i}.png`)),img);assert.ok(p>0&&q&&statements[i]);}});
test('system determinant and both singular rank classifications independently verified',()=>{for(let n=-100;n<=100;n++){const k=n/7;close(det3(coefficients(k)),k*(k-2));if(k!==0&&k!==2)assert.equal(rank(coefficients(k)),3);}assert.deepEqual(proof(cases[0]).singular,[{k:0,rankA:2,rankAugmented:3},{k:2,rankA:2,rankAugmented:2}]);const a=coefficients(0).map((r,i)=>[...r,independent(0)[i]]),contradiction=a[2].map((x,i)=>x-a[0][i]+3*a[1][i]);assert.deepEqual(contradiction,[0,0,0,8]);});
test('parameter family satisfies all three original equations; every distractor fails',()=>{const p=proof(cases[0]),A=coefficients(2),b=independent(2),image=x=>A.map(row=>row.reduce((s,a,i)=>s+a*x[i],0));for(let n=-100;n<=100;n++){const t=n/7,x=p.particular.map((v,i)=>v+t*p.direction[i]);image(x).forEach((v,i)=>close(v,b[i]));}for(const x of p.wrongParticulars)assert.ok(image(x).some((v,i)=>Math.abs(v-b[i])>1e-8));assert.match(solve(cases[0])[0].solutionSteps.map(s=>s.math).join(' '),/rg\(A\|b\)=3/);});
test('all determinant identities checked on varied non-diagonal order-three examples',()=>{for(let k=-20;k<=20;k++){const M=[[1,k,0],[0,1,k],[0,0,2]],Mt=M[0].map((_,j)=>M.map(r=>r[j])),inverse=[[1,-k,k*k/2],[0,1,-k/2],[0,0,.5]],swapped=[M[1],M[0],M[2]];close(det3(M),2);assert.equal(rank(multiply(multiply(M,M),M)),3);close(det3(Mt.map(r=>r.map(x=>2*x))),16);close(det3(multiply(inverse,inverse)),.25);close(det3(swapped),-2);multiply(M,inverse).forEach((r,i)=>r.forEach((v,j)=>close(v,i===j?1:0)));}const p=proof(cases[1]);for(const [i,v]of[3,16,.25,-2].entries()){assert.ok(p.wrong[i].every(x=>x!==v));assert.equal(new Set(p.wrong[i]).size,3);}});
test('rank/determinant batch has six full official parts and deterministic reconstruction',()=>{const a=buildRanksBatch('test'),b=buildRanksBatch('test',[...cases].reverse()),sort=r=>r.batch.records.toSorted((x,y)=>x.exerciseId.localeCompare(y.exerciseId));assert.deepEqual(sort(a),sort(b));assert.equal(a.batch.records.reduce((s,r)=>s+r.parts.length,0),6);for(const r of a.batch.records){assert.equal(r.subject,'Matemáticas II');assert.equal(r.examSlot,1);assert.equal(r.matesEvidence.documentHash,r.officialSource.documentHash);for(const p of r.parts){assert.equal(p.answer,p.finalAnswer);assert.ok(p.solutionSteps.length>=5);assert.equal(new Set([p.answer,...p.distractors]).size,4);}}});
