import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,buildRecoveredBranchBatch} from '../scripts/resolve-andalucia-probability-pdf-recovered-branches.mjs';
import {sourceProjection,restoreText} from '../scripts/project-andalucia-inference-source-glyphs.mjs';
import {parameterReplacements} from '../scripts/andalucia-probability-pdf-parameter-evidence.mjs';
const records=buildRecoveredBranchBatch().batch.records,at=i=>records.find(r=>r.correctionEvidence.parameters.index===i);
const number=s=>{const m=s.match(/^frac\{(-?\d+)\}\{(\d+)\}$/);return m?+m[1]/+m[2]:Number(s);};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-12,`${a} != ${b}`);
function check(i,expected){const ps=at(i).parts;assert.equal(ps.length,expected.length);for(const[j,e]of expected.entries()){const p=ps[j],xs=[p.answer,...p.distractors].map(number);near(xs[0],e);assert.equal(xs.filter(x=>Math.abs(x-e)<1e-12).length,1);assert.equal(new Set(xs.map(x=>x.toFixed(12))).size,4);assert.ok(xs.every(x=>Number.isFinite(x)&&x>=0&&x<=1));assert.equal(p.answer,p.finalAnswer);assert.ok(p.solutionSteps.length>=6);}}
test('eight PDF-recovered exercises, twenty-five official subparts and seventy-five distractors',()=>{assert.equal(records.length,8);assert.equal(records.flatMap(r=>r.parts).length,25);assert.equal(records.flatMap(r=>r.parts.flatMap(p=>p.distractors)).length,75);});
test('truck total, Bayesian denominator and three-stage rain probability',()=>{const incident=.3*.02+.2*.01+.5*.05;check(55,[1-incident,.5*.05/incident,.3*.02*.4]);});
test('processor classified proportions independently recover discarded and retained rates',()=>{const d=.6*.2+.3*.5+.1*.6;check(67,[.6*.2+.3*.5,d,.1*.4/(1-d)]);});
test('spam false-positive rate is six per thousand, not sixty percent',()=>{const a=.2*.4,b=.2*.6,c=.8*.006,d=.8*.994;check(127,[a/(a+c),d/(b+d),b+c]);near(a+b+c+d,1);});
test('enumerating all physical chip pairs without replacement verifies three prizes',()=>{const balls=['V','V','V','A','A','R','R','R','R'],pairs=[];for(let i=0;i<9;i++)for(let j=0;j<9;j++)if(i!==j)pairs.push([balls[i],balls[j]]);const first=p=>p.every(x=>x==='A'),second=p=>p.every(x=>x==='V'),third=p=>(p[0]==='A')!==(p[1]==='A');const thirdCount=pairs.filter(third).length,win=pairs.filter(p=>first(p)||second(p)||third(p)).length;check(244,[pairs.filter(p=>first(p)||second(p)).length/72,thirdCount/72,thirdCount/win]);});
test('dance 32 percent is a joint probability and master is conditional on A classical',()=>{const ac=.2*.7,bc=.32,am=.2-ac,bm=.8-bc;check(453,[ac+bc,bm/.8,bm/(am+bm),ac*.8]);});
test('mobile and games reconstruct four mutually exclusive regions without assuming independence',()=>{const union=.8,both=.45,v=1-.4,m=union-v+both;check(810,[m-both,(v-both)/(1-m),union-both,1-union]);assert.notEqual(m*v,both);});
test('ski rates complement not-ski source rates and use unequal bus weights',()=>{const a=4/9*.35,b=1/3*.6,c=2/9,total=a+b+c;check(1157,[total,c/total,a+c]);});
test('export inverse mixture solution is checked by substitution',()=>{const x=(.37-.25)/(.4-.25);near(.4*x+.25*(1-x),.37);check(1432,[x,x*.6/(1-.37)]);});
test('official PDF parameters have matched anchors, reversible source ledger and source hashes',()=>{for(const c of cases){const r={...at(c.index),queueIndex:c.index},p=sourceProjection(r);assert.equal(restoreText(p.text,p.changes),r.sourceLiteral);assert.equal(p.changes.length,parameterReplacements[c.index].length);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(r.officialSource.path)).digest('hex'),r.officialSource.documentHash);assert.ok(p.evidence.pngHash||p.evidence.pngSha256);assert.ok(c.cells.every(x=>x[2]>=0));assert.equal(c.cells.reduce((s,x)=>s+x[2],0),c.scale);}
 const text=i=>sourceProjection({...at(i),queueIndex:i}).text;assert.match(text(127),/0\.6 %/);assert.match(text(55),/camión de tipo C si/);assert.match(text(453),/escuela B y practican/);assert.match(text(1157),/65 %/);
});
test('source prompt, scores, deterministic replay and reversed input order remain unchanged',()=>{const sig=rs=>rs.map(r=>[r.exerciseId,r.sourceLiteral,r.scoreEvidence,r.parts]).sort((a,b)=>a[0].localeCompare(b[0]));assert.deepEqual(sig(records),sig(buildRecoveredBranchBatch().batch.records));assert.deepEqual(sig(records),sig(buildRecoveredBranchBatch('batch-0286',[...cases].reverse()).batch.records));});
