import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {observations,cases,solve,proof,buildCommutationReflectionBatch} from '../scripts/resolve-andalucia-mates-commutation-reflection.mjs';
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),sub=(a,b)=>a.map((x,i)=>x-b[i]),d=(f,x)=>(f(x+1e-5)-f(x-1e-5))/2e-5;
test('commutation-reflection source pages keep their inspected hashes',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);});
test('two and only two commuting real matrices satisfy trace and determinant; options rejected independently',()=>{const mul=(a,b)=>a.map(row=>b[0].map((_,j)=>row.reduce((s,v,k)=>s+v*b[k][j],0))),A=[[0,-1],[1,0]],valid=X=>Math.abs(X[0][0]+X[1][1]-1)<1e-10&&Math.abs(X[0][0]*X[1][1]-X[0][1]*X[1][0]-1)<1e-10&&mul(A,X).every((r,i)=>r.every((v,j)=>Math.abs(v-mul(X,A)[i][j])<1e-10));for(const sign of[-1,1]){const b=sign*Math.sqrt(3)/2;assert.deepEqual([[[.5,b],[-b,.5]],[[.5,b],[b,.5]],[[1,b],[-b,1]],[[.5,sign*.5],[-sign*.5,.5]]].map(valid),[true,false,false,false]);}near(proof({index:321}).bSquared,.75);});
test('plane contains every r point, is parallel to s and excludes its points; three false planes rejected',()=>{const p=proof({index:322}),valid=([n,k])=>Math.abs(dot(n,p.rPoint)-k)<1e-10&&dot(n,p.rDirection)===0&&dot(n,p.sDirection)===0;assert.deepEqual([[[ -1,1,1],0],[[1,1,1],4],[[-1,1,1],1],[[-1,1,-1],-6]].map(valid),[true,false,false,false]);for(const t of[-5,0,1,3]){near(dot(p.normal,p.rPoint.map((x,i)=>x+t*p.rDirection[i])),0);near(dot(p.normal,p.sPoint.map((x,i)=>x+t*p.sDirection[i])),1);}assert.equal(dot(p.rDirection,p.sDirection),6);assert.notDeepEqual(p.rDirection,p.sDirection);});
test('double primitive satisfies differential data and initial conditions independently',()=>{const f=x=>(x+1)*Math.log(x+1)-x+1;for(const x of[-.7,-.1,0,.5,2,4]){near(d(f,x),Math.log(x+1));near(d(t=>Math.log(t+1),x),1/(x+1));}near(f(0),1);near(d(f,0),0);const opts=[f,x=>(x+1)*Math.log(x+1)+1,x=>(x+1)*Math.log(x+1)-x,x=>Math.log(x+1)+1];assert.deepEqual(opts.map(g=>Math.abs(g(0)-1)<1e-8&&Math.abs(d(g,0))<1e-6&&Math.abs(d(g,.5)-Math.log(1.5))<1e-6),[true,false,false,false]);});
test('reflection is independently verified by equal distances and perpendicular midpoint; all false points fail',()=>{const A=[2,-4,-3],B=[1,1,2],C=[0,1/3,1],D=[-3,0,3],n=[-1,3,-1];[B,C,D].forEach(P=>near(dot(n,P),0));const valid=Q=>{const H=Q.map((x,i)=>(x+A[i])/2),v=sub(Q,A),cross=[v[1]*n[2]-v[2]*n[1],v[2]*n[0]-v[0]*n[2],v[0]*n[1]-v[1]*n[0]];return Math.abs(dot(n,H))<1e-10&&cross.every(x=>Math.abs(x)<1e-10);};assert.deepEqual([[0,2,-5],[1,-1,-4],[4,-10,-1],[-2,8,-7]].map(valid),[true,false,false,false]);const p=proof({index:329});near(dot(sub(A,p.foot),sub(A,p.foot)),11);near(dot(sub(p.reflection,p.foot),sub(p.reflection,p.foot)),11);});
test('five pedagogical parts, one correct and three distinct choices, stable reversal without enabling',()=>{const parts=cases.flatMap(solve);assert.equal(parts.length,5);for(const p of parts){assert.ok(p.partId);assert.equal(p.solutionSteps.length,6);assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);}const a=buildCommutationReflectionBatch('test').batch,b=buildCommutationReflectionBatch('test',[...cases].reverse()).batch;assert.deepEqual(a.records,[...b.records].reverse());a.records.forEach(r=>assert.equal(r.qualityGates.publication,'NOT_ENABLED'));});
