import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,buildBoundedPiecewiseBatch,functions,graphSpecs,renderBoundedPiecewiseGraph} from '../scripts/resolve-andalucia-calculus-bounded-piecewise.mjs';
import {boundedPiecewiseObservations,boundedPiecewiseReplacements} from '../scripts/andalucia-calculus-bounded-piecewise-pdf-evidence.mjs';
const rows=()=>buildBoundedPiecewiseBatch('bounded-piecewise-test').batch.records,ev=(i,k)=>rows().find(r=>r.correctionEvidence.parameters.index===i).parts[k].verification.numericalEvidence;
const close=(a,b,t=1e-5)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),d=(f,x)=>(f(x+1e-5)-f(x-1e-5))/2e-5,sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function integral(f,a,b,n=40000){const h=(b-a)/n;let s=0;for(let k=0;k<n;k++)s+=h*f(a+(k+.5)*h);return s;}
test('69: official join minus two is continuous with unequal exact one-sided slopes',()=>{const f=functions[69],p=ev(69,0);assert.equal(f(-2),5);close((f(-2)-f(-2-1e-6))/1e-6,2.5);close((f(-2+1e-6)-f(-2))/1e-6,-4);assert.deepEqual(p.slopes,[2.5,-4]);for(const x of [-5,-3,0,1,3,5])close(d(f,x),x<-2?2.5:x<2?2*x:-2.5);});
test('69: tangent passes through its point and only the requested slope is valid',()=>{const f=functions[69],p=ev(69,1);assert.deepEqual(p.point,[-.5,1.25]);assert.equal(f(p.point[0]),p.point[1]);close(d(f,p.point[0]),p.slope);close(p.slope*p.point[0]+p.intercept,p.point[1]);for(const[m,b]of p.wrongLines)assert.ok(m!==p.slope||m*p.point[0]+b!==p.point[1]);assert.ok(p.outerSlopes.every(x=>x!==p.slope));});
test('69: bounded area uses both triangular tails and the central parabola',()=>{const f=functions[69],p=ev(69,2);for(const x of p.roots)assert.equal(f(x),0);for(let x=-4;x<4;x+=.01)assert.ok(f(x)>=0);assert.ok(f(-5)<0&&f(5)<0);const parts=[integral(f,-4,-2),integral(f,-2,2),integral(f,2,4)];parts.forEach((x,i)=>close(x,p.partialAreas[i],1e-8));close(parts.reduce((a,b)=>a+b),p.area,1e-8);assert.equal(p.area,58/3);for(const w of p.wrongAreas)assert.ok(Math.abs(w-p.area)>1);close(d(x=>x**3/3+x,1.3),f(1.3));});
test('77: squared branches and bounded domain give a corner only at zero',()=>{const f=functions[77],p=ev(77,0);assert.throws(()=>f(-2.01));assert.throws(()=>f(2.01));assert.equal(f(-2),1);assert.equal(f(0),1);assert.equal(f(2),1);close((f(0)-f(-1e-6))/1e-6,2);close((f(1e-6)-f(0))/1e-6,-2);assert.deepEqual(p.slopes,[2,-2]);close(d(f,-1),0);close(d(f,1),0);assert.notEqual(f(-1),2**0);});
test('77: global extrema include closed endpoints and interior maximum',()=>{const f=functions[77],p=ev(77,1);for(const[x,y]of [...p.minima,...p.maxima])assert.equal(f(x),y);assert.deepEqual(p.maxima,[[-2,1],[0,1],[2,1]]);for(let k=0;k<=1000;k++){const y=f(-2+4*k/1000);assert.ok(y>=0&&y<=1);}for(const x of [-1,1])assert.ok(f(x-.01)>f(x)&&f(x+.01)>f(x));assert.ok(f(-.01)<f(0)&&f(.01)<f(0));});
test('77: official area bounds minus one and one produce two thirds, not whole-domain area',()=>{const f=functions[77],p=ev(77,2);close(integral(f,-1,0),1/3,1e-8);close(integral(f,0,1),1/3,1e-8);close(integral(f,-1,1),p.area,1e-8);assert.equal(p.area,2/3);for(const w of p.wrongAreas)assert.ok(Math.abs(w-p.area)>.1);close(d(x=>(x+1)**3/3,-.6),f(-.6));close(d(x=>(x-1)**3/3,.6),f(.6));});
test('bounded-piecewise graphs use actual formulas, domains and area bounds',()=>{for(const s of Object.values(graphSpecs)){for(const p of s.points)close(functions[s.index](p.xy[0]),p.xy[1]);for(const p of s.pieces)for(let k=1;k<100;k++){const x=p.range[0]+(p.range[1]-p.range[0])*k/100;close(p.coefficients.reduce((n,c,i)=>n+c*x**i,0),functions[s.index](x));}const svg=renderBoundedPiecewiseGraph(s);assert.equal(svg,renderBoundedPiecewiseGraph(s));assert.doesNotMatch(svg,/undefined|NaN/);assert.match(svg,/<polygon/);assert.equal((svg.match(/<polyline /g)||[]).length,s.pieces.length);assert.throws(()=>renderBoundedPiecewiseGraph({...s,area:[0,1]}));}});
test('two official pages bind six subparts, no lost source text and four distinct options',()=>{const r=rows();assert.equal(r.length,2);assert.equal(r.reduce((n,x)=>n+x.parts.length,0),6);for(const x of r){const i=x.correctionEvidence.parameters.index,o=boundedPiecewiseObservations.find(o=>o[0]===i);assert.equal(sha(fs.readFileSync(x.officialSource.path)),o[1]);assert.equal(sha(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${i}.png`)),o[4]);let text=x.sourceLiteral;const changes=[];for(const[before,after]of boundedPiecewiseReplacements({...x,queueIndex:i})){const offset=text.indexOf(before);assert.ok(offset>=0);text=text.replace(before,after);changes.push({before,after,offset});}for(const c of changes.reverse())text=text.slice(0,c.offset)+c.before+text.slice(c.offset+c.after.length);assert.equal(text,x.sourceLiteral);for(const p of x.parts){assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.ok(p.solutionSteps.length>=5);}}});
test('bounded-piecewise batch is reproducible, order-invariant and does not mutate inputs',()=>{const paths=['data/andalucia-pau-runtime.js','math-renderer.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=paths.map(p=>sha(fs.readFileSync(p))),sort=r=>r.sort((a,b)=>a.exerciseId.localeCompare(b.exerciseId));assert.deepEqual(rows(),rows());assert.deepEqual(sort(rows()),sort(buildBoundedPiecewiseBatch('bounded-piecewise-test',[...cases].reverse()).batch.records));assert.deepEqual(paths.map(p=>sha(fs.readFileSync(p))),before);});
