import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,buildDocLinearFinalBatch} from '../scripts/resolve-andalucia-doc-linear-final-2012.mjs';import {derive} from '../scripts/resolve-andalucia-linear-quadrilaterals-official.mjs';import {feasible} from '../scripts/resolve-andalucia-linear-region-official.mjs';import {renderRationalGraph} from '../scripts/resolve-andalucia-linear-rational-and-faces.mjs';
const rows=()=>buildDocLinearFinalBatch('doc-linear-final-test').batch.records,sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9);
test('DOC39 includes negative coordinates and both exact extrema',()=>{const c=cases[0],v=derive(c);assert.deepEqual([...v.points].sort(),[[-2,-4],[-1,3],[3,-1]].sort());assert.equal(v.min,-16);assert.equal(v.max,7);for(const p of v.points)assert.ok(feasible(p,c.constraints));assert.ok(feasible([0,0],c.constraints));});
test('independent nonnegative dual certificates prove bounds over the whole regions',()=>{for(const c of cases)for(const [name,sgn,k] of [['maxDual',1,c.max],['minDual',-1,-c.min]]){if(!c[name])continue;const d=c[name];assert.ok(d.every(x=>x>=0));for(let j=0;j<2;j++)near(d.reduce((s,x,i)=>s+x*c.constraints[i][j],0),sgn*c.objective[j]);near(d.reduce((s,x,i)=>s+x*c.constraints[i][2],0),k);}});
test('DOC47 integer exhaustive search independently confirms unique production optimum',()=>{const c=cases[1];let max=-Infinity,points=[];for(let x=0;x<=250;x++)for(let y=0;y<=300;y++)if(feasible([x,y],c.constraints)){const z=30*x+50*y;if(z>max){max=z;points=[[x,y]];}else if(z===max)points.push([x,y]);}assert.equal(max,17250);assert.deepEqual(points,[[75,300]]);assert.equal(1250-(5*75+2*300),275);assert.equal(derive(c).points.length,5);});
test('each incorrect option fails source constraints or true extremum comparison',()=>{const rr=rows(),a=rr.find(r=>r.correctionEvidence.parameters.index===39),b=rr.find(r=>r.correctionEvidence.parameters.index===47);for(const vv of a.parts[0].verification.numericalEvidence.wrongVertices)assert.notDeepEqual([...vv].sort(),[...derive(cases[0]).points].sort());for(const e of a.parts[1].verification.numericalEvidence.wrongExtrema)assert.notDeepEqual(e,[7,-16]);for(const p of b.parts[0].verification.numericalEvidence.wrongPoints)assert.ok(!feasible(p,cases[1].constraints)||30*p[0]+50*p[1]<17250);});
test('real official DOCs and every subpart remain source bound; graphics preserve constraints',()=>{const rr=rows();assert.equal(rr.length,2);assert.equal(rr.reduce((s,r)=>s+r.parts.length,0),3);for(const r of rr){assert.equal(sha(r.officialSource.path),r.officialSource.documentHash);assert.equal(r.examSlot,2);for(const p of r.parts){assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.ok(p.solutionSteps.length>=7);assert.equal(p.answer,p.finalAnswer);}const svg=renderRationalGraph(r.parts[0].visual);assert.match(svg,/<polygon/);assert.doesNotMatch(svg,/NaN|undefined/);}});
test('DOC final linear batch is reproducible and order invariant without mutating runtime or sources',()=>{const paths=['data/andalucia-pau-runtime.js','math-renderer.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=paths.map(sha),sort=a=>a.sort((x,y)=>x.exerciseId.localeCompare(y.exerciseId));assert.deepEqual(rows(),rows());assert.deepEqual(sort(rows()),sort(buildDocLinearFinalBatch('doc-linear-final-test',[...cases].reverse()).batch.records));assert.deepEqual(paths.map(sha),before);});
