import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,observations,statements,proof,solve,buildMetricParametersBatch} from '../scripts/resolve-andalucia-mates-metric-parameters.mjs';
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),D=(f,x)=>(f(x+1e-5)-f(x-1e-5))/2e-5;
function integral(f,a,b,n=200000){let s=0;for(let i=0;i<n;i++)s+=f(a+(i+.5)*(b-a)/n);return s*(b-a)/n;}
test('six inspected official pages remain byte-identical and area is four thirds',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);assert.match(statements[156],/frac\{4\}\{3\}/);assert.equal(observations.find(o=>o[0]===180)[3],'A.1');});
test('plane contains the full source line and point, rejects each wrong plane',()=>{const p=proof({index:151});for(const t of [-3,-1,0,2,7])near(dot(p.normal,p.linePoint.map((x,i)=>x+t*p.lineVector[i]))+p.planeConstant,0);near(dot(p.normal,p.point)+p.planeConstant,0);for(const [n,k]of [[[ -2,7,10],41],[[2,7,10],-41],[[2,2,-1],5]])assert.ok(Math.abs(dot(n,p.point)+k)>0||Math.abs(dot(n,p.lineVector))>0);});
test('orthogonal foot and new line independently satisfy all three conditions',()=>{const p=proof({index:151});assert.deepEqual(p.linePoint.map((x,i)=>x-p.lineVector[i]),p.foot);assert.deepEqual(p.point.map((x,i)=>x+p.perpendicular[i]),p.foot);near(dot(p.lineVector,p.perpendicular),0);assert.notEqual(dot(p.lineVector,[3,2,2]),0);assert.notEqual(dot(p.lineVector,p.lineVector),0);assert.notEqual((p.point[0]-p.linePoint[0])/3,(p.point[1]-p.linePoint[1])/-2);});
test('transversal intersects r and s with the requested direction and rejects all distractors',()=>{const p=proof({index:154});assert.deepEqual(p.rPoint.map((x,i)=>x-p.direction[i]),p.sPoint);assert.ok(p.rPoint.every(x=>x===4));assert.deepEqual(p.sPoint.slice(0,2),[2,1]);assert.notEqual(3/2,2/3);for(const base of [[2,1,4],[1,1,1]]){const t=(base[1]-base[0])/(2-3),q=base.map((x,i)=>x+t*p.direction[i]);if(base[0]===2)assert.ok(q[0]!==q[2]);else{const s=(2-base[0])/2;assert.notEqual(base[1]+3*s,1);}}});
test('root area independently integrated, parameter monotonicity and distractors rejected',()=>{for(const b of [.25,.5,1,2])near(integral(x=>Math.sqrt(x)-b*x,0,1/b**2),1/(6*b**3),1e-6);near(integral(x=>Math.sqrt(x)-x/2,0,4),4/3);for(const b of [2,1/8,-.5])assert.ok(b<=0||Math.abs(1/(6*b**3)-4/3)>1);});
test('limit parameter independently verified through source evaluation and exceptional order',()=>{const p=proof({index:176}),f=(x,a)=>(Math.sin(x)-Math.log1p(x))/(a*x*x-x+Math.exp(x)-Math.cos(2*x));for(const x of [-.001,-.0001,.0001,.001])near(f(x,p.parameter),-1/7,.0002);for(const a of [1,-4,-12])assert.ok(Math.abs(f(.0001,a)+1/7)>.01);assert.ok(Math.abs(f(.0001,-2.5))>1000);});
test('trigonometric parameters meet point, horizontal tangency and distinct line intersection',()=>{const valid=([a,b,c])=>{const f=x=>a+b*Math.cos(x)+c*Math.sin(x);return Math.abs(f(Math.PI/2)-1)<1e-8&&Math.abs(D(f,Math.PI/2))<1e-8&&Math.abs(f(0)+1)<1e-8;};assert.ok(valid([-1,0,2]));for(const p of [[1,0,0],[-1,2,2],[-1,0,-2]])assert.ok(!valid(p));});
test('exponential primitive independently differentiated over real domain and tangent checked',()=>{const f=x=>(8*Math.exp(x)-4*Math.exp(2*x))/(1+Math.exp(x)),F=x=>-4*Math.exp(x)+12*Math.log1p(Math.exp(x))+4;for(const x of [-5,-2,-.5,0,.3,1,2])near(D(F,x),f(x));near(F(0),12*Math.log(2));near(D(F,0),2);for(const [s,c]of [[-4,0],[4,-4],[-4,-4]]){const G=x=>s*Math.exp(x)+12*Math.log1p(Math.exp(x))+c;assert.ok(Math.abs(G(0)-12*Math.log(2))>1||Math.abs(D(G,0)-2)>1);}});
test('seven complete parts, four unique options each and independent verification evidence',()=>{let n=0;for(const c of cases)for(const p of solve(c,statements[c.index])){n++;assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.distractorEvidence.length,3);assert.ok(p.solutionSteps.length>=6);assert.equal(p.verification.verified,true);}assert.equal(n,7);});
test('deterministic source-bound batch reverses without changing records or publishing',()=>{const a=buildMetricParametersBatch('test').batch,b=buildMetricParametersBatch('test',[...cases].reverse()).batch;assert.deepEqual(a.records,[...b.records].reverse());assert.equal(a.records.length,6);for(const r of a.records){assert.equal(r.subject,'Matemáticas II');assert.equal(r.qualityGates.publication,'NOT_ENABLED');}});
