import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {observations,statements,cases,proof,solve,matrices,parameterMatrix,buildMatrixEquationsBatch} from '../scripts/resolve-andalucia-mates-matrix-equations.mjs';
import {det3} from '../scripts/resolve-andalucia-mates-determinants-integrals.mjs';import {rank} from '../scripts/resolve-andalucia-mates-parameter-systems.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} ≠ ${b}`),mul=(a,b)=>a.map(r=>b[0].map((_,j)=>r.reduce((s,v,k)=>s+v*b[k][j],0))),add=(a,b,s=1)=>a.map((r,i)=>r.map((v,j)=>v+s*b[i][j])),scale=(a,s)=>a.map(r=>r.map(v=>s*v)),transpose=a=>a[0].map((_,j)=>a.map(r=>r[j])),I=[[1,0,0],[0,1,0],[0,0,1]],same=(a,b)=>a.every((r,i)=>r.every((v,j)=>Math.abs(v-b[i][j])<1e-7));
test('seven inspected source pages retain hashes and exact matrix rows',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);assert.match(statements[57],/\[6,1,3\]/);assert.match(statements[100],/\[8,4α,4β\]/);assert.match(statements[88],/m≥0/);});
test('rectangular matrix equation and three distractors verified in original equation',()=>{const {A,B,X}=matrices[57],bt=transpose(B),M=add(scale(I,3),A,-1);near(det3(M),1);assert.ok(same(add(scale(X,3),bt,-1),mul(A,X)));const wrong=[scale(X,-1),[[2,0],[-11,-5],[4,-1]],scale(X,3)];for(const w of wrong)assert.ok(!same(add(scale(w,3),bt,-1),mul(A,w)));});
test('shifted matrix singularities independently checked across negative and positive parameters',()=>{for(let k=-40;k<=40;k++){const l=k/4,M=add(parameterMatrix(64,l),scale(I,2),-1);near(det3(M),(l-2)*(1-l*l));assert.equal(rank(M)===3,![-1,1,2].includes(l));}assert.equal(rank(add(parameterMatrix(64,0),scale(I,2),-1)),3);});
test('inverse equation at lambda minus two rejects negative transpose and doubled solutions',()=>{const A=parameterMatrix(64,-2),X=proof({index:64}).X;assert.ok(same(mul(A,X),add(scale(X,2),I)));for(const w of [scale(X,-1),transpose(X),scale(X,2)])assert.ok(!same(mul(A,w),add(scale(w,2),I)));});
test('square root parameter matrix determinant and ranks include m between zero and one',()=>{for(let k=0;k<=200;k++){const m=k/20,A=parameterMatrix(88,m);near(det3(A),m*(m-1)**2);assert.equal(rank(A)===3,m!==0&&m!==1);}assert.equal(rank(parameterMatrix(88,0)),2);assert.equal(rank(parameterMatrix(88,1)),1);});
test('twelve times inverse verified independently with all three wrong matrices',()=>{const A=parameterMatrix(88,4),X=proof({index:88}).X;assert.ok(same(mul(A,X),scale(I,12)));for(const w of [[[5,2,2],[2,4,0],[2,0,4]],scale(X,1/12),[[5,-2,-2],[-2,0,4],[-2,4,0]]])assert.ok(!same(mul(A,w),scale(I,12)));});
test('rank and compatibility of m system verified independently by Gauss elimination',()=>{for(let k=-40;k<=40;k++){const m=k/4,A=parameterMatrix(89,m),aug=A.map((r,i)=>[...r,i<2?1:0]);near(det3(A),2*(2*m-1)*(m-1));assert.equal(rank(A),m===.5||m===1?2:3);assert.equal(rank(aug),m===1?2:3);}const A=parameterMatrix(89,1);for(let k=-25;k<=25;k++){const t=k/7;assert.ok(same(mul(A,[[-2*t],[1-t],[t]]),[[1],[1],[0]]));}for(const v of [[2,0,1],[-2,2,1],[-2,-2,1]])assert.ok(!same(mul(A,v.map(x=>[x])),[[1],[1],[0]]));});
test('matrix square cube and inverse identity independently checked',()=>{const {A,A2}=matrices[91];assert.ok(same(mul(A,A),A2));assert.ok(same(mul(A2,A),scale(I,-1)));assert.ok(same(mul(A,scale(A2,-1)),I));for(const w of [scale(A2,-1),transpose(A2),[[-1,0,1],[1,4,-4],[-1,-3,-3]]])assert.ok(!same(mul(A,A),w));});
test('fourth power equation checked in its original form including distractors',()=>{const {A,A2,B,C,X}=matrices[91],A4=mul(A2,A2),rhs=mul(A,C);assert.ok(same(add(mul(A4,X),B),rhs));assert.deepEqual(rhs,[[-5,2],[9,-3],[-7,2]]);for(const w of [[[-7,6],[0,17],[1,-13]],scale(X,-1),[[-1,-6],[12,-25],[-5,17]]])assert.ok(!same(add(mul(A4,w),B),rhs));});
test('row determinant transformation checked for independent matrices and a source-consistent instance',()=>{for(let a=-4;a<=4;a++)for(let b=-4;b<=4;b++){const A=[[a,b,1],[2,a,b],[3,4,a]],M=[scale([A[2]],-1)[0],add([A[0]],[A[1]],-1)[0],scale([A[1]],4)[0]];near(det3(M),-4*det3(A));}const A=[[2,2,1],[2,2,2],[3,4,2]],M=[[-3,-4,-2],[0,0,-1],[8,8,8]];near(det3(A),-2);near(det3(M),8);for(const wrong of [-8,-2,4])assert.notEqual(wrong,det3(M));});
test('inverse transpose product determinant checked by independently solving inverse',()=>{const A=[[2,2,1],[2,2,2],[3,4,2]]; // inverse below computed by augmented Gauss, without determinant formula shortcut
const aug=A.map((r,i)=>[...r,...I[i]]);for(let j=0;j<3;j++){let k=j;while(Math.abs(aug[k][j])<1e-9)k++;[aug[j],aug[k]]=[aug[k],aug[j]];const pivot=aug[j][j];aug[j]=aug[j].map(x=>x/pivot);for(let i=0;i<3;i++)if(i!==j){const p=aug[i][j];aug[i]=aug[i].map((x,k)=>x-p*aug[j][k]);}}const inv=aug.map(r=>r.slice(3));assert.ok(same(mul(inv,A),I));near(det3(mul(mul(inv,mul(transpose(A),transpose(A))),A)),4);for(const w of [-8,-2,.25])assert.notEqual(w,4);});
test('streaming counts and distractors verified against the original percentages and difference',()=>{const residual=([x,y,z])=>{const t=x+y+z;return[.3*x+.5*y-.2*t,.25*x+.5*y+.6*z-.5*t,y-x-100];};const p=proof({index:149});p.counts.forEach(x=>assert.ok(Number.isInteger(x)&&x>=0));residual(p.counts).forEach(x=>near(x,0));near(det3(p.coefficientMatrix),2);for(const w of [[300,200,750],[100,200,250],[300,400,150]])assert.ok(residual(w).some(x=>Math.abs(x)>1e-6));});
test('thirteen complete answers retain four distinct choices and full pedagogical steps',()=>{let n=0;for(const c of cases)for(const p of solve(c,'official unchanged')){n++;assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.ok(p.solutionSteps.length>=6);assert.equal(p.distractorEvidence.length,3);if(c.whole)assert.equal(p.prompt,'official unchanged');}assert.equal(n,13);});
test('seven source-bound records remain deterministic and invariant to input order',()=>{const a=buildMatrixEquationsBatch('test').batch,b=buildMatrixEquationsBatch('test',[...cases].reverse()).batch;assert.deepEqual(a.records,[...b.records].reverse());assert.equal(a.records.length,7);for(const r of a.records){assert.equal(r.examSlot,1);assert.equal(r.qualityGates.publication,'NOT_ENABLED');assert.equal(r.subject,'Matemáticas II');}});
