import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,buildPopulationBatch} from '../scripts/resolve-andalucia-probability-population-partitions.mjs';
const records=buildPopulationBatch().batch.records,at=i=>records.find(r=>r.correctionEvidence.parameters.index===i);
const number=s=>{const m=s.match(/^frac\{(-?\d+)\}\{(\d+)\}$/);return m?+m[1]/+m[2]:Number(s);};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-12,`${a} != ${b}`);
function check(i,expected){const ps=at(i).parts;assert.equal(ps.length,expected.length);for(const[j,e]of expected.entries()){const p=ps[j],xs=[p.answer,...p.distractors].map(number);near(xs[0],e);assert.equal(xs.filter(x=>Math.abs(x-e)<1e-12).length,1);assert.equal(new Set(xs.map(x=>x.toFixed(12))).size,4);assert.ok(xs.every(x=>Number.isFinite(x)&&x>=0&&x<=1));assert.equal(p.answer,p.finalAnswer);assert.ok(p.solutionSteps.length>=6);}}
test('eight source-bound exercises, seventeen official parts and fifty-one distractors',()=>{assert.equal(records.length,8);assert.equal(records.flatMap(r=>r.parts).length,17);assert.equal(records.flatMap(r=>r.parts.flatMap(p=>p.distractors)).length,51);});
test('professional and municipal partitions use correct unequal population weights',()=>{const d=.3*.75+.25*.6+.45*.15;check(648,[1-d,.3*.75/d]);check(1109,[(420+120+200)/2000,480/(580+480+200)]);});
test('scooter union deducts overlap exactly once and model-conditional complement is not marginal',()=>{const p=.25*.15+.4*.1+.35*.12;check(1197,[p,1-.15,p+.35-.35*.12]);const wrong=at(1197).parts[2].distractors.map(number);near(wrong[0],p+.35);near(wrong[1],.35*.12);near(wrong[2],p+.35-2*.35*.12);});
test('hospitalization posterior uses non-hospitalized denominator',()=>{const h=.35*.15+.4*.45+.25*.2;check(1210,[h,.25*.8/(1-h)]);});
test('airbag good-production Bayesian denominator includes every plant',()=>{const good=.45*.99+.21*.97+.34*.98;check(1220,[.34*.98,.45*.99/good]);near(good,1-(.45*.01+.21*.03+.34*.02));});
test('physical enumeration of the census verifies travelers and posterior',()=>{const people=[...Array(1275).fill(['M',true]),...Array(7225).fill(['M',false]),...Array(1300).fill(['H',true]),...Array(5200).fill(['H',false])];check(1274,[people.filter(x=>x[1]).length/people.length,people.filter(x=>x[0]==='H'&&!x[1]).length/people.filter(x=>!x[1]).length]);});
test('tourist and geography probabilities are independently recomputed from source rates',()=>{const hotel=.65*.75+.35*.15;check(1292,[hotel,.35*.85/(1-hotel)]);const a=598/1150,b=1-a,pass=a*.78+b*.74;check(1534,[pass,a*.78/pass]);assert.match(cases.find(x=>x.index===1534).definitions,/no recuentos inventados/);});
test('official source, score evidence and source PDF remain immutable; all partition weights nonnegative',()=>{const canon=fs.readFileSync('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl','utf8').trim().split(/\r?\n/).map(JSON.parse);for(const c of cases){const r=at(c.index),s=canon.find(x=>x.exerciseId===r.exerciseId);assert.equal(r.sourceLiteral,s.officialPrompt);assert.deepEqual(r.scoreEvidence,s.scoreEvidence);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(r.officialSource.path)).digest('hex'),r.officialSource.documentHash);assert.equal(c.cells.reduce((n,x)=>n+x[2],0),c.scale);assert.ok(c.cells.every(x=>x[2]>=0));for(const q of c.queries)if(q.d!=='all')assert.ok(q.n.every(x=>q.d.includes(x)));}});
test('repeat and reverse order are semantically identical',()=>{const sig=xs=>xs.map(r=>[r.exerciseId,r.sourceLiteral,r.parts]).sort((a,b)=>a[0].localeCompare(b[0]));assert.deepEqual(sig(records),sig(buildPopulationBatch().batch.records));assert.deepEqual(sig(records),sig(buildPopulationBatch('batch-0284',[...cases].reverse()).batch.records));});
