import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {cases,buildUrnEventBatch} from '../scripts/resolve-andalucia-probability-urns-and-events.mjs';
const rows=buildUrnEventBatch().batch.records,at=i=>rows.find(x=>x.correctionEvidence.parameters.index===i);
const val=s=>{const m=s.match(/^frac\{(-?\d+)\}\{(\d+)\}$/);return m?+m[1]/+m[2]:Number(s);};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-12,`${a} != ${b}`);
function check(i,values){const r=at(i);assert.equal(r.parts.length,values.length);for(const[j,n]of values.entries()){const p=r.parts[j],xs=[p.answer,...p.distractors].map(val);near(xs[0],n);assert.ok(xs.every(x=>Number.isFinite(x)&&x>=0&&x<=1));assert.equal(xs.filter(x=>Math.abs(x-n)<1e-12).length,1);assert.equal(new Set(xs.map(x=>x.toFixed(12))).size,4);}}
test('eight official sources, twenty-one complete parts and sixty-three plausible false alternatives',()=>{assert.equal(rows.length,8);assert.equal(rows.flatMap(r=>r.parts).length,21);for(const r of rows)for(const p of r.parts){assert.equal(p.answer,p.finalAnswer);assert.equal(p.distractors.length,3);assert.ok(p.solutionSteps.length>=6);}});
test('series inclusion-exclusion and pharmacological total probability are independently solved',()=>{const union=1-.18,joint=.69+.35-union;check(762,[union,joint/.69,.69-joint]);const total=.3*.6+.5*.8+.2*.7;check(956,[total,.3*.6/total]);});
test('the bicycle unknown is solved only with the additional part-c premise',()=>{check(800,[.3*.8+.7*.6,.3*(1-.8-.05),(.19-.3*.05)/.7]);const c=cases.find(x=>x.index===800);assert.equal(c.cells.filter(x=>x[0]==='E2').length,2);assert.deepEqual(c.cells.filter(x=>x[0]==='E2').map(x=>x[1]),['B','Bc']);assert.ok(!JSON.stringify(at(800).parts.slice(0,2)).includes('0,19'));});
test('independence AB and incompatibility AC are distinct models, with no fabricated BC relationship',()=>{const pa=.4,pb=.1/pa;check(871,[(pa-.1)/(1-pb),1-pa-.2,1-pa]);const p=at(871).parts[1];assert.deepEqual(p.verification.numericalEvidence.weights,[['A','C',0],['A','Cc',2],['Ac','C',1],['Ac','Cc',2]]);});
test('replacement by opposite-color balls removes the first ball; exact transition enumeration',()=>{for(const[i,r,b,k]of [[887,6,4,6],[998,5,3,2]]){const n=r+b,after=n-1+k,rr=r/n*(r-1)/after,rb=r/n*(b+k)/after,br=b/n*(r+k)/after,bb=b/n*(b-1)/after;near(rr+rb+br+bb,1);if(i===887)check(i,[rr+br,bb/(rb+bb)]);else check(i,[rb+bb,rr/(rr+br)]);}});
test('enumeration of 8010 distinct ordered key pairs checks all answers and alternatives',()=>{const pairs=[];for(let a=0;a<90;a++)for(let b=0;b<90;b++)if(a!==b)pairs.push([a<60,b<60]);check(906,[pairs.filter(([a,b])=>a&&b).length/pairs.length,pairs.filter(([a,b])=>a||b).length/pairs.length,pairs.filter(([a,b])=>a!==b).length/pairs.length]);});
test('enumeration of fifteen physical slips checks no replacement and posterior direction',()=>{const slips=['M','M','M','L','L',...Array(10).fill('C')],pairs=[];for(let a=0;a<15;a++)for(let b=0;b<15;b++)if(a!==b)pairs.push([slips[a],slips[b]]);check(1030,[pairs.filter(([a,b])=>a==='M'&&b==='M').length/210,pairs.filter(([a,b])=>a!=='C'&&b!=='C').length/210,pairs.filter(([a,b])=>a==='L'&&b==='L').length/pairs.filter(([,b])=>b==='L').length]);});
test('official literals, score evidence, source hashes and partition positivity are preserved',()=>{const canonical=fs.readFileSync('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl','utf8').trim().split(/\r?\n/).map(JSON.parse);for(const c of cases){const r=at(c.index),s=canonical.find(x=>x.exerciseId===r.exerciseId);assert.equal(r.sourceLiteral,s.officialPrompt);assert.deepEqual(r.scoreEvidence,s.scoreEvidence);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(r.officialSource.path)).digest('hex'),r.officialSource.documentHash);assert.equal(c.cells.reduce((s,x)=>s+x[2],0),c.scale);assert.ok(c.cells.every(x=>x[2]>=0));for(const q of c.queries)if(q.d!=='all')assert.ok(q.n.every(x=>q.d.includes(x)));}});
test('repeat and reversed order preserve every mathematical output',()=>{const sig=xs=>xs.map(x=>[x.exerciseId,x.sourceLiteral,x.parts]).sort((a,b)=>a[0].localeCompare(b[0]));assert.deepEqual(sig(rows),sig(buildUrnEventBatch().batch.records));assert.deepEqual(sig(rows),sig(buildUrnEventBatch('batch-0283',[...cases].reverse()).batch.records));});
