import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {observations,cases,proof,solve,buildPlaneMetricsBatch} from '../scripts/resolve-andalucia-mates-plane-metrics.mjs';
const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),sub=(a,b)=>a.map((x,i)=>x-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>Math.hypot(...a),near=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),value=(p,x)=>dot(p.slice(0,3),x)+p[3],parallel=(a,b)=>norm(cross(a,b))<1e-9;
test('five plane-metric original pages retain their source hashes',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);});
test('566 reflection distance and unique perpendicular-bisector plane reject all alternatives',()=>{const v=proof({index:566}),A=[-1,2,6],B=[1,4,-2];assert.deepEqual(v.midpoint,A.map((x,i)=>(x+B[i])/2));near(norm(sub(B,A))/2,v.distance);assert.deepEqual([3*Math.SQRT2,6*Math.SQRT2,18,Math.SQRT2].map(x=>Math.abs(x-v.distance)<1e-9),[true,false,false,false]);assert.deepEqual([[1,1,-4,5],[1,1,-4,-5],[1,1,4,-11],[2,2,-8,5]].map(p=>value(p,v.midpoint)===0&&parallel(p.slice(0,3),sub(B,A))),[true,false,false,false]);near(value(v.plane,A),-value(v.plane,B));});
test('579 triangle area and tetrahedron volume independently checked by Gram and determinant',()=>{const v=proof({index:579}),[A,B,C]=v.vertices,u=sub(B,A),w=sub(C,A);for(const x of v.vertices)near(value([2,1,3,-6],x),0);assert.deepEqual(cross(u,w),v.cross);near(norm(cross(u,w))/2,v.area);near((dot(u,u)*dot(w,w)-dot(u,w)**2)/4,v.area**2);near(Math.abs(dot(A,cross(B,C)))/6,v.volume);assert.deepEqual([3*Math.sqrt(14),6*Math.sqrt(14),9,3*Math.sqrt(13)].map(x=>Math.abs(x-v.area)<1e-9),[true,false,false,false]);assert.deepEqual([6,36,18,12].map(x=>x===v.volume),[true,false,false,false]);});
test('587 normal plane, projection foot and reflected point checked independently',()=>{const v=proof({index:587}),P=[1,0,5];assert.deepEqual([[0,-2,1,-5],[0,1,2,-10],[0,-2,1,5],[1,0,0,-1]].map(p=>value(p,P)===0&&parallel(p.slice(0,3),v.direction)),[true,false,false,false]);near(dot(sub(P,v.foot),v.direction),0);near(v.foot[1]+2*v.foot[2],0);near(norm(sub(P,v.foot)),v.distance);assert.deepEqual(v.mirror,v.foot.map((x,i)=>2*x-P[i]));const valid=(d,m)=>{const h=m.map((x,i)=>(x+P[i])/2);return Math.abs(d-v.distance)<1e-9&&h[0]===1&&h[1]+2*h[2]===0&&Math.abs(dot(sub(P,h),v.direction))<1e-9};assert.deepEqual([[2*Math.sqrt(5),[1,-4,-3]],[2*Math.sqrt(5),[1,4,3]],[4*Math.sqrt(5),[1,-4,-3]],[5,[1,0,-5]]].map(x=>valid(...x)),[true,false,false,false]);});
test('588 point-normal plane and full spatial triangle area reject projected and doubled areas',()=>{const v=proof({index:588}),A=[0,1,0],d=[1,2,1];assert.deepEqual([[1,2,1,-2],[1,2,1,2],[2,1,1,-1],[1,2,-1,-2]].map(p=>value(p,A)===0&&parallel(p.slice(0,3),d)),[true,false,false,false]);const[U,V,W]=v.vertices;for(const x of v.vertices)near(value([2,3,4,-12],x),0);near(norm(cross(sub(V,U),sub(W,U)))/2,v.area);assert.deepEqual([3*Math.sqrt(29),6*Math.sqrt(29),12,3*Math.sqrt(13)].map(x=>Math.abs(x-v.area)<1e-9),[true,false,false,false]);});
test('596 non-obtuse angle and volume check all four answers',()=>{const v=proof({index:596}),[n,m]=v.normals;near(Math.abs(dot(n,m))/(norm(n)*norm(m)),v.cosine);near(Math.acos(v.cosine)*180/Math.PI,60);assert.deepEqual([60,120,30,90].map(x=>x>=0&&x<=90&&Math.abs(Math.cos(x*Math.PI/180)-v.cosine)<1e-9),[true,false,false,false]);near(Math.abs(dot(v.vertices[0],cross(v.vertices[1],v.vertices[2])))/6,v.volume);assert.deepEqual([125/36,125/6,125/12,125/18].map(x=>Math.abs(x-v.volume)<1e-9),[true,false,false,false]);});
test('five geometry exercises and ten complete parts preserve evidence and reverse-order invariance',()=>{const a=buildPlaneMetricsBatch('test').batch,b=buildPlaneMetricsBatch('test',[...cases].reverse()).batch;assert.deepEqual(a.records,[...b.records].reverse());assert.equal(a.records.length,5);assert.equal(cases.flatMap(solve).length,10);for(const r of a.records){assert.equal(r.qualityGates.publication,'NOT_ENABLED');for(const p of r.parts){assert.equal(p.answer,p.finalAnswer);assert.equal(p.solutionSteps.length,6);assert.equal(new Set([p.answer,...p.distractors]).size,4);}}});
