import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,integerOptima,buildWorkshopsAdvertisingBatch} from '../scripts/resolve-andalucia-linear-workshops-advertising.mjs';
import {workshopsAdvertisingObservations,workshopsAdvertisingReplacements} from '../scripts/andalucia-workshops-advertising-pdf-evidence.mjs';
import {renderRationalGraph} from '../scripts/resolve-andalucia-linear-rational-and-faces.mjs';
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),rows=()=>buildWorkshopsAdvertisingBatch('workshops-test').batch.records,close=(a,b,t=1e-7)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
for(const c of cases)test(`${c.index} positive dual certificate proves global real maximum; independent integer enumeration confirms all optima`,()=>{
 for(let j=0;j<2;j++)close(c.constraints.reduce((s,r,i)=>s+r[j]*c.dual[i],0),c.objective[j]);assert.ok(c.dual.every(x=>x>=0));close(c.constraints.reduce((s,r,i)=>s+r[2]*c.dual[i],0),c.maximum);
 const r=integerOptima(c);assert.equal(r.best,c.maximum);if(c.index===757)assert.deepEqual(r.hits,Array.from({length:9},(_,k)=>[6+3*k,16-2*k]));else assert.deepEqual(r.hits,[c.optimum]);
 for(let x=0;x<=c.domain.x[1];x+=.5)for(let y=0;y<=c.domain.y[1];y+=.5){if(!c.constraints.every(([a,b,k])=>a*x+b*y<=k))continue;const z=c.objective[0]*x+c.objective[1]*y;assert.ok(z<=c.maximum+1e-8);close(c.maximum-z,c.constraints.reduce((s,[a,b,k],i)=>s+c.dual[i]*(k-a*x-b*y),0));}
 const p=rows().find(r=>r.correctionEvidence.parameters.index===c.index).parts[0],v=p.verification.numericalEvidence;close(v.max,c.maximum);for(const point of v.wrongPoints??[]){const [x,y]=point,valid=c.constraints.every(([a,b,k])=>a*x+b*y<=k);assert.ok(!valid||c.objective[0]*x+c.objective[1]*y<c.maximum);}const svg=renderRationalGraph(p.visual);assert.match(svg,/<polygon/);assert.doesNotMatch(svg,/undefined|NaN/);assert.equal(svg,renderRationalGraph(p.visual));
});
test('639 proposed 49/32 is rejected solely by the demonstrated carbon excess; 702 proposal is feasible but suboptimal',()=>{assert.equal(90*49+100*32,7610);assert.equal(100*49+50*32,6500);assert.equal(60+2*50,160);assert.equal(2*60+2*50,220);assert.equal(250*60+350*50,32500);const r=rows().find(r=>r.correctionEvidence.parameters.index===702);assert.deepEqual(r.parts[1].verification.numericalEvidence.resources,[160,220]);assert.match(r.parts[1].answer,/no máximo/);});
test('687 absolute difference is represented in both directions; wrong audience and infeasible television-only proposal rejected',()=>{const c=cases.find(c=>c.index===687);assert.equal(34000*7+72000*17,1462000);assert.equal(2400*7+3600*17,78000);assert.ok(!c.constraints.every(([a,b,k])=>a*0+b*21<=k));assert.ok(!c.constraints.every(([a,b,k])=>a*21+b*0<=k));assert.notEqual(1426000,c.maximum);});
test('757 all nine integer optima, not one vertex; every generated parametric alternative is demonstrably false',()=>{const c=cases.find(c=>c.index===757),p=rows().find(r=>r.correctionEvidence.parameters.index===757).parts[0],v=p.verification.numericalEvidence;assert.equal(v.integerOptima.length,9);assert.deepEqual(v.integerOptima.map(p=>p.join()).sort(),integerOptima(c).hits.map(p=>p.join()).sort());assert.equal(2*3+18,24);assert.ok(24<28);assert.ok(2*28+3*2>60);assert.match(p.answer,/Nueve/);assert.ok(v.integerOptima.some(([x,y])=>x===6&&y===16));});
test('858 three resource residuals are explicitly checked, with no assumption that every optimum consumes all resources',()=>{const p=rows().find(r=>r.correctionEvidence.parameters.index===858).parts[1];assert.deepEqual(p.verification.numericalEvidence.leftover,[500-100-2*200,400-2*100-200,225-200]);assert.deepEqual(p.verification.numericalEvidence.leftover,[0,0,25]);});
test('six PDF sources and inspected page images bind exact data; editorial removal is reversible and preserves source literal',()=>{for(const r of rows()){const i=r.correctionEvidence.parameters.index,o=workshopsAdvertisingObservations.find(o=>o[0]===i);assert.equal(sha(fs.readFileSync(r.officialSource.path)),o[1]);assert.equal(sha(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${i}.png`)),o[4]);let t=r.sourceLiteral;for(const[b,a]of workshopsAdvertisingReplacements({...r,queueIndex:i})){const at=t.indexOf(b);assert.ok(at>=0);const next=t.slice(0,at)+a+t.slice(at+b.length);assert.equal(next.slice(0,at)+b+next.slice(at+a.length),t);t=next;}assert.doesNotMatch(t,/BLOQUE B|undefined/);if(i===687){assert.match(t,/audiencia/);assert.match(r.sourceLiteral,/BLOQUE B/);}}});
test('six complete exercises and eight original response units have four options, full pedagogy and graph support',()=>{const r=rows();assert.equal(r.length,6);assert.equal(r.reduce((n,r)=>n+r.parts.length,0),8);for(const x of r){assert.equal(x.primaryTopic,'Programación lineal');assert.ok(x.parts[0].visual);for(const p of x.parts){assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.answer,p.finalAnswer);assert.ok(p.solutionSteps.length>=6);assert.equal(p.verification.verified,true);}}});
test('batch construction reproducible under reversed input without modifying runtime or queue',()=>{const files=['data/andalucia-pau-runtime.js','math-renderer.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=files.map(p=>sha(fs.readFileSync(p))),sort=r=>r.sort((a,b)=>a.exerciseId.localeCompare(b.exerciseId));assert.deepEqual(rows(),rows());assert.deepEqual(sort(rows()),sort(buildWorkshopsAdvertisingBatch('workshops-test',[...cases].reverse()).batch.records));assert.deepEqual(files.map(p=>sha(fs.readFileSync(p))),before);});
