import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {cases,sourceImages,buildRegionBatch} from '../scripts/resolve-andalucia-inference-critical-regions.mjs';
import {hypothesisValues} from '../scripts/resolve-andalucia-inference-confidence-and-tests.mjs';
const records=buildRegionBatch().batch.records,at=i=>records.find(r=>r.correctionEvidence.parameters.index===i);
const close=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),num=s=>Number(s.replace(',','.'));
// Independent Python statistics.NormalDist results, not generated by the solver.
const refs=[[686,-1.7320508075688772,2.17009037758456,.04163225833177525],[689,2.0224719101123565,1.6448536269514715,.0215638113390888],[696,1.4925373134328357,1.6448536269514715,.06777917147602275],[704,-3.577708763999667,2.3263478740408408,.00017330967556733468],[760,3,1.6448536269514715,.0013498980316299924],[860,.585021367131191,1.9599639845400536,.27926667481156286],[870,2,1.6448536269514715,.022750131948179098],[1337,-.6324555320336759,1.6448536269514715,.26354462843276905]];
test('eight official exercises keep all eighteen scopes without invented subparts',()=>{
 assert.equal(records.length,8);assert.equal(records.reduce((n,r)=>n+r.parts.length,0),18);
 for(const r of records){const c=r.correctionEvidence.parameters;assert.deepEqual(r.parts.map(p=>p.partId),c.whole?['whole']:c.tasks.map((_,i)=>String.fromCharCode(97+i)));
  if(c.whole)assert.equal(r.deliveryScope,'WHOLE_OFFICIAL_EXERCISE');
  for(const p of r.parts){assert.equal(p.answer,p.finalAnswer);assert.equal(p.distractors.length,3);assert.ok(p.solutionSteps.length>=5);assert.doesNotMatch(p.prompt,/\([^)]*puntos?\)/);}
 }
});
test('eight independent quantiles, p values and decisions',()=>{
 for(const [i,z,cut,p]of refs){const c=cases.find(x=>x.index===i),v=hypothesisValues(c);close(v.z,z);close(v.cut,cut);close(v.pValue,p);assert.equal(v.rejected,p<c.levels[0]);}
});
test('each full test has exactly one correct, three wrong non-equivalent composite options',()=>{
 for(const c of cases){const p=at(c.index).parts.at(-1),v=hypothesisValues(c),strings=[p.answer,...p.distractors];
  const tuples=strings.map(s=>{const m=s.match(/Z ([<>]) (-?\d+(?:,\d+)?).*Z ≈ (-?\d+(?:,\d+)?); (no se rechaza|se rechaza)/);assert.ok(m,s);return [m[1],num(m[2]),num(m[3]),m[4]==='se rechaza'];});
  const expected=[c.tail==='left'?'<':'>',c.tail==='left'?-v.cut:v.cut,v.z,v.rejected];
  const valid=t=>t[0]===expected[0]&&Math.abs(t[1]-expected[1])<.000006&&Math.abs(t[2]-expected[2])<.000006&&t[3]===expected[3];
  assert.ok(valid(tuples[0]));assert.equal(tuples.filter(valid).length,1);assert.equal(new Set(tuples.map(JSON.stringify)).size,4);
 }
});
test('acceptance and rejection use correct signs and scale; every alternative describes a different region',()=>{
 for(const c of cases.filter(c=>c.tasks)){const r=at(c.index),v=hypothesisValues(c),bound=c.tail==='left'?-v.cut:v.cut;
  for(const [i,task]of c.tasks.entries())if(['acceptance','rejection','hypotheses-rejection'].includes(task)){
   const p=r.parts[i],sign=task==='acceptance'?(c.tail==='left'?'≥':'≤'):(c.tail==='left'?'<':'>');
   const tuples=[p.answer,...p.distractors].map(s=>{const m=s.match(/Z ([<>≤≥]) (-?\d+(?:,\d+)?); x̄ ([<>≤≥]) (-?\d+(?:,\d+)?)/);assert.ok(m,s);return [m[1],num(m[2]),m[3],num(m[4])];});
   const valid=t=>t[0]===sign&&t[2]===sign&&Math.abs(t[1]-bound)<.000006&&Math.abs(t[3]-(c.nullValue+bound*v.se))<.000006;
   assert.ok(valid(tuples[0]));assert.equal(tuples.filter(valid).length,1);assert.equal(new Set(tuples.map(JSON.stringify)).size,4);
  }
 }
 assert.match(at(696).parts[1].answer,/No rechazo: Z ≤/);assert.match(at(860).parts[1].answer,/10,0124/);
});
test('hypotheses are population statements and sample oranges total 870 kg',()=>{
 for(const c of cases.filter(c=>c.tasks?.[0]==='hypotheses')){const p=at(c.index).parts[0],tuples=[p.answer,...p.distractors].map(s=>s.match(/H₀: μ ([≤≥=]) ([\d,]+); H₁: μ ([<>≠]) ([\d,]+)/).slice(1));
  const valid=t=>t[0]===(c.tail==='left'?'≥':'≤')&&t[2]===(c.tail==='left'?'<':'>')&&num(t[1])===c.nullValue&&num(t[3])===c.nullValue;
  assert.ok(valid(tuples[0]));assert.equal(tuples.filter(valid).length,1);assert.equal(new Set(tuples.map(JSON.stringify)).size,4);
 }
 assert.equal(cases.at(-1).sample.reduce((s,x)=>s+x,0),870);assert.match(at(1337).parts[1].solutionSteps[1].math,/870/);assert.doesNotMatch(JSON.stringify(at(1337).parts),/diámetros/);
});
test('PDF hashes, inspected images and the restored significance have explicit provenance',()=>{
 const sha=x=>crypto.createHash('sha256').update(x).digest('hex');for(const r of records){const c=r.correctionEvidence.parameters;assert.equal(sha(fs.readFileSync(r.officialSource.path)),r.officialSource.documentHash);assert.equal(sha(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${c.index}.png`)),sourceImages[c.index]);}
 const r=at(860),e=r.correctionEvidence.parameters.officialParameterRecovery;assert.equal(e.documentHash,r.officialSource.documentHash);assert.equal(e.value,.025);assert.equal(e.imageHash,sourceImages[860]);assert.match(r.sourceLiteral,/para un nivel de significación\nc\)/);assert.doesNotMatch(r.sourceLiteral,/0\.025/);
});
test('rebuild and reverse-order identity; wrong original parameters cannot pass source checks',()=>{
 const norm=rs=>rs.map(r=>[r.exerciseId,r.parts]).sort((a,b)=>a[0].localeCompare(b[0]));assert.deepEqual(norm(records),norm(buildRegionBatch().batch.records));assert.deepEqual(norm(records),norm(buildRegionBatch('batch-0254',[...cases].reverse()).batch.records));
 assert.throws(()=>buildRegionBatch('not-consumed',[{...cases[0],successes:15}]));assert.throws(()=>buildRegionBatch('not-consumed',[{...cases[0],literals:['murieron 15']}]));assert.throws(()=>buildRegionBatch('not-consumed',[{...cases.at(-1),center:88}]));
});
