import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {observations,cases,line1046,system1051,buildReflectionAngleCompatibleBatch} from '../scripts/resolve-andalucia-reflection-angle-compatible.mjs';
const near=(a,b,t=1e-7)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,x,j)=>s+x*b[j],0),sub=(a,b)=>a.map((x,j)=>x-b[j]),norm=a=>dot(a,a),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
function rank(m){m=m.map(r=>r.slice());let k=0;for(let j=0;j<m[0].length&&k<m.length;j++){let i=m.findIndex((r,i)=>i>=k&&Math.abs(r[j])>1e-9);if(i<0)continue;[m[i],m[k]]=[m[k],m[i]];const p=m[k][j];m[k]=m[k].map(x=>x/p);for(let z=k+1;z<m.length;z++){const f=m[z][j];m[z]=m[z].map((x,c)=>x-f*m[k][c]);}k++;}return k;}
test('0468 official source bytes and inspected page hashes unchanged',()=>{const rows=p=>fs.readFileSync(p,'utf8').trim().split(/\r?\n/).map(JSON.parse),q=rows('artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'),m=new Map(rows('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl').map(x=>[x.exerciseId,x])),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');for(const o of observations){const e=m.get(q[o[0]].exerciseId);assert.equal(sha(e.provenance.localPath),o[1]);assert.equal(e.sourceRange.page,o[2]);assert.equal(sha(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`),o[4]);}});
test('1046 symmetry independently validates midpoint and perpendicular chord, exactly one answer',()=>{const P=[1,0,-1],v=[1,1,-2],valid=S=>{const H=S.map((x,i)=>(x+P[i])/2);return norm(sub(H,line1046(H[1])))<1e-9&&Math.abs(dot(sub(S,P),v))<1e-9;};assert.deepEqual([[7,-2,1],[4,-1,0],[11,2,-7],[9,0,-3]].map(valid),[true,false,false,false]);});
test('1046 equidistant point checks two distances and rejects all distractors',()=>{const P=[1,0,-1],Q=[2,1,1],valid=X=>norm(sub(X,line1046(X[1])))<1e-9&&Math.abs(norm(sub(X,P))-norm(sub(X,Q)))<1e-9;assert.deepEqual([[4.5,-.5,-1],[5.5,.5,-3],[4,-1,0],[5,0,-2]].map(valid),[true,false,false,false]);near(norm(sub([4.5,-.5,-1],P)),12.5);});
test('1048 critical parameter independently differentiated numerically; options mutually distinct',()=>{const derivative=a=>{const h=1e-5,f=x=>(x-a)*Math.exp(x);return (f(h)-f(-h))/(2*h);};assert.deepEqual([1,0,-1,2].map(a=>Math.abs(derivative(a))<1e-7),[true,false,false,false]);});
test('1048 unique inflection satisfies function and second derivative with sign change',()=>{const f=x=>(x-1)*Math.exp(x),d2=x=>(x+1)*Math.exp(x),opts=[[-1,-2/Math.E],[0,-1],[1,0],[-1,2/Math.E]];assert.deepEqual(opts.map(([x,y])=>Math.abs(f(x)-y)<1e-9&&Math.abs(d2(x))<1e-9),[true,false,false,false]);assert.ok(d2(-1.1)<0&&d2(-.9)>0);const h=1e-3;for(const x of [-2,-.5,.5])near((f(x+h)-2*f(x)+f(x-h))/(h*h),d2(x),1e-6);});
test('1049 angle verified from independent vector norms, no squared-root extraneous candidate',()=>{const cosine=a=>{const u=[1,a,2],v=[-2,1,a];return dot(u,v)/Math.sqrt(norm(u)*norm(v));};assert.deepEqual([3,-3,2/3,1].map(a=>Math.abs(cosine(a)-.5)<1e-9),[true,false,false,false]);near(Math.acos(cosine(3)),Math.PI/3);});
test('1049 cross product orthogonality independently computed with all three components',()=>{const residual=a=>{const u=[1,a,2],v=[-2,1,a];return dot(sub(cross(u,v),v),u);};assert.deepEqual([2/3,-2/3,3,2].map(a=>Math.abs(residual(a))<1e-9),[true,false,false,false]);for(let a=-10;a<=10;a++)near(residual(a),2-3*a);});
test('1051 Rouché Frobenius verified using independent elimination on coefficient and augmented matrices',()=>{const det=m=>m[0][0]*(m[1][1]*m[2][2]-m[1][2]*m[2][1])-m[0][1]*(m[1][0]*m[2][2]-m[1][2]*m[2][0])+m[0][2]*(m[1][0]*m[2][1]-m[1][1]*m[2][0]);for(const l of [-3,-2,-1,-.5,0,.5,1,2,3]){const {A,b}=system1051(l),r=rank(A),ra=rank(A.map((row,i)=>[...row,b[i]]));near(det(A),2*l*(l+1));assert.equal(r,ra);assert.equal(r,l===0||l===-1?2:3);}});
test('1051 all free solutions and generic unique solution verified, parameter-family distractors rejected',()=>{const residual=(l,X)=>{const {A,b}=system1051(l);return A.every((row,i)=>Math.abs(dot(row,X)-b[i])<1e-9);};for(const t of [-10,-1,0,.25,1,3,20]){assert.ok(residual(0,[0,0,t]));assert.ok(residual(-1,[t-1,t,1-2*t]));}for(const l of [-2,-.5,.5,1,3])assert.ok(residual(l,[l,0,1]));const opts=[t=>[[0,0,t],[t-1,t,1-2*t]],t=>[[t,t,0],[t-1,t,1-2*t]],t=>[[0,0,t],[t+1,t,1-2*t]],t=>[[0,0,t],[t-1,t,1+2*t]]];assert.deepEqual(opts.map(fn=>[-2,0,1,3].every(t=>{const [a,b]=fn(t);return residual(0,a)&&residual(-1,b);})),[true,false,false,false]);});
test('0468 deterministic four records eight six-step parts, reversible statement and no enabling',()=>{const a=buildReflectionAngleCompatibleBatch('test').batch,b=buildReflectionAngleCompatibleBatch('test',[...cases].reverse()).batch;assert.equal(a.records.length,4);assert.equal(a.records.flatMap(r=>r.parts).length,8);assert.deepEqual(a.records,[...b.records].reverse());for(const r of a.records){assert.equal(r.qualityGates.publication,'NOT_ENABLED');assert.equal(r.qualityGates.rendering,'RECHECK_REQUIRED');for(const p of r.parts){assert.equal(p.solutionSteps.length,6);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.answer,p.finalAnswer);}}});
