import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {observations,cases,solve,proof,buildRankTetrahedraBatch} from '../scripts/resolve-andalucia-mates-rank-tetrahedra.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),sub=(a,b)=>a.map((v,i)=>v-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],det=m=>dot(m[0],cross(m[1],m[2]));
function rank(m){m=m.map(r=>[...r]);let k=0;for(let j=0;j<m[0].length&&k<m.length;j++){const pivot=m.findIndex((r,i)=>i>=k&&Math.abs(r[j])>1e-10);if(pivot<0)continue;[m[k],m[pivot]]=[m[pivot],m[k]];const p=m[k][j];m[k]=m[k].map(v=>v/p);for(let i=0;i<m.length;i++)if(i!==k){const f=m[i][j];m[i]=m[i].map((v,l)=>v-f*m[k][l]);}k++;}return k;}
test('rank-tetrahedra official page hashes match inspected evidence',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);});
test('354 exceptional ranks and all four classifications verified independently',()=>{const classify=a=>{const m=[[1,0,a],[2,a,0],[3,1,a+4]],b=[2,a+4,7];near(det(m),-2*a*(a-3));const r=rank(m),s=rank(m.map((x,i)=>[...x,b[i]]));return r<s?'SI':r===3?'SCD':'SCI';};for(const a of[-7,-3,-1,0,.5,2,3,7])assert.equal(classify(a),[0,3].includes(a)?'SCI':'SCD');const options=[a=>[0,3].includes(a)?'SCI':'SCD',a=>[0,3].includes(a)?'SI':'SCD',a=>[0,-3].includes(a)?'SCI':'SCD',a=>a===0?'SCI':'SCD'];assert.deepEqual(options.map(f=>[-3,0,2,3].every(a=>f(a)===classify(a))),[true,false,false,false]);for(const a of[0,3])for(const t of[-2,0,.25,7]){const p=a===0?[2,1-4*t,t]:[2-3*t,1+2*t,t];[[1,0,a],[2,a,0],[3,1,a+4]].forEach((r,i)=>near(dot(r,p),[2,a+4,7][i]));}});
test('354 numeric solution and distractors checked by substitution',()=>{const m=[[1,0,2],[2,2,0],[3,1,6]],b=[2,6,7];assert.deepEqual([[2,1,0],[1,2,0],[2,0,1],[0,1,2]].map(p=>m.every((r,i)=>dot(r,p)===b[i])),[true,false,false,false]);});
test('359 only one plane contains the entire s and is parallel to r',()=>{const p=proof({index:359}),valid=([n,d])=>dot(n,p.point)===d&&dot(n,p.rDirection)===0&&dot(n,p.sDirection)===0;assert.deepEqual([[[8,6,11],18],[[8,6,11],121],[[8,-6,11],42],[[8,6,-11],-26]].map(valid),[true,false,false,false]);assert.deepEqual(cross(p.rDirection,p.sDirection),p.normal);assert.notEqual(dot(p.normal,[-11,0,19]),p.constant);});
test('372 dependence and volume verified directly from official vertices',()=>{const value=k=>{const A=[-1,k,3],B=[k+1,0,2],C=[1,2,0],D=[2,0,1];return {consecutive:det([sub(B,A),sub(C,B),sub(D,C)]),volume:Math.abs(det([sub(B,A),sub(C,A),sub(D,A)]))/6};};for(const k of[-8,-1,0,2,.3]){near(value(k).consecutive,-k*k-2*k-2);assert.notEqual(value(k).consecutive,0);}const options=[[-1-Math.sqrt(5),-1+Math.sqrt(5)],[-1-Math.sqrt(7),-1+Math.sqrt(7)],[-1-Math.sqrt(2),-1+Math.sqrt(2)],[1-Math.sqrt(5),1+Math.sqrt(5)]];assert.deepEqual(options.map(ks=>ks.every(k=>Math.abs(value(k).volume-1)<1e-9)),[true,false,false,false]);for(const k of[-1-Math.sqrt(2),-1+Math.sqrt(2),-1])assert.notEqual(value(k).consecutive,0);});
test('373 determinant volume equals triangular base times height divided by three',()=>{const A=[0,2,-2],B=[3,2,1],C=[2,3,2],n=cross(sub(B,A),sub(C,A)),d=dot(n,A),intercepts=n.map(v=>d/v),v=Math.abs(intercepts.reduce((p,x)=>p*x,1))/6;near(v,18);near(v,(6*3/2)*6/3);assert.deepEqual([18,108,-18,36].map(x=>x===v),[true,false,false,false]);for(const p of[A,B,C])near(dot([1,2,-1],p),6);});
test('six complete parts, source guards, reversal and no premature enabling',()=>{const ps=cases.flatMap(solve);assert.equal(ps.length,6);for(const p of ps){assert.equal(p.solutionSteps.length,6);assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);}const a=buildRankTetrahedraBatch('test').batch,b=buildRankTetrahedraBatch('test',[...cases].reverse()).batch;assert.deepEqual(a.records,[...b.records].reverse());a.records.forEach(r=>assert.equal(r.qualityGates.publication,'NOT_ENABLED'));});
