import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {cases,buildSourceBranchBatch} from '../scripts/resolve-andalucia-probability-source-branches.mjs';
const rows=buildSourceBranchBatch().batch.records,at=i=>rows.find(x=>x.correctionEvidence.parameters.index===i);
const val=s=>{const m=s.match(/^frac\{(-?\d+)\}\{(\d+)\}$/);return m?+m[1]/+m[2]:Number(s);};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-12,`${a} != ${b}`);
test('six official exercises, thirteen fully answered parts, thirty-nine distinct distractors',()=>{assert.equal(rows.length,6);assert.equal(rows.flatMap(x=>x.parts).length,13);for(const r of rows)for(const p of r.parts){assert.equal(p.answer,p.finalAnswer);assert.equal(p.distractors.length,3);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.ok(p.solutionSteps.length>=6);}});
test('independent tree calculations verify all twelve numeric answers and false options',()=>{
 const refs=[[364,[.65*.8+.35*.3,.65*.8/(.65*.8+.35*.3)]],[400,[(200/500+500/900+200/300)/3,(300/500)/(300/500+400/900+100/300)]],[402,[(1800+2400+3000)/30000,(10000-1800)/(30000-1800-2400-3000)]],[528,[(140*.05+100*.04+150*.02)/440,96/(140*.95+100*.96+150*.98+50)]],[586,[(3000*.9+1500*.95)/5000,500/(3000*.1+1500*.05+500)]],[643,[.5*.8+.3*.85+.2*.3,.2*.7/(.5*.2+.3*.15+.2*.7)]]];
 for(const[i,expected]of refs)for(const[j,n]of expected.entries()){const p=at(i).parts[j],xs=[p.answer,...p.distractors].map(val);near(xs[0],n);assert.ok(xs.every(x=>Number.isFinite(x)&&x>=0&&x<=1));assert.equal(xs.filter(x=>Math.abs(x-n)<1e-12).length,1);assert.equal(new Set(xs.map(x=>x.toFixed(12))).size,4);}
});
test('urn selection is equiprobable by urn, not by pooled ballots',()=>{near(val(at(400).parts[0].answer),73/135);assert.notEqual(val(at(400).parts[0].answer),900/1700);near(val(at(400).parts[1].answer),27/62);});
test('chapter sampling weights chapters by page count',()=>{const pages=Array.from({length:440},(_,i)=>({chapter:i<140?1:i<240?2:i<390?3:4,error:i<7||(i>=140&&i<144)||(i>=240&&i<243)}));near(val(at(528).parts[0].answer),pages.filter(x=>x.error).length/440);near(val(at(528).parts[1].answer),pages.filter(x=>!x.error&&x.chapter===2).length/pages.filter(x=>!x.error).length);});
test('loan comparison uses posterior probabilities and defeats all three false claims',()=>{const housing=.5*.2,consumer=.2*.7,industry=.3*.15,total=housing+consumer+industry;near(housing/total,20/57);near(consumer/total,28/57);assert.ok(housing<consumer);assert.match(at(643).parts[2].answer,/^No:.*20.*57.*28.*57/);assert.ok(Math.abs(housing/total-.5)>1e-6);assert.ok(Math.abs(housing/total-.2)>1e-6);});
test('canonical literal, scores, PDF hashes, disjoint cells and conditioned universes are retained',()=>{const canonical=fs.readFileSync('artifacts/pau-canonical-andalucia-madrid/runs/run-a/andalucia-canonical-exercises.jsonl','utf8').trim().split(/\r?\n/).map(JSON.parse);for(const c of cases){const r=at(c.index),s=canonical.find(x=>x.exerciseId===r.exerciseId);assert.equal(r.sourceLiteral,s.officialPrompt);assert.deepEqual(r.scoreEvidence,s.scoreEvidence);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(r.officialSource.path)).digest('hex'),r.officialSource.documentHash);assert.equal(c.cells.reduce((s,x)=>s+x[2],0),c.scale);for(const q of c.queries)if(q.d!=='all')assert.ok(q.n.every(x=>q.d.includes(x)));}});
test('repeat and reversed order preserve mathematical outputs',()=>{const sig=xs=>xs.map(x=>[x.exerciseId,x.sourceLiteral,x.parts]).sort((a,b)=>a[0].localeCompare(b[0]));assert.deepEqual(sig(rows),sig(buildSourceBranchBatch().batch.records));assert.deepEqual(sig(rows),sig(buildSourceBranchBatch('batch-0282',[...cases].reverse()).batch.records));});
