import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {cases,buildLinearMatrixBatch} from '../scripts/resolve-andalucia-linear-matrix-mixed.mjs';
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const transpose=A=>A[0].map((_,j)=>A.map(r=>r[j]));
const sub=(A,B)=>A.map((r,i)=>r.map((x,j)=>x-B[i][j]));
const mul=(A,B)=>A.map(r=>B[0].map((_,j)=>r.reduce((s,x,k)=>s+x*B[k][j],0)));
const inverse=([[a,b],[c,d]])=>[[d,-b],[-c,a]].map(r=>r.map(x=>x/(a*d-b*c)));
const times=(A,k)=>A.map(r=>r.map(x=>x*k));
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} ≠ ${b}`);
const matrixEqual=(A,B)=>A.every((r,i)=>r.every((x,j)=>Math.abs(x-B[i][j])<1e-9));
test('both matrix answers satisfy the original equations, with three false distinct alternatives',()=>{
 for(const c of cases){const L=c.index===135?sub(c.A,transpose(c.A)):c.A,R=c.index===135?c.B:times(sub(c.C,transpose(c.D)),2);
 assert.ok(matrixEqual(mul(L,c.X),R));assert.ok(matrixEqual(mul(inverse(L),R),c.X));
 for(const w of c.wrongX)assert.ok(!matrixEqual(mul(L,w),R));
 const all=[c.X,...c.wrongX];for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++)assert.ok(!matrixEqual(all[i],all[j]));
 }
});
test('matrix distractors are generated by the documented operations, not arbitrary entries',()=>{
 const a=cases[0],b=cases[1];assert.ok(matrixEqual(times(a.X,-1),a.wrongX[0]));assert.ok(matrixEqual(transpose(a.X),a.wrongX[1]));assert.ok(matrixEqual(mul(inverse(a.A),a.B),a.wrongX[2]));
 assert.ok(matrixEqual(mul(inverse(b.A),times(sub(b.C,b.D),2)),b.wrongX[0]));assert.ok(matrixEqual(mul(times(sub(b.C,transpose(b.D)),2),inverse(b.A)),b.wrongX[1]));assert.ok(matrixEqual(times(b.X,.5),b.wrongX[2]));
});
test('square extrema and continuum of minimizers independently checked',()=>{
 const v=[[1,0],[0,1],[-1,0],[0,-1]],F=(x,y)=>3*x+2*y+7,G=(x,y)=>x+y+6;
 assert.deepEqual(v.map(([x,y])=>F(x,y)),[10,9,4,5]);assert.deepEqual(v.map(([x,y])=>G(x,y)),[7,7,5,5]);
 for(let i=0;i<=100;i++){const t=i/100;near(G(-t,t-1),5);}
 for(let i=-50;i<=50;i++)for(let j=-50;j<=50;j++){const x=i/50,y=j/50;if(Math.abs(x)+Math.abs(y)<=1){assert.ok(F(x,y)<=10+1e-9);assert.ok(G(x,y)>=5-1e-9);}}
 near(G(-.5,-.5),5);assert.ok(F(0,1)<F(1,0));assert.ok(G(1,0)>5);
});
test('pentagon extrema and full optimal edge checked by convex combinations',()=>{
 const v=[[0,2],[2,0],[4,0],[6,3],[3,6]],F=(x,y)=>4*x-3*y+8;
 assert.deepEqual(v.map(([x,y])=>F(x,y)),[2,16,24,23,2]);
 for(let i=0;i<=100;i++){const t=i/100;near(F(3*t,2+4*t),2);for(const a of v)for(const b of v){const f=F(t*a[0]+(1-t)*b[0],t*a[1]+(1-t)*b[1]);assert.ok(f>=2-1e-9&&f<=24+1e-9);}}
 near(F(1.5,4),2);assert.ok(F(6,3)<24);assert.ok(F(2,0)>2);
});
test('sources intact, complete task coverage and unique formatted options',()=>{
 const records=buildLinearMatrixBatch('test').batch.records;assert.equal(records.length,2);
 for(const r of records){assert.equal(sha(fs.readFileSync(r.officialSource.path)),r.officialSource.documentHash);assert.equal(r.parts.length,2);assert.deepEqual(r.parts.map(p=>p.partId),['a','b']);for(const p of r.parts){assert.ok(p.solutionSteps.length>=7);assert.equal(new Set([p.answer,...p.distractors]).size,4);}}
});
test('determinism, reversed order and read-only rollback preserve production',()=>{
 const paths=['app.js','data/andalucia-pau-runtime.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=paths.map(p=>sha(fs.readFileSync(p)));
 const normalize=rs=>[...rs].sort((a,b)=>a.exerciseId.localeCompare(b.exerciseId));
 assert.deepEqual(normalize(buildLinearMatrixBatch('same').batch.records),normalize(buildLinearMatrixBatch('same',[...cases].reverse()).batch.records));assert.deepEqual(before,paths.map(p=>sha(fs.readFileSync(p))));
});
