import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,buildClientsLogisticsBatch} from '../scripts/resolve-andalucia-linear-clients-logistics.mjs';
import {clientsLogisticsObservations,clientsLogisticsReplacements} from '../scripts/andalucia-clients-logistics-pdf-evidence.mjs';
import {renderRationalGraph} from '../scripts/resolve-andalucia-linear-rational-and-faces.mjs';
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),rows=()=>buildClientsLogisticsBatch('clients-logistics-test').batch.records,close=(a,b,t=1e-7)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
for(const c of cases)test(`${c.index} exact dual signs, feasible optimum, all polygon vertices and independent grid extremum`,()=>{
 const sign=c.minimize?-1:1;for(let j=0;j<2;j++)close(sign*c.constraints.reduce((s,r,i)=>s+r[j]*c.dual[i],0),c.objective[j]);assert.ok(c.dual.every(x=>x>=0));close(sign*c.constraints.reduce((s,r,i)=>s+r[2]*c.dual[i],0),c.extreme);
 assert.ok(c.constraints.every(([a,b,k])=>a*c.optimum[0]+b*c.optimum[1]<=k));let best=c.minimize?Infinity:-Infinity,hits=[];const step=c.continuous?10:1;
 for(let x=0;x<=c.domain.x[1];x+=step)for(let y=0;y<=c.domain.y[1];y+=step){if(!c.constraints.every(([a,b,k])=>a*x+b*y<=k))continue;const z=c.objective[0]*x+c.objective[1]*y;close(sign*(c.extreme-z),c.constraints.reduce((s,[a,b,k],i)=>s+c.dual[i]*(k-a*x-b*y),0));assert.ok(sign*(c.extreme-z)>=-1e-8);if(sign*(z-best)>0){best=z;hits=[];}if(z===best)hits.push([x,y]);}
 close(best,c.extreme);assert.deepEqual(hits,[c.optimum]);const p=rows().find(r=>r.correctionEvidence.parameters.index===c.index).parts[0],v=p.verification.numericalEvidence;close(c.minimize?v.min:v.max,c.extreme);
 for(const[x,y]of v.wrongPoints){const feasible=c.constraints.every(([a,b,k])=>a*x+b*y<=k),z=c.objective[0]*x+c.objective[1]*y;assert.ok(!feasible||sign*(c.extreme-z)>0);}
 const svg=renderRationalGraph(p.visual);assert.match(svg,/<polygon/);assert.doesNotMatch(svg,/NaN|undefined/);assert.equal(svg,renderRationalGraph(p.visual));
});
test('1385 documented recovered values are not inferred from the damaged extraction',()=>{const r=rows().find(r=>r.correctionEvidence.parameters.index===1385),p=clientsLogisticsReplacements({...r,queueIndex:1385})[0];assert.doesNotMatch(r.sourceLiteral,/15000|17000/);assert.match(p[1],/15000/);assert.match(p[1],/17000/);assert.match(p[1],/14 viajes/);assert.match(p[1],/10 viajes y como mucho 24/);assert.match(p[1],/B₁ y B₂/);assert.equal(15000*12+17000*12,384000);});
test('1460 nonzero silver residual preserved; 1598 integer optimum satisfies all three constraints',()=>{assert.deepEqual([50-10-2*20,40-2*10-20,25-20],[0,0,5]);const c=cases.find(c=>c.index===1598);assert.deepEqual(c.optimum,[1,5]);assert.equal(2*1+5,7);assert.equal(4*1+5,9);assert.ok(1+5>=3);assert.ok(4*2+3>9);});
test('source and page hashes bind six official exercises; projections round trip without overwriting source',()=>{for(const r of rows()){const i=r.correctionEvidence.parameters.index,o=clientsLogisticsObservations.find(o=>o[0]===i);assert.equal(sha(fs.readFileSync(r.officialSource.path)),o[1]);assert.equal(sha(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${i}.png`)),o[4]);let t=r.sourceLiteral;for(const[b,a]of clientsLogisticsReplacements({...r,queueIndex:i})){const at=t.indexOf(b);assert.ok(at>=0);const next=t.slice(0,at)+a+t.slice(at+b.length);assert.equal(next.slice(0,at)+b+next.slice(at+a.length),t);t=next;}assert.doesNotMatch(t,/BLOQUE B|undefined/);}});
test('six unsegmented exercises have complete multi-question answers, distinct options and pedagogical developments',()=>{const r=rows();assert.equal(r.length,6);for(const x of r){assert.equal(x.parts.length,1);const p=x.parts[0];assert.equal(p.partId,'whole');assert.ok(p.solutionSteps.length>=9);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.finalAnswer,p.answer);assert.equal(p.verification.verified,true);assert.ok(p.visual);assert.equal(x.primaryTopic,'Programación lineal');}});
test('reproducible and order-invariant construction preserves queue/runtime; rollback source evidence remains literal',()=>{const files=['data/andalucia-pau-runtime.js','math-renderer.js','artifacts/pau-andalucia-mass-processing/resolution-queue.jsonl'],before=files.map(p=>sha(fs.readFileSync(p))),sort=r=>r.sort((a,b)=>a.exerciseId.localeCompare(b.exerciseId));assert.deepEqual(rows(),rows());assert.deepEqual(sort(rows()),sort(buildClientsLogisticsBatch('clients-logistics-test',[...cases].reverse()).batch.records));assert.deepEqual(files.map(p=>sha(fs.readFileSync(p))),before);});
