import test from 'node:test';import assert from 'node:assert/strict';
import {cases,buildEventComparisonBatch} from '../scripts/resolve-andalucia-probability-pdf-event-comparisons.mjs';
import {sourceProjection,restoreText} from '../scripts/project-andalucia-inference-source-glyphs.mjs';
const records=buildEventComparisonBatch().batch.records,at=i=>records.find(r=>r.correctionEvidence.parameters.index===i);
const number=s=>{const m=s.match(/^frac\{(-?\d+)\}\{(\d+)\}$/);return m?+m[1]/+m[2]:Number(s);};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-12,`${a} != ${b}`);
function check(i,expected){for(const[j,e]of expected.entries()){const p=at(i).parts[j],xs=[p.answer,...p.distractors].map(number);near(xs[0],e);assert.equal(xs.filter(x=>Math.abs(x-e)<1e-12).length,1);assert.equal(new Set(xs.map(x=>x.toFixed(12))).size,4);assert.ok(xs.every(x=>Number.isFinite(x)&&x>=0&&x<=1));}}
function independent(i,pi,A,B,J){const p=at(i).parts[pi],v=p.verification.numericalEvidence;near(v.R/v.N,A);near(v.C/v.N,B);near(v.J/v.N,J);const yes=Math.abs(A*B-J)<1e-12;assert.equal(v.independent,yes);assert.equal(v.optionClaims.filter(x=>x.independent===yes&&Math.abs(x.joint[0]/x.joint[1]-J)<1e-12&&Math.abs(x.product[0]/x.product[1]-A*B)<1e-12).length,1);}
test('eight page-verified event exercises, 26 parts and 78 distractors',()=>{assert.equal(records.length,8);assert.equal(records.flatMap(x=>x.parts).length,26);for(const r of records)for(const p of r.parts){assert.equal(p.distractors.length,3);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.ok(p.prompt.length>0);assert.equal(p.answer,p.finalAnswer);assert.ok(p.solutionSteps.length>=6);}});
test('complement B gives joint by subtraction, conditional by division, then independence',()=>{const J=.25-.1;check(479,[J,.6-J,J/.6]);independent(479,3,.25,.6,J);});
test('at most one includes no passes; independence and incompatibility are distinct',()=>{check(500,[.5+.7-2*.3,1-.3,(.5-.3)/(1-.7)]);const v=at(500).parts[3].verification.numericalEvidence;assert.deepEqual(v.claims[0],[false,false]);assert.equal(v.claims.filter(([i,k])=>i===(.3===.5*.7)&&k===(.3===0)).length,1);});
test('missing formula prompts recovered from official page, exclusive differences and conditional',()=>{const J=.6*.3;check(537,[.6+.3-J,.6+.3-2*J,(.3-J)/(1-.6)]);assert.deepEqual(at(537).parts.slice(0,3).map(x=>x.prompt),['P(A ∪ B)','P(A − B) + P(B − A)','P(B/Aᶜ)']);assert.deepEqual(at(537).parts[3].verification.numericalEvidence.claims[0],[true,false]);});
test('neither A nor B is not the intersection; conditional no B uses complement denominator',()=>{const J=.3+.6-(1-.28);check(958,[J,(.3-J)/(1-.6)]);independent(958,2,.3,.6,J);});
test('phone inverse total probability checked by independent substitution',()=>{const x=(.53-.35*.8-.2*.05)/.45;near(.35*.8+.45*x+.2*.05,.53);check(1099,[x,.45*x/.53]);});
test('candy flavours compare all fruit against mint, not orange alone',()=>{const sn=.4-.4*.4,l=.6*.25+.4*.3;check(1352,[sn/.6]);const v=at(1352).parts[1].verification.numericalEvidence;near(v.fruit/100,.4+l);near(v.mint/100,1-.4-l);assert.equal(v.claims.filter(([a,b])=>Math.abs(a/100-(.4+l))<1e-12&&Math.abs(b/100-(1-.4-l))<1e-12).length,1);});
test('diet from sport-conditioned diet is independently inverted using Bayes',()=>{const S=.17/.5,D=1-.58-S+.17;check(1404,[1-.58,.17/D]);independent(1404,2,D,S,.17);});
test('platform and email exclusive or, conditional and independence',()=>{const J=.75+.4-(1-.15);check(1468,[J,.75+.4-2*J,(.75-J)/(1-.4)]);independent(1468,3,.75,.4,J);});
test('source projections restore every original byte and preserve official score evidence',()=>{for(const c of cases){const r=at(c.index),p=sourceProjection({...r,queueIndex:c.index});assert.equal(restoreText(p.text,p.changes),r.sourceLiteral);assert.equal(p.evidence.humanApproval,false);assert.ok(!/[\u0000-\u0008\u000e-\u001f\ue000-\uf8ff]/.test(p.text));assert.deepEqual(p.text.match(/\([\d.,]+ puntos?\)/g),r.sourceLiteral.match(/\([\d.,]+ puntos?\)/g));assert.equal(c.cells.reduce((s,x)=>s+x[2],0),c.scale);}});
test('replay and reversed case order preserve mathematical results and immutable sources',()=>{const sig=rs=>rs.map(r=>[r.exerciseId,r.sourceLiteral,r.parts,r.scoreEvidence]).sort((a,b)=>a[0].localeCompare(b[0]));assert.deepEqual(sig(records),sig(buildEventComparisonBatch().batch.records));assert.deepEqual(sig(records),sig(buildEventComparisonBatch('batch-0287',[...cases].reverse()).batch.records));});
