import test from 'node:test';import assert from 'node:assert/strict';
import {cases,buildContextBatch} from '../scripts/resolve-andalucia-probability-final-pdf-contexts.mjs';
import {sourceProjection,restoreText} from '../scripts/project-andalucia-inference-source-glyphs.mjs';
const records=buildContextBatch().batch.records,at=i=>records.find(r=>r.correctionEvidence.parameters.index===i);
const value=s=>{const m=s.match(/^frac\{(-?\d+)\}\{(\d+)\}$/);return m?+m[1]/+m[2]:Number(s);};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-12,`${a} != ${b}`);
function check(i,j,result){const p=at(i).parts[j],xs=[p.answer,...p.distractors].map(value);near(xs[0],result);assert.equal(xs.filter(x=>Math.abs(x-result)<1e-12).length,1);assert.equal(new Set(xs.map(x=>x.toFixed(12))).size,4);assert.ok(xs.every(x=>Number.isFinite(x)&&x>=0&&x<=1));}
function tuple(i,j,results){const v=at(i).parts[j].verification.numericalEvidence;v.values.forEach(([n,d],k)=>near(n/d,results[k]));const all=[v.values,...v.bad].map(a=>a.map(([n,d])=>n/d));assert.equal(all.filter(a=>a.every((x,k)=>Math.abs(x-results[k])<1e-12)).length,1);assert.equal(new Set(all.map(a=>a.map(x=>x.toFixed(12)).join('|'))).size,4);assert.ok(all.flat().every(x=>x>=0&&x<=1));}
test('six official exercises, fifteen parts, forty-five distinct distractors and complete development',()=>{assert.equal(records.length,6);assert.equal(records.flatMap(x=>x.parts).length,15);for(const r of records)for(const p of r.parts){assert.equal(p.distractors.length,3);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.finalAnswer,p.answer);assert.ok(p.prompt.length>0);assert.ok(p.solutionSteps.length>=6);}});
test('languages: product, total probability and Bayes independently computed',()=>{const joint=.65*.4,G=joint+.35*.25;check(670,0,joint);check(670,1,G);check(670,2,joint/G);near(value(at(670).parts[1].distractors[2]),.65*.65+.35*.25);});
test('separate conditional and independent setups are never combined',()=>{check(888,0,(.5+.4-.8)/.4);check(888,1,1-(1-.3)*(1-.8));});
test('streaming: genre weights, error-conditioned Bayes and third-stage satisfaction',()=>{const R=.62*.7+.25*.75+.13*.15;check(1094,0,R);check(1094,1,.25*(1-.75)/(1-R));check(1094,2,.62*.7*.55);});
test('employees: complements and collective posterior preserve distinct categories',()=>{const noOperario=.35*.4+.2*.3;check(1102,0,noOperario);check(1102,1,noOperario/(.35+.2));const v=at(1102).parts[2].verification.numericalEvidence,weights=[.45*.8,.35*.6,.2*.7],total=weights.reduce((a,b)=>a+b,0);assert.equal(v.claims.filter(c=>c.most==='Operarios'&&c.values.every((n,k)=>Math.abs(n/v.denominator-weights[k]/total)<1e-12)).length,1);assert.equal(new Set(v.claims.map(c=>JSON.stringify(c.values))).size,4);});
test('die sets checked by exhaustive membership, with only one correct tuple',()=>{const universe=[1,2,3,4,5,6],A=x=>x>4,B=x=>x%2===0;const expected=[A,B,x=>!A(x)||B(x),x=>A(x)&&!B(x),x=>!(A(x)&&B(x))].map(f=>universe.filter(f)),v=at(1285).parts[0].verification.numericalEvidence;assert.deepEqual(v.values,expected);assert.equal([v.values,...v.bad].filter(x=>JSON.stringify(x)===JSON.stringify(expected)).length,1);assert.equal(new Set([v.values,...v.bad].map(JSON.stringify)).size,4);tuple(1285,1,[universe.filter(x=>!A(x)&&!B(x)).length/6,universe.filter(x=>!A(x)||!B(x)).length/6]);});
test('conditional branches determine tuple and reject independence',()=>{const J=.6*.8,B=J+.4*.1;tuple(1471,0,[B,J,.6+B-J]);const v=at(1471).parts[1].verification.numericalEvidence;assert.equal(v.independent,false);near(v.J/v.N,J);near(v.R/v.N,.6);near(v.C/v.N,B);assert.equal(v.optionClaims.filter(x=>x.independent===false&&Math.abs(x.joint[0]/x.joint[1]-J)<1e-12&&Math.abs(x.product[0]/x.product[1]-.6*B)<1e-12).length,1);});
test('six PDF projections are reversible and retain score evidence unchanged',()=>{for(const c of cases){const r=at(c.index),p=sourceProjection({...r,queueIndex:c.index});assert.equal(restoreText(p.text,p.changes),r.sourceLiteral);assert.equal(p.evidence.humanApproval,false);assert.ok(!/[\u0000-\u0008\u000e-\u001f\ue000-\uf8ff]/.test(p.text));assert.deepEqual(p.text.match(/\([\d.,]+ puntos?\)/g),r.sourceLiteral.match(/\([\d.,]+ puntos?\)/g));}});
test('replay and reversed input order preserve sources, solutions and results',()=>{const sig=rs=>rs.map(r=>[r.exerciseId,r.sourceLiteral,r.parts,r.scoreEvidence]).sort((a,b)=>a[0].localeCompare(b[0]));assert.deepEqual(sig(records),sig(buildContextBatch().batch.records));assert.deepEqual(sig(records),sig(buildContextBatch('batch-0288',[...cases].reverse()).batch.records));});
