import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {cases,observations,statements,proof,solve,graphs,curves,renderSourceAreaGraph,buildSourceAreasBatch} from '../scripts/resolve-andalucia-mates-source-areas.mjs';
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),D=(f,x)=>(f(x+1e-5)-f(x-1e-5))/2e-5;
function integral(f,a,b,n=20000){let s=0;for(let i=0;i<n;i++)s+=f(a+(i+.5)*(b-a)/n);return s*(b-a)/n;}
function reject(actual,wrong){assert.equal(new Set(wrong).size,3);for(const x of wrong)assert.ok(Math.abs(actual-x)>1e-5);}
test('six exact source page hashes and official question boundaries',()=>{for(const o of observations)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(`tmp/pdfs/inference-source-glyphs/q${o[0]}.png`)).digest('hex'),o[4]);assert.match(statements[61],/√\(ax\)/);assert.match(statements[134],/y=2ax/);assert.doesNotMatch(statements[61]+statements[134],/matriz|\[\[/i);});
test('logarithmic square derivative sign and unique minimum',()=>{const f=x=>Math.log(x)**2;for(const x of [.02,.2,.9,1,1.1,2,4])near(D(f,x),2*Math.log(x)/x,1e-4);near(f(1),0);assert.ok(D(f,.5)<0&&D(f,2)>0);assert.ok(f(Math.E)>f(1));});
test('logarithmic area independently integrated and all three distractors rejected',()=>{const f=curves[49][0],H=x=>x*Math.log(x)**2-2*x*Math.log(x)+2*x;near(integral(f,1,Math.E),Math.E-2);for(const x of [.3,1,2,3])near(D(H,x),f(x));reject(Math.E-2,[Math.E,2-Math.E,3*Math.E-2]);});
test('piecewise continuity and parameter distractors tested in original radical',()=>{const p=proof({index:61});near(Math.sqrt(8*p.parameter),(64-32)/4);for(const a of [1,64,-8])assert.ok(!Number.isFinite(Math.sqrt(8*a))||Math.abs(Math.sqrt(8*a)-8)>1);});
test('piecewise integral verified with separate quadratures and primitive derivatives',()=>{const f=x=>Math.sqrt(8*x),h=x=>(x*x-32)/(x-4),H=x=>x*x/2+4*x-16*Math.log(x-4),p=proof({index:61});near(integral(f,0,8,100000),128/3,2e-6);near(integral(h,8,10),p.secondIntegral);near(128/3+integral(h,8,10),p.total);for(const x of [8,8.5,9,10])near(D(H,x),h(x));reject(p.total,[206/3+16*Math.log(1.5),26-16*Math.log(1.5),206/3-16*Math.log(1.25)]);});
test('absolute value graph branches slopes and both positive lobes',()=>{const f=curves[66][0];for(const x of [-3,-1,0,1,1.9,2.1,3])near(f(x),x<2?2*x-x*x:x*x-2*x);near(f(1),1);near(f(2),0);near((f(2)-f(2-1e-6))/1e-6,-2,2e-6);near((f(2+1e-6)-f(2))/1e-6,2,2e-6);near(integral(f,0,2),4/3);near(integral(f,2,3),4/3);reject(8/3,[4/3,0,-8/3]);});
test('cubic and parabola intersections verified in both source functions',()=>{const [f,g]=curves[105];for(const [x,y]of proof({index:105}).intersections){near(f(x),y);near(g(x),y);}for(const [x,y]of [[2,10],[-2,-2],[1,1]])assert.ok(Math.abs(f(x)-y)>1e-6||Math.abs(g(x)-y)>1e-6);for(let i=1;i<100;i++)assert.ok(g(i/100)>f(i/100));near(integral(x=>g(x)-f(x),0,1),5/12);reject(5/12,[11/12,3/4,-5/12]);});
test('tangent point slope and all three proposed wrong lines',()=>{const f=curves[130][0];near(f(1),-3);near(D(f,1),-1);for(const [m,b]of [[1,-4],[-1,-3],[-3,0]])assert.ok(Math.abs(m+1)>1e-5||Math.abs(m+b+3)>1e-5);});
test('double tangency root and area independently verified',()=>{const [f,g]=curves[130];for(let i=-30;i<30;i++){const x=i/10;near(f(x)-g(x),(x-1)**2*(x+2));}for(const [x,y]of proof({index:130}).intersections){near(f(x),y);near(g(x),y);}near(integral(x=>f(x)-g(x),-2,1),27/4);near(integral(x=>x**3-3*x,-2,1),3/4);reject(27/4,[3/4,27/2,-27/4]);});
test('parameter area determined independently over a range of parameters',()=>{for(const a of [.2,.5,1,2,3,5])near(integral(x=>3*a*x-x*x,0,3*a),9*a**3/2,2e-6);near(9*2**3/2,36);for(const a of [8,Math.cbrt(24),-2])assert.ok(a<=0||Math.abs(9*a**3/2-36)>1);});
test('five original deterministic source graphs preserve curve data and visible crossings',()=>{for(const index of[49,66,105,130,134]){const g=graphs[index],svg=renderSourceAreaGraph(g);assert.equal(svg,renderSourceAreaGraph(structuredClone(g)));assert.match(svg,/<polygon/);assert.equal((svg.match(/<polyline /g)||[]).length,2);assert.doesNotMatch(svg,/NaN|Infinity|undefined|<script/);for(const [x,y]of g.points)near(curves[g.index][0](x),y);}assert.throws(()=>renderSourceAreaGraph({...graphs[49],area:[0,1]}));});
test('twelve parts include all official subparts, full derivation and verified plots',()=>{let count=0,plot=0;for(const c of cases)for(const p of solve(c,'unchanged official whole exercise')){count++;assert.equal(p.answer,p.finalAnswer);assert.equal(new Set([p.answer,...p.distractors]).size,4);assert.equal(p.distractorEvidence.length,3);assert.ok(p.solutionSteps.length>=6);if(p.visual){plot++;assert.deepEqual(p.visual,graphs[c.index]);}}assert.equal(count,12);assert.equal(plot,8);});
test('source-bound batch invariant under reversed order and not automatically published',()=>{const a=buildSourceAreasBatch('test').batch,b=buildSourceAreasBatch('test',[...cases].reverse()).batch;assert.deepEqual(a.records,[...b.records].reverse());assert.equal(a.records.length,6);for(const r of a.records){assert.equal(r.subject,'Matemáticas II');assert.equal(r.examSlot,3);assert.equal(r.qualityGates.publication,'NOT_ENABLED');}});
